Repository aquasecurity/cloudsploit, pull requests merged in 2021-07, with the labels that each got.

#753 feature/AKD-228: Plugin to check log_disconnections parameter
  exports.js
  plugins/alibaba/rds/rdsLogDisconnectionsEnabled.js
  plugins/alibaba/rds/rdsLogDisconnectionsEnabled.spec.js
Labels: readytogo, reviewed

#754 feature/AKD-227: Plugin to check log_connections parameter
  exports.js
  package-lock.json
  package.json
  plugins/alibaba/rds/rdsLogConnectionEnabled.js
  plugins/alibaba/rds/rdsLogConnectionEnabled.spec.js
Labels: reviewed

#783 feature/AKD-285: Plugin to check bucket pay per requester enabled and related unit tests
  collectors/alibaba/collector.js
  collectors/alibaba/oss/getBucketRequestPayment.js
  collectors/alibaba/oss/index.js
  exports.js
  plugins/alibaba/oss/bucketPayByRequester.js
  plugins/alibaba/oss/bucketPayByRequester.spec.js
Labels: reviewed

#788 feature/SAAS-1843: Added AWS ELB SSl Termination plugin and test cases
  exports.js
  plugins/aws/elbv2/elbv2SslTermination.js
  plugins/aws/elbv2/elbv2SslTermination.spec.js
Labels: reviewed

#781 feature/AKD-283: Plugin to check bucket transfer acceleration and unit tests
  exports.js
  plugins/alibaba/oss/ossBucketTransferAcceleration.js
  plugins/alibaba/oss/ossBucketTransferAcceleration.spec.js
Labels: reviewed

#782 feature/AKD-284: Plugin to check bucket cross region replication and unit tests
  exports.js
  plugins/alibaba/oss/bucketCrossRegionReplication.js
  plugins/alibaba/oss/bucketCrossRegionReplication.spec.js
Labels: reviewed

#756 feature/AKD-275: Added Azure 'Azure Monitor Logs Enabled' Plugin and test cases
  exports.js
  plugins/azure/monitor/monitorLogsEnabled.js
  plugins/azure/monitor/monitorLogsEnabled.spec.js
Labels: readytogo, reviewed

#786 feature/AKD-181: Added 'SSL Access Only Enabled' plugin and test cases
  collectors/azure/collector.js
  exports.js
  helpers/azure/locations.js
  plugins/azure/redisCache/sslAccessOnlyEnabled.js
  plugins/azure/redisCache/sslAccessOnlyEnabled.spec.js
Labels: reviewed

#787 Added Security Center Plugins and test cases
  exports.js
  plugins/azure/securitycenter/monitorExternalAccounts.js
  plugins/azure/securitycenter/monitorExternalAccounts.spec.js
  plugins/azure/securitycenter/monitorIpForwarding.js
  plugins/azure/securitycenter/monitorIpForwarding.spec.js
  plugins/azure/securitycenter/monitorNextGenerationFirewall.js
  plugins/azure/securitycenter/monitorNextGenerationFirewall.spec.js
  plugins/azure/securitycenter/monitorSubscriptionOwners.js
  plugins/azure/securitycenter/monitorSubscriptionOwners.spec.js
Labels: readytogo, reviewed

#778 feature/storage-resource-naming: Added functionality to show full resource names for storage buckets
  plugins/google/storage/bucketLogging.js
  plugins/google/storage/bucketRetentionPolicy.js
  plugins/google/storage/bucketUniformAccess.js
  plugins/google/storage/bucketVersioning.js
Labels: readytogo

#792 modification/SAAS-1956: Added new regions
  plugins/oracle/compute/instanceMaxCount.js
Labels: readytogo

#799 SAAS-2073: Updated new deprecated versions
  plugins/aws/eks/eksKubernetesVersion.js
  plugins/aws/eks/eksKubernetesVersion.spec.js
Labels: readytogo

#803 modification: Removed end ip addr check
  plugins/azure/sqlserver/noPublicAccess.js
Labels: readytogo

#797 modification/SAAS-2065: Modified BigQuery, Kubernetes and DNS plugin to display resource names
  helpers/google/functions.js
  plugins/google/bigquery/datasetAllUsersPolicy.js
  plugins/google/bigquery/datasetAllUsersPolicy.spec.js
  plugins/google/dns/dnsSecEnabled.js
  plugins/google/dns/dnsSecEnabled.spec.js
  plugins/google/dns/dnsSecSigningAlgorithm.js
  plugins/google/dns/dnsSecSigningAlgorithm.spec.js
  plugins/google/kubernetes/aliasIpRangesEnabled.js
  plugins/google/kubernetes/aliasIpRangesEnabled.spec.js
  plugins/google/kubernetes/autoNodeRepairEnabled.js
  plugins/google/kubernetes/autoNodeRepairEnabled.spec.js
  plugins/google/kubernetes/autoNodeUpgradesEnabled.js
  plugins/google/kubernetes/autoNodeUpgradesEnabled.spec.js
  plugins/google/kubernetes/basicAuthenticationDisabled.js
  plugins/google/kubernetes/basicAuthenticationDisabled.spec.js
  plugins/google/kubernetes/clusterLabelsAdded.js
  plugins/google/kubernetes/clusterLabelsAdded.spec.js
  plugins/google/kubernetes/clusterLeastPrivilege.js
  plugins/google/kubernetes/clusterLeastPrivilege.spec.js
  plugins/google/kubernetes/cosImageEnabled.js
  plugins/google/kubernetes/cosImageEnabled.spec.js
  plugins/google/kubernetes/defaultServiceAccount.js
  plugins/google/kubernetes/defaultServiceAccount.spec.js
  plugins/google/kubernetes/kubernetesAlphaDisabled.js
  plugins/google/kubernetes/kubernetesAlphaDisabled.spec.js
  plugins/google/kubernetes/legacyAuthorizationDisabled.js
  plugins/google/kubernetes/legacyAuthorizationDisabled.spec.js
  plugins/google/kubernetes/loggingEnabled.js
  plugins/google/kubernetes/loggingEnabled.spec.js
  plugins/google/kubernetes/masterAuthorizedNetwork.js
  plugins/google/kubernetes/masterAuthorizedNetwork.spec.js
  plugins/google/kubernetes/monitoringEnabled.js
  plugins/google/kubernetes/monitoringEnabled.spec.js
  plugins/google/kubernetes/networkPolicyEnabled.js
  plugins/google/kubernetes/networkPolicyEnabled.spec.js
  plugins/google/kubernetes/podSecurityPolicyEnabled.js
  plugins/google/kubernetes/podSecurityPolicyEnabled.spec.js
  plugins/google/kubernetes/privateClusterEnabled.js
  plugins/google/kubernetes/privateClusterEnabled.spec.js
  plugins/google/kubernetes/privateEndpoint.js
  plugins/google/kubernetes/privateEndpoint.spec.js
  plugins/google/kubernetes/webDashboardDisabled.js
  plugins/google/kubernetes/webDashboardDisabled.spec.js
Labels: readytogo

#802 SAAS-1844: Modified plugins to add check to whitelist organization accounts
  exports.js
  helpers/aws/functions.js
  plugins/aws/iam/trustedCrossAccountRoles.js
  plugins/aws/iam/trustedCrossAccountRoles.spec.js
  plugins/aws/kms/kmsKeyPolicy.js
  plugins/aws/sns/snsCrossAccount.js
  plugins/aws/sns/snsCrossAccount.spec.js
  plugins/aws/sqs/sqsCrossAccount.js
  plugins/aws/sqs/sqsCrossAccount.spec.js
  plugins/aws/sqs/sqsPublicAccess.js
Labels: readytogo

#593 remediaton: AWS Glue Data Catalog Ecnryption Enabled
  plugins/aws/glue/dataCatalogEncryptionEnabled.js
Labels: readytogo

#807 HOTFIX: Added check to check projects length
  plugins/google/clb/clbCDNEnabled.js
  plugins/google/clb/clbSecurityPolicyEnabled.js
  plugins/google/iam/kmsUserSeparation.js
  plugins/google/iam/serviceAccountSeparation.js
  plugins/google/iam/serviceAccountUser.js
  plugins/google/logging/logSinksEnabled.js
Labels: readytogo

#808 SAAS-2109: Changed zone for region in results
  plugins/google/compute/autoscaleEnabled.js
  plugins/google/compute/connectSerialPortsDisabled.js
  plugins/google/compute/connectSerialPortsdisabled.spec.js
  plugins/google/compute/csekEncryptionEnabled.js
  plugins/google/compute/csekEncryptionEnabled.spec.js
  plugins/google/compute/instanceDefaultServiceAccount.js
  plugins/google/compute/instanceDefaultServiceAccount.spec.js
  plugins/google/compute/instanceDeletionProtection.js
  plugins/google/compute/instanceDeletionProtection.spec.js
  plugins/google/compute/instanceLeastPrivilege.js
  plugins/google/compute/instanceLeastPrivilege.spec.js
  plugins/google/compute/instanceLevelSSHOnly.js
  plugins/google/compute/instanceLevelSSHOnly.spec.js
  plugins/google/compute/instancePublicAccess.js
  plugins/google/compute/instancePublicAccess.spec.js
  plugins/google/compute/instancesMultiAz.js
  plugins/google/compute/instancesMultiAz.spec.js
  plugins/google/compute/ipForwardingDisabled.js
  plugins/google/compute/ipForwardingDisabled.spec.js
  plugins/google/compute/shieldedVmEnabled.js
  plugins/google/compute/shieldedVmEnabled.spec.js
Labels: readytogo

#794 fix/blobContainersPrivateAccess : Added check for public access flag at storage account level
  plugins/azure/blobservice/blobContainersPrivateAccess.js
  plugins/azure/blobservice/blobContainersPrivateAccess.spec.js
Labels: readytogo

#818 SAAS-2063: Fixed FP issue
  plugins/aws/cloudtrail/globalLoggingDuplicated.js
  plugins/aws/cloudtrail/globalLoggingDuplicated.spec.js
Labels: readytogo

#821 SAAS-2220: Fixed logical errors in code
  plugins/google/kubernetes/clusterLeastPrivilege.js
Labels: readytogo

#820 SAAS-2069: Fixed FN issue in S3 bucket secure transport
  plugins/aws/s3/bucketSecureTransportEnabled.js
  plugins/aws/s3/bucketSecureTransportEnabled.spec.js
Labels: readytogo

#829 HOTFIX: Added missing resource names for Google
  plugins/google/storage/bucketAllUsersPolicy.js
  plugins/google/storage/bucketAllUsersPolicy.spec.js
  plugins/google/vpcnetwork/dnsLoggingEnabled.js
  plugins/google/vpcnetwork/dnsLoggingEnabled.spec.js
Labels: readytogo

#811 Updated unusedAmi plugin to check for ami usage in launchTemplates
  collectors/aws/collector.js
  plugins/aws/ec2/unusedAmi.js
  plugins/aws/ec2/unusedAmi.spec.js
Labels: readytogo

#809 Unit test added for configService plugins in AWS
  plugins/aws/configservice/configServiceEnabled.spec.js
Labels: readytogo

#815 Unit tests for AWS ECR service
  plugins/aws/ecr/ecrRepositoryPolicy.spec.js
  plugins/aws/ecr/ecrRepositoryTagImmutability.spec.js
Labels: reviewed

#696 hotfix/vmAvailabilitySetLimit: Fixed bug and added test case
  collectors/azure/collector.js
  plugins/azure/virtualmachines/vmAvailabilitySetLimit.js
  plugins/azure/virtualmachines/vmAvailabilitySetLimit.spec.js
Labels: readytogo, reviewed

#801 SAAS - 1828 : Added Default Mapping for security center policy assignments
  helpers/azure/functions.js
  plugins/azure/securitycenter/monitorExternalAccounts.spec.js
  plugins/azure/securitycenter/monitorIpForwarding.spec.js
  plugins/azure/securitycenter/monitorNextGenerationFirewall.spec.js
  plugins/azure/securitycenter/monitorSubscriptionOwners.spec.js
Labels: readytogo
