Repository aquasecurity/cloudsploit, pull requests merged in 2021-06, with the labels that each got.

#636 feature/AKD-110: Added Azure 'Auto-Failover Groups Enabled' plugin and test cases
  collectors/azure/collector.js
  exports.js
  plugins/azure/sqlserver/autoFailoverGroupsEnabled.js
  plugins/azure/sqlserver/autoFailoverGroupsEnabled.spec.js
Labels: readytogo, reviewed

#640 feature/AKD-132: Added Azure 'Premium SSD Disabled' plugin and test cases
  exports.js
  plugins/azure/virtualmachines/premiumSsdDisabled.js
  plugins/azure/virtualmachines/premiumSsdDisabled.spec.js
Labels: question, reviewed

#741 feature/AKD-189: Added Azure 'Always On Enabled' Plugin and test cases
  exports.js
  plugins/azure/appservice/alwaysOnEnabled.js
  plugins/azure/appservice/alwaysOnEnabled.spec.js
Labels: reviewed

#734 feature/managedNatGateways: Added Azure 'Managed NAT Gateway In Use' Plugin and test cases
  collectors/azure/collector.js
  exports.js
  helpers/azure/locations.js
  plugins/azure/virtualnetworks/managedNatGateway.js
  plugins/azure/virtualnetworks/managedNatGateway.spec.js
Labels: reviewed

#739 feature/AKD-188: Added Azure 'Remote Debugging Disabled' Plugin and test cases
  exports.js
  plugins/azure/appservice/remoteDebuggingDisabled.js
  plugins/azure/appservice/remoteDebuggingDisabled.spec.js
Labels: readytogo, reviewed

#721 feature/noGatewayConnections: Added Azure 'No Network Gateways Connections' Plugin and test cases
  collectors/azure/collector.js
  exports.js
  helpers/azure/locations.js
  plugins/azure/virtualnetworks/noGatewayConnections.js
  plugins/azure/virtualnetworks/noGatewayConnections.spec.js
Labels: reviewed

#720 feature/gatewaysInUse: Added Azure 'Network Gateways Usage' Plugin and test cases
  collectors/azure/collector.js
  exports.js
  helpers/azure/locations.js
  plugins/azure/virtualnetworks/noNetworkGatewaysInUse.js
  plugins/azure/virtualnetworks/noNetworkGatewaysInUse.spec.js
Labels: reviewed

#716 feature/AKD-149: Added Azure 'Disk Volumes BYOK Encryption Enabled' plugin and test cases
  exports.js
  plugins/azure/virtualmachines/diskByokEncryptionEnabled.js
  plugins/azure/virtualmachines/diskByokEncryptionEnabled.spec.js
Labels: reviewed

#715 feature/AKD-144: Added Azure 'Scale Sets Health Monitoring Enabled' plugin and test cases
  exports.js
  plugins/azure/virtualmachines/scaleSetHealthMonitoring.js
  plugins/azure/virtualmachines/scaleSetHealthMonitoring.spec.js
Labels: readytogo, reviewed

#714 feature/AKD-143: Added Azure 'Virtual Machine Boot Diagnostics Enabled' plugin and test cases
  exports.js
  plugins/azure/virtualmachines/vmBootDiagnosticsEnabled.js
  plugins/azure/virtualmachines/vmBootDiagnosticsEnabled.spec.js
Labels: readytogo, reviewed

#713 feature/AKD-141: Added Azure 'Virtual Machine Performance Diagnostics Enabled' plugin and test cases
  exports.js
  plugins/azure/virtualmachines/performanceDiagnosticsEnabled.js
  plugins/azure/virtualmachines/performanceDiagnosticsEnabled.spec.js
Labels: reviewed

#712 feature/AKD-142: Added 'Azure Active Directory (AD) Authentication Enabled' plugin and test cases
  exports.js
  plugins/azure/virtualmachines/vmAdAuthenticationEnabled.js
  plugins/azure/virtualmachines/vmAdAuthenticationEnabled.spec.js
Labels: reviewed

#681 spec/virtualMachines: Added test cases for virtual machine plugins
  plugins/azure/virtualmachines/vmAgentEnabled.spec.js
  plugins/azure/virtualmachines/vmDiskDataEncryption.spec.js
  plugins/azure/virtualmachines/vmDiskOSEncryption.spec.js
  plugins/azure/virtualmachines/vmEndpointProtection.spec.js
  plugins/azure/virtualmachines/vmInstanceLimit.spec.js
Labels: reviewed

#666 fix/approvedVmImage : Fixed spell errors
  plugins/azure/virtualmachines/approvedVmImage.js
  plugins/azure/virtualmachines/approvedVmImage.spec.js
Labels: reviewed

#668 feature/AKD-147: Added Azure 'Old VM Disk Snapshots' plugin and test cases
  collectors/azure/collector.js
  exports.js
  helpers/azure/locations.js
  plugins/azure/virtualmachines/oldVmDiskSnapshots.js
  plugins/azure/virtualmachines/oldVmDiskSnapshots.spec.js
Labels: reviewed

#667 Feature/160 161 sql plugins(sql server db flags)
  exports.js
  plugins/google/sql/sqlContainedDatabaseAuth.js
  plugins/google/sql/sqlContainedDatabaseAuth.spec.js
  plugins/google/sql/sqlCrossDbOwnership.js
  plugins/google/sql/sqlCrossDbOwnership.spec.js
Labels: reviewed

#687 SQL plugin and spec file added for checking public access.
  exports.js
  plugins/google/sql/sqlNoPublicIps.js
  plugins/google/sql/sqlNoPublicIps.spec.js
Labels: reviewed

#747 Alibaba rds public access disabled plugin with spec file
  collectors/alibaba/collector.js
  exports.js
  plugins/alibaba/rds/rdsPublicAccess.js
  plugins/alibaba/rds/rdsPublicAccess.spec.js
Labels: reviewed

#748 Alibaba rds auditing enable plugin added with spec file
  .github/workflows/scans_ci.yml
  collectors/alibaba/collector.js
  exports.js
  plugins/alibaba/rds/rdsAuditingEnabled.js
  plugins/alibaba/rds/rdsAuditingEnabled.spec.js
Labels: reviewed

#732 feature/networkPeering: Added Azure 'Cross Subscription Network Peerings' Plugin and test cases
  collectors/azure/collector.js
  exports.js
  helpers/azure/locations.js
  plugins/azure/virtualnetworks/virtualNetworkPeering.js
  plugins/azure/virtualnetworks/virtualNetworkPeering.spec.js
Labels: reviewed

#680 feature/AKD-139: Added Azure 'VM Guest Level Diagnostics Enabled' plugin and test cases
  collectors/azure/collector.js
  exports.js
  plugins/azure/virtualmachines/guestLevelDiagnosticsEnabled.js
  plugins/azure/virtualmachines/guestLevelDiagnosticsEnabled.spec.js
Labels: question, reviewed

#679 feature/AKD-137: Added Azure 'Scale Sets Autoscale Notifications Enabled' plugin and test cases
  exports.js
  plugins/azure/virtualmachines/autoscaleNotificationsEnabled.js
  plugins/azure/virtualmachines/autoscaleNotificationsEnabled.spec.js
Labels: question, reviewed

#694 feature/AKD-145: Added 'VM Approved Extensions' plugin and test cases
  exports.js
  plugins/azure/virtualmachines/approvedVmExtension.js
  plugins/azure/virtualmachines/approvedVmExtension.spec.js
Labels: reviewed

#677 feature/AKD-126: Added Azure 'VM Desired SKU Size' plugin and test cases
  exports.js
  plugins/azure/virtualmachines/desiredSkuSize.js
  plugins/azure/virtualmachines/desiredSkuSize.spec.js
Labels: question, reviewed

#678 feature/AKD-138,129,130: Added Azure 'VM Backups Enabled', 'VM DailyBackup Retention Period', 'VM Instant Restore Backup Retention Period' plugin and test cases
  collectors/azure/collector.js
  exports.js
  helpers/azure/locations.js
  plugins/azure/virtualmachines/instantRestoreRetention.js
  plugins/azure/virtualmachines/instantRestoreRetention.spec.js
  plugins/azure/virtualmachines/vmBackupsEnabled.js
  plugins/azure/virtualmachines/vmBackupsEnabled.spec.js
  plugins/azure/virtualmachines/vmDailyBackupRetention.js
  plugins/azure/virtualmachines/vmDailyBackupRetention.spec.js
Labels: question, reviewed

#758 HOTFIX/sqs-public-access: Logic will check policy condition as well
  plugins/aws/sqs/sqsPublicAccess.js
Labels: readytogo

#775 feature/AKD-304: Added Google Pub/Sub Topic Encryption plugin and test cases
  collectors/google/collector.js
  exports.js
  helpers/google/functions.js
  helpers/google/index.js
  helpers/google/regions.js
  plugins/google/pubsub/topicEncryption.js
  plugins/google/pubsub/topicEncryption.spec.js
Labels: readytogo

#774 feature/AKD-214: Added ECS System Disks Encrypted plugin and test cases
  exports.js
  helpers/alibaba/functions.js
  helpers/alibaba/index.js
  plugins/alibaba/ecs/systemDisksEncrypted.js
  plugins/alibaba/ecs/systemDisksEncrypted.spec.js
Labels: readytogo

#773 feature/AKD-281: Added Alibaba OSS Bucket Versioning plugin and test cases
  exports.js
  plugins/alibaba/oss/ossBucketVersioning.js
  plugins/alibaba/oss/ossBucketVersioning.spec.js
Labels: readytogo

#772 feature/AKD-225: Added Alibaba RDS TDE Enabled plugin and test cases
  collectors/alibaba/collector.js
  exports.js
  plugins/alibaba/rds/rdsTdeEnabled.js
  plugins/alibaba/rds/rdsTdeEnabled.spec.js
Labels: readytogo

#771 feature/AKD-224: Added Alibaba RDS SQL Audit Retention Period plugin and test cases
  collectors/alibaba/collector.js
  exports.js
  plugins/alibaba/rds/rdsSqlAuditRetentionPeriod.js
  plugins/alibaba/rds/rdsSqlAuditRetentionPeriod.spec.js
Labels: readytogo

#770 feature/AKD-300: Added Google compute Instance Deletion Protection plugin and test cases
  exports.js
  plugins/google/compute/instanceDeletionProtection.js
  plugins/google/compute/instanceDeletionProtection.spec.js
Labels: readytogo

#769 feature/AKD-310: Added Google SQL Server Certificate Rotation plugin and test cases
  exports.js
  plugins/google/sql/serverCertificateRotation.js
  plugins/google/sql/serverCertificateRotation.spec.js
Labels: readytogo

#768 feature/AKD-307: Added Google Storage Auto Increase Enabled plugin and test cases
  exports.js
  plugins/google/sql/storageAutoIncreaseEnabled.js
  plugins/google/sql/storageAutoIncreaseEnabled.spec.js
Labels: readytogo

#766 feature/AKD-306: Added Google SQL PostgreSQL Max Connections flag plugin and test cases
  exports.js
  plugins/google/sql/postgresqlMaxConnections.js
  plugins/google/sql/postgresqlMaxConnections.spec.js
  plugins/google/sql/sqlContainedDatabaseAuth.spec.js
Labels: readytogo

#765 feature/AKD-176: Added KMS Key Protection Level plugin and test cases
  exports.js
  plugins/google/cryptographickeys/keyProtectionLevel.js
  plugins/google/cryptographickeys/keyProtectionLevel.spec.js
Labels: readytogo

#746 feature/AKD-254: Added Alibaba ECS Open All Ports Protocols plugin and test cases
  exports.js
  plugins/alibaba/ecs/openAllPortsProtocols.js
  plugins/alibaba/ecs/openAllPortsProtocols.spec.js
Labels: readytogo

#791 HOTFIX: Fixed Alibaba ECS Open All Ports Protocols
  plugins/alibaba/ecs/openAllPortsProtocols.js
Labels: readytogo

#745 GCP Shielded vm enabled for compute instances plugin added with spec file
  exports.js
  plugins/google/compute/shieldedVmEnabled.js
  plugins/google/compute/shieldedVmEnabled.spec.js
Labels: readytogo, reviewed

#704 Feature/166 - GCP computer instance default service account plugin with test cases
  exports.js
  plugins/google/compute/instanceDefaultServiceAccount.js
  plugins/google/compute/instanceDefaultServiceAccount.spec.js
Labels: readytogo, reviewed

#693 GCP SQL plugin updated for restorable backups.
  collectors/google/collector.js
  helpers/google/regions.js
  plugins/google/sql/dbRestorable.js
  plugins/google/sql/dbRestorable.spec.js
Labels: readytogo, reviewed

#700 GCP compute instance public access
  exports.js
  plugins/google/compute/instancePublicAccess.js
  plugins/google/compute/instancePublicAccess.spec.js
Labels: reviewed
