Repository aquasecurity/cloudsploit, pull requests merged in 2021-08, with the labels that each got.

#834 HOTFIX: AWS EC2 Unused Ami plugin
  plugins/aws/ec2/unusedAmi.js
Labels: readytogo

#831 HOTFIX: Fixed Pub/Sub Topic Encryption bug
  helpers/google/functions.js
  plugins/google/pubsub/topicEncryption.js
  plugins/google/pubsub/topicEncryption.spec.js
Labels: readytogo

#844 Updated failing unit test for inactiveUserDisabled
  plugins/alibaba/ram/inactiveUserDisabled.spec.js
Labels: reviewed

#813 SAAS-2221: Added Google Spanner Instance Node Count plugin and test cases
  collectors/google/collector.js
  exports.js
  helpers/google/index.js
  helpers/google/regions.js
  plugins/google/spanner/instanceNodeCount.js
  plugins/google/spanner/instanceNodeCount.spec.js
Labels: readytogo

#760 feature/AKD-220: Added Alibaba OSS Bucket CMK Encrypted plugin and test cases
  exports.js
  helpers/alibaba/functions.js
  plugins/alibaba/ecs/systemDisksEncrypted.js
  plugins/alibaba/oss/bucketCmkEncrypted.js
  plugins/alibaba/oss/bucketCmkEncrypted.spec.js
  plugins/google/pubsub/topicEncryption.spec.js
Labels: readytogo

#835 SAAS-2277: Added S3 Encryption setting to allow unencrypted static websites
  plugins/aws/s3/s3Encryption.js
  plugins/aws/s3/s3Encryption.spec.js
Labels: readytogo

#836 SAAS-2306: Added Google Deployment Manager Delete Expired Deployments
  collectors/google/collector.js
  exports.js
  helpers/google/regions.js
  plugins/google/deploymentmanager/deleteExpiredDeployments.js
  plugins/google/deploymentmanager/deleteExpiredDeployments.spec.js
Labels: readytogo

#817 SAAS-2233: Plugin to check access analyzer is enabled
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/accessanalyzer/accessAnalyzerEnabled.js
  plugins/aws/accessanalyzer/accessAnalyzerEnabled.spec.js
Labels: readytogo, reviewed

#859 SAAS-2321: Application Layer Secrets Encryption Level for GKE Clusters
  exports.js
  plugins/google/kubernetes/clusterEncryption.js
  plugins/google/kubernetes/clusterEncryption.spec.js
Labels: reviewed

#858 SAAS-2312: Node Encryption Level for GKE Cluster Nodes
  exports.js
  plugins/google/kubernetes/nodeEncryption.js
  plugins/google/kubernetes/nodeEncryption.spec.js
Labels: readytogo, reviewed

#857 SAAS-2314: Secure Boot Enabled for GKE Cluster Nodes
  exports.js
  plugins/google/kubernetes/secureBootEnabled.js
  plugins/google/kubernetes/secureBootEnabled.spec.js
Labels: readytogo, reviewed

#856 SAAS-2313: Integrity Monitoring Enabled for GKE Cluster Nodes
  exports.js
  plugins/google/kubernetes/integrityMonitoringEnabled.js
  plugins/google/kubernetes/integrityMonitoringEnabled.spec.js
Labels: readytogo, reviewed

#855 SAAS-2311: Shielded Nodes for GKE Clusters
  exports.js
  plugins/google/kubernetes/shieldedNodes.js
  plugins/google/kubernetes/shieldedNodes.spec.js
Labels: readytogo, reviewed

#853 SAAS-2299: Plugin to check PrivateLink is used in transfer servers
  exports.js
  plugins/aws/transfer/transferPrivateLinkInUse.js
  plugins/aws/transfer/transferPrivateLinkInUse.spec.js
Labels: readytogo, reviewed

#852 SAAS-2298: Plugin to check sender policy FW record exists in Route 53 DNS records
  exports.js
  plugins/aws/route53/senderPolicyFwRecordPresent.js
  plugins/aws/route53/senderPolicyFwRecordPresent.spec.js
Labels: readytogo, reviewed

#851 SAAS-2297: Plugin to check sender policy framework in use for AWS Route53
  exports.js
  plugins/aws/route53/senderPolicyFwInUse.js
  plugins/aws/route53/senderPolicyFwInUse.spec.js
Labels: readytogo, reviewed

#850 SAAS-2296: Plugin to check privacy protection enabled for Route53 domain
  collectors/aws/collector.js
  exports.js
  plugins/aws/route53/privacyProtection.js
  plugins/aws/route53/privacyProtection.spec.js
Labels: readytogo, reviewed

#849 SAAS-2295: Plugin to check AWS ES has TLS version 1.2
  exports.js
  plugins/aws/es/esTlsVersion.js
  plugins/aws/es/esTlsVersion.spec.js
Labels: readytogo, reviewed

#847 SAAS-2294: Plugin to check AWS Elasticsearch desired instance types
  exports.js
  plugins/aws/es/esDesiredInstanceTypes.js
  plugins/aws/es/esDesiredInstanceTypes.spec.js
Labels: readytogo, reviewed

#845 SAAS-2293: Plugin to check Elasticsearch use dedicated master nodes.
  exports.js
  plugins/aws/es/esDedicatedMasterEnabled.js
  plugins/aws/es/esDedicatedMasterEnabled.spec.js
Labels: readytogo, reviewed

#841 SAAS-2316: Instance Template Machine Types for Google Compute Engine
  collectors/google/collector.js
  exports.js
  helpers/google/regions.js
  plugins/google/compute/InstanceTemplateMachineTypes.spec.js
  plugins/google/compute/instanceTemplateMachineTypes.js
Labels: reviewed

#780 feature/AKD-280: Plugin to check OSS bucket lifecycle configuration
  collectors/alibaba/collector.js
  collectors/alibaba/oss/getBucketLifecycle.js
  exports.js
  plugins/alibaba/oss/ossBucketLifecycle.js
  plugins/alibaba/oss/ossBucketLifecycle.spec.js
Labels: reviewed

#800 feature/AkD-327: Plugin to check recently active IAM user
  exports.js
  plugins/aws/iam/iamUserInUse.js
  plugins/aws/iam/iamUserInUse.spec.js
Labels: reviewed

#816 SAAS-2231: Plugin to check access of AWS Support Center via IAM policy
  collectors/aws/collector.js
  exports.js
  plugins/aws/iam/iamSupportPolicy.js
  plugins/aws/iam/iamSupportPolicy.spec.js
Labels: reviewed

#839 SAAS-2308: Instance Automatic Restart Enabled for Google Compute Engine
  exports.js
  plugins/google/compute/automaticRestartEnabled.js
  plugins/google/compute/automaticRestartEnabled.spec.js
Labels: readytogo, reviewed

#840 SAAS-2309: Instance Desired Machine Types for Google Compute Engine
  exports.js
  plugins/google/compute/instanceDesiredMachineTypes.js
  plugins/google/compute/instanceDesiredMachineTypes.spec.js
Labels: readytogo, reviewed

#837 SAAS-2290: Plugin to check AWS ElasticSearch Cluster status
  collectors/aws/cloudwatch/getEsMetricStatistics.js
  collectors/aws/collector.js
  exports.js
  plugins/aws/es/esClusterStatus.js
  plugins/aws/es/esClusterStatus.spec.js
Labels: help wanted, reviewed

#819 SAAS-2062: Plugin to check for outdated Amazon Machine Images
  .gitignore
  exports.js
  package.json
  plugins/aws/ec2/outdatedAmiInUse.js
  plugins/aws/ec2/outdatedAmiInUse.spec.js
Labels: readytogo, reviewed

#846 SAAS-1822: Modified Google Audit Logging Enabled to check at org level
  collectors/google/collector.js
  helpers/google/index.js
  helpers/google/regions.js
  plugins/google/logging/auditLoggingEnabled.js
  plugins/google/logging/auditLoggingEnabled.spec.js
Labels: readytogo

#864 SAAS-2277: Added setting to skip S3 encryption for static websites
  collectors/alibaba/ack/describeClustersV1.js
  collectors/alibaba/collector.js
  exports.js
  helpers/alibaba/regions.js
  plugins/alibaba/ack/networkPolicyEnabled.js
  plugins/alibaba/ack/networkPolicyEnabled.spec.js
  plugins/aws/s3/bucketEncryption.js
  plugins/aws/s3/bucketEncryption.spec.js
  plugins/aws/s3/bucketEncryptionInTransit.js
  plugins/aws/s3/bucketEncryptionInTransit.spec.js
Labels: readytogo

#862 SAAS-2422: Added Alibaba ACK Network Policy Enabled plugin and spec
  plugins/alibaba/ack/networkPolicyEnabled.js
Labels: readytogo

#824 SAAS-2256: Added GCP Dataflow Jobs Encryption plugin and test cases
  collectors/google/collector.js
  exports.js
  helpers/google/index.js
  helpers/google/regions.js
  plugins/google/dataflow/dataflowJobsEncryption.js
  plugins/google/dataflow/dataflowJobsEncryption.spec.js
Labels: readytogo

#822 SAAS-2244: Added GCP Dataflow Hanged Jobs plugin and test cases
  exports.js
  plugins/google/dataflow/dataflowHangedJobs.js
  plugins/google/dataflow/dataflowHangedJobs.spec.js
Labels: readytogo

#830 Modification: Updated AWS plugins to skip checking ports for unused security groups
  helpers/aws/functions.js
  plugins/aws/ec2/openAllPortsProtocols.js
  plugins/aws/ec2/openAllPortsProtocols.spec.js
  plugins/aws/ec2/openCIFS.js
  plugins/aws/ec2/openCIFS.spec.js
  plugins/aws/ec2/openCustomPorts.js
  plugins/aws/ec2/openCustomPorts.spec.js
  plugins/aws/ec2/openDNS.js
  plugins/aws/ec2/openDNS.spec.js
  plugins/aws/ec2/openDocker.js
  plugins/aws/ec2/openDocker.spec.js
  plugins/aws/ec2/openElasticsearch.js
  plugins/aws/ec2/openElasticsearch.spec.js
  plugins/aws/ec2/openFTP.js
  plugins/aws/ec2/openFTP.spec.js
  plugins/aws/ec2/openHadoopNameNode.js
  plugins/aws/ec2/openHadoopNameNode.spec.js
  plugins/aws/ec2/openHadoopNameNodeWebUI.js
  plugins/aws/ec2/openHadoopNameNodeWebUI.spec.js
  plugins/aws/ec2/openKibana.js
  plugins/aws/ec2/openKibana.spec.js
  plugins/aws/ec2/openMySQL.js
  plugins/aws/ec2/openMySQL.spec.js
  plugins/aws/ec2/openNetBIOS.js
  plugins/aws/ec2/openNetBIOS.spec.js
  plugins/aws/ec2/openOracle.js
  plugins/aws/ec2/openOracle.spec.js
  plugins/aws/ec2/openOracleAutoDataWarehouse.js
  plugins/aws/ec2/openOracleAutoDataWarehouse.spec.js
  plugins/aws/ec2/openPostgreSQL.js
  plugins/aws/ec2/openPostgreSQL.spec.js
  plugins/aws/ec2/openRDP.js
  plugins/aws/ec2/openRDP.spec.js
  plugins/aws/ec2/openRPC.js
  plugins/aws/ec2/openRPC.spec.js
  plugins/aws/ec2/openSMBoTCP.js
  plugins/aws/ec2/openSMBoTCP.spec.js
  plugins/aws/ec2/openSMTP.js
  plugins/aws/ec2/openSMTP.spec.js
  plugins/aws/ec2/openSQLServer.js
  plugins/aws/ec2/openSQLServer.spec.js
  plugins/aws/ec2/openSSH.js
  plugins/aws/ec2/openSSH.spec.js
  plugins/aws/ec2/openSalt.js
  plugins/aws/ec2/openSalt.spec.js
  plugins/aws/ec2/openTelnet.js
  plugins/aws/ec2/openTelnet.spec.js
  plugins/aws/ec2/openVNCClient.js
  plugins/aws/ec2/openVNCClient.spec.js
  plugins/aws/ec2/openVNCServer.js
  plugins/aws/ec2/openVNCServer.spec.js
Labels: enhancement, reviewed

#876 SAAS-2452: Modified SNS Topic Policies to add setting for policy conditions
  helpers/aws/functions.js
  plugins/aws/es/esCrossAccountAccess.js
  plugins/aws/sns/topicPolicies.js
Labels: enhancement, hotfix

#869 SAAS-2411: Bug fix for AWS kmsKeyRotation
  plugins/aws/kms/kmsKeyRotation.js
  plugins/aws/kms/kmsKeyRotation.spec.js
Labels: enhancement, reviewed, hotfix

#524 refactoring: Modified all S3 plugins to add region name instead of 'global' region
  plugins/aws/s3/bucketAllUsersAcl.js
  plugins/aws/s3/bucketAllUsersAcl.spec.js
  plugins/aws/s3/bucketAllUsersPolicy.js
  plugins/aws/s3/bucketAllUsersPolicy.spec.js
  plugins/aws/s3/bucketDnsCompliantName.js
  plugins/aws/s3/bucketDnsCompliantName.spec.js
  plugins/aws/s3/bucketEncryption.js
  plugins/aws/s3/bucketEncryption.spec.js
  plugins/aws/s3/bucketEncryptionInTransit.js
  plugins/aws/s3/bucketEncryptionInTransit.spec.js
  plugins/aws/s3/bucketEnforceEncryption.js
  plugins/aws/s3/bucketEnforceEncryption.spec.js
  plugins/aws/s3/bucketLogging.js
  plugins/aws/s3/bucketLogging.spec.js
  plugins/aws/s3/bucketPolicyCloudFrontOai.js
  plugins/aws/s3/bucketPolicyCloudFrontOai.spec.js
  plugins/aws/s3/bucketPublicAccessBlock.js
  plugins/aws/s3/bucketPublicAccessBlock.spec.js
  plugins/aws/s3/bucketSecureTransportEnabled.js
  plugins/aws/s3/bucketSecureTransportEnabled.spec.js
  plugins/aws/s3/bucketTransferAcceleration.js
  plugins/aws/s3/bucketTransferAcceleration.spec.js
  plugins/aws/s3/bucketVersioning.js
  plugins/aws/s3/bucketVersioning.spec.js
  plugins/aws/s3/bucketWebsiteEnabled.js
  plugins/aws/s3/bucketWebsiteEnabled.spec.js
  plugins/aws/s3/s3Encryption.js
  plugins/aws/s3/s3Encryption.spec.js
Labels: enhancement
