Repository aquasecurity/cloudsploit, pull requests merged in 2021-11, with the labels that each got.

#947 SLK-41150: Added missing regions for ServiceQuotas service and refactored Instance vCPU On-Demand Based Limits plugin accordingly
  collectors/aws/collector.js
  helpers/aws/regions.js
  plugins/aws/ec2/instanceVcpusLimit.spec.js
Labels: enhancement

#932 SAAS-2877: Added new argument to run asl plugin, false by default
  engine.js
  index.js
Labels: enhancement

#916 SAAS-2763: Fixed some checks and added spec for ACM certificate expiry
  plugins/aws/acm/acmCertificateExpiry.js
  plugins/aws/acm/acmCertificateExpiry.spec.js
Labels: enhancement, readytogo

#880 SAAS-2577: Changed async.each to async.eachLimit
  collectors/aws/apigateway/getClientCertificate.js
  collectors/aws/eks/describeNodegroups.js
Labels: enhancement, readytogo

#927 SAAS-2843: GCP show separate results for multiple resources
  plugins/google/storage/bucketAllUsersPolicy.js
  plugins/google/storage/bucketAllUsersPolicy.spec.js
Labels: enhancement, reviewed

#875 SAAS-2509: Added missing region in AWS
  helpers/aws/regions.js
  plugins/aws/ec2/instanceMaxCount.js
Labels: enhancement

#913 SAAS-2841: Added new regions to GCP
  helpers/google/regions.js
  plugins/google/compute/instanceMaxCount.js
Labels: enhancement, reviewed

#950 SAAS-2222: Update EKS Supported Versions
  plugins/aws/eks/eksKubernetesVersion.js
Labels: enhancement, reviewed

#921 SAAS-2842: GCP Modify Disk Plugins to use aggregated list
  plugins/google/compute/csekEncryptionEnabled.js
  plugins/google/compute/csekEncryptionEnabled.spec.js
  plugins/google/compute/diskAutomaticBackupEnabled.js
  plugins/google/compute/diskAutomaticBackupEnabled.spec.js
  plugins/google/compute/diskInUse.js
  plugins/google/compute/diskInUse.spec.js
Labels: enhancement, reviewed

#939 SAAS-2857: GCP Audit Logging Enabled
  plugins/google/logging/auditLoggingEnabled.js
  plugins/google/logging/auditLoggingEnabled.spec.js
Labels: enhancement, reviewed

#952 SAAS-2997: Fix duplicate results issue in CloudTrail plugins
  helpers/aws/functions.js
  plugins/aws/cloudtrail/cloudtrailBucketAccessLogging.js
  plugins/aws/cloudtrail/cloudtrailBucketDelete.js
  plugins/aws/cloudtrail/cloudtrailBucketPrivate.js
  plugins/aws/cloudtrail/cloudtrailObjectLock.js
Labels: enhancement, reviewed

#961 SAAS-2109: Fixed to display region instead of zone
  plugins/google/compute/csekEncryptionEnabled.js
  plugins/google/compute/diskAutomaticBackupEnabled.js
  plugins/google/compute/diskInUse.js
  plugins/google/compute/diskMultiAz.js
Labels: enhancement, hotfix

#975 SAAS-3073: Added AWS Glue DataBrew Job Output Encrypted plugin and spec
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/gluedatabrew/databrewJobOutputEncrypted.js
  plugins/aws/gluedatabrew/databrewJobOutputEncrypted.spec.js
Labels: reviewed

#964 SAAS-3025: Added Elastic Transcoder Job Output Encrypted plugin and spec
  collectors/aws/collector.js
  exports.js
  plugins/aws/elastictranscoder/jobOutputsEncrypted.js
  plugins/aws/elastictranscoder/jobOutputsEncrypted.spec.js
Labels: readytogo

#958 SAAS-3015: Added AWS AppFlow Flow Encrypted plugin and spec
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/appflow/flowEncrypted.js
  plugins/aws/appflow/flowEncrypted.spec.js
Labels: readytogo

#933 SAAS-2300: Added S3 Versioned Buckets Lifycycle Configuration plugin and spec
  exports.js
  plugins/aws/s3/versionedBucketsLC.js
  plugins/aws/s3/versionedBucketsLC.spec.js
Labels: reviewed

#994 SAAS-3116: Added HealthLake Data Store Encryption Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/healthlake/dataStoreEncrypted.js
  plugins/aws/healthlake/dataStoreEncrypted.spec.js
Labels: reviewed

#993 SAAS-3109: Added Pipeline Artifacts Encryption Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/codepipeline/pipelineArtifactsEncrypted.js
  plugins/aws/codepipeline/pipelineArtifactsEncrypted.spec.js
Labels: reviewed

#990 SAAS-3107: Added FinSpace Environment Encryption Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/finspace/finspaceEnvironmentEncrypted.js
  plugins/aws/finspace/finspaceEnvironmentEncrypted.spec.js
Labels: reviewed

#987 SAAS-3098: Added App Runner Service Encryption Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/apprunner/serviceEncrypted.js
  plugins/aws/apprunner/serviceEncrypted.spec.js
Labels: reviewed

#986 SAAS-3097: Added QLDB Ledger Encryption Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/qldb/ledgerEncrypted.js
  plugins/aws/qldb/ledgerEncrypted.spec.js
Labels: reviewed

#985 SAAS-3093: Added Connect Customer Profiles Domain Encryption Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/connect/customerProfilesDomainEncrypted.js
  plugins/aws/connect/customerProfilesDomainEncrypted.spec.js
Labels: reviewed

#983 SAAS-3087: Added Proton Environment Template Encryption Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/proton/environmentTemplateEncrypted.js
  plugins/aws/proton/environmentTemplateEncrypted.spec.js
Labels: reviewed

#981 SAAS-3082: Added MWAA Environment Data Encryption Plugin
  exports.js
  plugins/aws/mwaa/environmentDataEncrypted.js
  plugins/aws/mwaa/environmentDataEncrypted.spec.js
Labels: reviewed

#982 SAAS-3083: Added Kendra Index Encryption Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/kendra/kendraIndexEncrypted.js
  plugins/aws/kendra/kendraIndexEncrypted.spec.js
Labels: reviewed

#979 SAAS-3081: Added MSK Cluster at rest Encryption Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/msk/mskClusterEncryptionAtRest.js
  plugins/aws/msk/mskClusterEncryptionAtRest.spec.js
Labels: readytogo, reviewed

#974 SAAS-3072: Added MemoryDB Cluster Encrypted Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/memorydb/memorydbClusterEncrypted.js
  plugins/aws/memorydb/memorydbClusterEncrypted.spec.js
Labels: readytogo, reviewed

#965 SAAS-3026: Added ElastiCache Redis In-Transit Clusters Encrypted Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/elasticache/redisClusterEncryptionInTransit.js
  plugins/aws/elasticache/redisClusterEncryptionInTransit.spec.js
Labels: readytogo, reviewed

#963 SAAS-3018: Added DocumentDb Clusters Encrypted Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/documentDB/docdbClusterEncrypted.js
  plugins/aws/documentDB/docdbClusterEncrypted.spec.js
Labels: readytogo, reviewed

#977 SAAS-3079: Added Neptune Database Cluster Encrypted Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/neptune/neptuneDBInstanceEncrypted.js
  plugins/aws/neptune/neptuneDBInstanceEncrypted.spec.js
Labels: readytogo, reviewed

#970 SAAS-3064: Added ECR Repository Encrypted Plugin
  exports.js
  plugins/aws/ecr/ecrRepositoryEncrypted.js
  plugins/aws/ecr/ecrRepositoryEncrypted.spec.js
Labels: readytogo, reviewed

#968 SAAS-3063: Added Timestream Databases Encrypted Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/timestreamwrite/timestreamDatabaseEncrypted.js
  plugins/aws/timestreamwrite/timestreamDatabaseEncrypted.spec.js
Labels: readytogo, reviewed

#967 SAAS-3029: Added Elasticache Redis At Rest Clusters Encrypted Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/elasticache/redisClusterEncryptionAtRest.js
  plugins/aws/elasticache/redisClusterEncryptionAtRest.spec.js
Labels: question, reviewed

#973 SAAS-3071: Added MQ Broker Encrypted Plugin
  exports.js
  plugins/aws/mq/mqBrokerEncrypted.js
  plugins/aws/mq/mqBrokerEncrypted.spec.js
Labels: readytogo, reviewed

#956 SAAS-3008: Added Backup Vault Encrypted plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/backup/backupVaultEncrypted.js
  plugins/aws/backup/backupVaultEncrypted.spec.js
Labels: reviewed

#999 SAAS-3132: Added Instance Attachments Encrypted Plugin
  collectors/aws/collector.js
  collectors/aws/connect/instanceAttachmentStorageConfigs.js
  exports.js
  plugins/aws/connect/instanceAttachmentsEncrypted.js
  plugins/aws/connect/instanceAttachmentsEncrypted.spec.js
Labels: reviewed

#998 SAAS-3131: Added Instance Exported Reports Encrypted Plugin
  collectors/aws/collector.js
  collectors/aws/connect/listInstanceExportedReportStorageConfigs.js
  exports.js
  plugins/aws/connect/instanceReportsEncrypted.js
  plugins/aws/connect/instanceReportsEncrypted.spec.js
Labels: readytogo, reviewed

#997 SAAS-3130: Added Instance Media Streams Encrypted Plugin
  collectors/aws/collector.js
  collectors/aws/connect/listInstanceMediaStreamStorageConfigs.js
  exports.js
  helpers/aws/regions_gov.js
  plugins/aws/connect/instanceMediaStreamsEncrypted.js
  plugins/aws/connect/instanceMediaStreamsEncrypted.spec.js
Labels: reviewed
