Repository aquasecurity/cloudsploit, pull requests merged in 2021-05, with the labels that each got.

#674 HOTIX: Fixed undefined resource issue
  plugins/aws/es/esExposedDomain.js
Labels: reviewed

#684 feature/AKD-191: Added Alibaba RAM Users MFA Enabled plugin and test cases
  collectors/alibaba/collector.js
  exports.js
  helpers/alibaba/functions.js
  helpers/alibaba/regions.js
  index.js
  plugins/alibaba/ram/usersMfaEnabled.js
  plugins/alibaba/ram/usersMfaEnabled.spec.js
Labels: reviewed

#685 feature/AKD-195: Added Alibaba RAM Password Requires Uppercase plugin and test cases
  collectors/alibaba/collector.js
  exports.js
  plugins/alibaba/ram/passwordRequiresUppercase.js
  plugins/alibaba/ram/passwordRequiresUppercase.spec.js
Labels: reviewed

#686 feature/AKD-215: Added Alibaba RDS SSL Encryption Enabled plugin and test cases
  collectors/alibaba/collector.js
  exports.js
  plugins/alibaba/rds/rdsSslEncryptionEnabled.js
  plugins/alibaba/rds/rdsSslEncryptionEnabled.spec.js
Labels: reviewed

#729 Merging SAAS 05-25
  collectors/alibaba/collector.js
  collectors/alibaba/oss/listBuckets.js
  docs/gcp.md
  index.js
  plugins/aws/es/esExposedDomain.js
Labels: readytogo

#702 Alibaba ram user plugin added for inactive user disabled
  collectors/alibaba/collector.js
  exports.js
  plugins/alibaba/ram/inactiveUserDisabled.js
  plugins/alibaba/ram/inactiveUserDisabled.spec.js
Labels: readytogo

#703 Feature/202 - Alibaba ram user password lowercase policy plugin with test cases
  exports.js
  plugins/alibaba/ram/passwordRequiresLowercase.js
  plugins/alibaba/ram/passwordRequiresLowercase.spec.js
Labels: readytogo, reviewed

#709 Feature/203 - Alibaba password symbols policy plugin added with test cases
  exports.js
  plugins/alibaba/ram/passwordRequiresSymbols.js
  plugins/alibaba/ram/passwordRequiresSymbols.spec.js
Labels: readytogo, reviewed

#710 Feature/204 - Alibaba ram user password numbers policy plugin with test cases
  exports.js
  plugins/alibaba/ram/passwordRequiresNumbers.js
  plugins/alibaba/ram/passwordRequiresNumbers.spec.js
Labels: reviewed

#711 Feature/205 - Alibaba ram user password min length policy plugin with test cases
  exports.js
  plugins/alibaba/ram/passwordMinLength.js
  plugins/alibaba/ram/passwordMinLength.spec.js
Labels: reviewed

#723 Alibaba plugin added for ram user password reuse prevention policy with spec file
  exports.js
  plugins/alibaba/ram/passwordNoReuse.js
  plugins/alibaba/ram/passwordNoReuse.spec.js
Labels: readytogo, reviewed

#724 Alibaba ram user plugin added for password expiry with spec file
  exports.js
  plugins/alibaba/ram/passwordExpiry.js
  plugins/alibaba/ram/passwordExpiry.spec.js
Labels: readytogo, reviewed

#725 Alibaba ram user plugin added for block logon with spec file
  exports.js
  plugins/alibaba/ram/passwordBlockLogon.js
  plugins/alibaba/ram/passwordBlockLogon.spec.js
Labels: readytogo, reviewed

#728 feature/AKD-210: Added Alibaba RAM Policy Attachments plugin and test cases
  collectors/alibaba/collector.js
  exports.js
  plugins/alibaba/ram/ramPolicyAttachments.js
  plugins/alibaba/ram/ramPolicyAttachments.spec.js
Labels: readytogo

#731 feature/open-ports: Added Alibaba ECS Open Ports plugins and test cases
  exports.js
  plugins/alibaba/ecs/openCIFS.js
  plugins/alibaba/ecs/openCIFS.spec.js
  plugins/alibaba/ecs/openDNS.js
  plugins/alibaba/ecs/openDNS.spec.js
  plugins/alibaba/ecs/openDocker.js
  plugins/alibaba/ecs/openDocker.spec.js
  plugins/alibaba/ecs/openElasticsearch.js
  plugins/alibaba/ecs/openElasticsearch.spec.js
  plugins/alibaba/ecs/openFTP.js
  plugins/alibaba/ecs/openFTP.spec.js
  plugins/alibaba/ecs/openHadoopNameNode.js
  plugins/alibaba/ecs/openHadoopNameNode.spec.js
  plugins/alibaba/ecs/openHadoopNameNodeWebUI.js
  plugins/alibaba/ecs/openHadoopNameNodeWebUI.spec.js
  plugins/alibaba/ecs/openKibana.js
  plugins/alibaba/ecs/openKibana.spec.js
  plugins/alibaba/ecs/openMySQL.js
  plugins/alibaba/ecs/openMySQL.spec.js
  plugins/alibaba/ecs/openNetBIOS.js
  plugins/alibaba/ecs/openNetBIOS.spec.js
  plugins/alibaba/ecs/openOracle.js
  plugins/alibaba/ecs/openOracle.spec.js
  plugins/alibaba/ecs/openPostgreSQL.js
  plugins/alibaba/ecs/openPostgreSQL.spec.js
  plugins/alibaba/ecs/openRDP.js
  plugins/alibaba/ecs/openRDP.spec.js
Labels: readytogo

#730 feature/AKD-211: Added Alibaba ActionTrail Global Export Logs plugin and test cases
  collectors/alibaba/collector.js
  exports.js
  helpers/alibaba/regions.js
  plugins/alibaba/actiontrail/actiontrailGlobalExportLogs.js
  plugins/alibaba/actiontrail/actiontrailGlobalExportLogs.spec.js
Labels: readytogo

#722 Alibaba ram user access keys rotation plugin with spec file
  collectors/alibaba/collector.js
  exports.js
  plugins/alibaba/ram/accessKeysRotation.js
  plugins/alibaba/ram/accessKeysRotation.spec.js
Labels: readytogo, reviewed
