Repository aquasecurity/cloudsploit, pull requests merged in 2021-03, with the labels that each got.

#562 HOTFIX: Fixed failing test in IAM Access Keys Rotated plugin
  plugins/aws/iam/accessKeysRotated.spec.js
Labels: duplicate, reviewed

#566 HOTFIX: Fixed to add check for log group retention never expire
  plugins/aws/cloudwatchlogs/logRetentionPeriod.js
  plugins/aws/cloudwatchlogs/logRetentionPeriod.spec.js
Labels: reviewed

#559 HOTFIX + spec: Added Google VPC Network Open Ports test cases
  helpers/google/functions.js
  plugins/google/vpcnetwork/openAllPorts.spec.js
  plugins/google/vpcnetwork/openCIFS.spec.js
  plugins/google/vpcnetwork/openDNS.spec.js
  plugins/google/vpcnetwork/openDocker.spec.js
  plugins/google/vpcnetwork/openFTP.spec.js
  plugins/google/vpcnetwork/openHadoopNameNode.spec.js
  plugins/google/vpcnetwork/openHadoopNameNodeWebUI.spec.js
  plugins/google/vpcnetwork/openKibana.spec.js
  plugins/google/vpcnetwork/openMySQL.spec.js
  plugins/google/vpcnetwork/openNetBIOS.spec.js
  plugins/google/vpcnetwork/openOracle.spec.js
  plugins/google/vpcnetwork/openOracleAutoDataWarehouse.spec.js
  plugins/google/vpcnetwork/openPostgreSQL.spec.js
  plugins/google/vpcnetwork/openRDP.spec.js
  plugins/google/vpcnetwork/openRPC.spec.js
  plugins/google/vpcnetwork/openSMBoTCP.spec.js
  plugins/google/vpcnetwork/openSMTP.spec.js
  plugins/google/vpcnetwork/openSQLServer.spec.js
  plugins/google/vpcnetwork/openSSH.spec.js
  plugins/google/vpcnetwork/openSalt.spec.js
  plugins/google/vpcnetwork/openTelnet.spec.js
  plugins/google/vpcnetwork/openVNCClient.js
  plugins/google/vpcnetwork/openVNCClient.spec.js
  plugins/google/vpcnetwork/openVNCServer.spec.js
Labels: readytogo

#428 remediation: AWS xrayEncryptionEnabled plugin remediated
  engine.js
  plugins/aws/xray/xrayEncryptionEnabled.js
  plugins/aws/xray/xrayEncryptionEnabled.spec.js
Labels: readytogo, reviewed

#520 feature/akfr-30: Added AWS MWAA Environment Admin Privileges plugin and test cases
  collectors/aws/collector.js
  collectors/aws/mwaa/getEnvironment.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/mwaa/environmentAdminPrivileges.js
  plugins/aws/mwaa/environmentAdminPrivileges.spec.js
Labels: reviewed

#454 feature-request: Added 'Secrets Manager Encrypted' plugin and test cases
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/secretsmanager/secretsManagerEncrypted.js
  plugins/aws/secretsmanager/secretsManagerEncrypted.spec.js
Labels: readytogo, reviewed

#521 feature/akfr-31: Added AWS MWAA 'Web Server Public Access' plugin and test cases
  exports.js
  plugins/aws/mwaa/webServerPublicAccess.js
  plugins/aws/mwaa/webServerPublicAccess.spec.js
Labels: reviewed

#522 feature/akrf-24: Added AWS 'DevOps Guru Notification Enabled' plugin and test cases
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  package.json
  plugins/aws/devopsguru/devOpsGuruNotificationEnabled.js
  plugins/aws/devopsguru/devOpsGuruNotificationEnabled.spec.js
Labels: readytogo, reviewed

#541 feature/akd-49: Added AWS 'API Gateway CloudWatch Logs' plugin and test cases
  exports.js
  plugins/aws/apigateway/apigatewayCloudwatchLogs.js
  plugins/aws/apigateway/apigatewayCloudwatchLogs.spec.js
Labels: readytogo

#536 feature/akd-43: Added AWS 'ELBv2 Deregostration Delay' plugin and test cases
  collectors/aws/collector.js
  exports.js
  plugins/aws/elbv2/elbv2DeregistrationDelay.js
  plugins/aws/elbv2/elbv2DeregistrationDelay.spec.js
  plugins/aws/glue/glueCloudwatchLogsEncrypted.js
Labels: readytogo

#547 feature/AKG-7: Added Google 'Open Redis' plugin, test cases
  exports.js
  plugins/google/vpcnetwork/openRedis.js
  plugins/google/vpcnetwork/openRedis.spec.js
Labels: readytogo

#548 feature/akg-9: Added Google 'Open MSSQL' plugin, test cases
  exports.js
  plugins/google/vpcnetwork/openMsSQL.js
  plugins/google/vpcnetwork/openMsSQL.spec.js
Labels: readytogo

#556 feature/AKD-93: Added AWS 'RDS Deletion Protection Enabled' plugin and test cases
  exports.js
  plugins/aws/rds/rdsDeletionProtectionEnabled.js
  plugins/aws/rds/rdsDeletionProtectionEnabled.spec.js
Labels: readytogo, reviewed

#558 feature/AKD-53: Added AWS 'Secrets Manager Secret Rotation Enabled' plugin and test c…
  collectors/aws/collector.js
  exports.js
  plugins/aws/secretsmanager/secretRotationEnabled.js
  plugins/aws/secretsmanager/secretRotationEnabled.spec.js
Labels: readytogo

#567 feature/AKAD-3: Added Azure PostgreSQL server 'Geo-redundant Backup Enabled' plugin a…
  exports.js
  plugins/azure/postgresqlserver/geoRedundantBackupEnabled.js
  plugins/azure/postgresqlserver/geoRedundantBackupEnabled.spec.js
Labels: readytogo

#561 feature/AKD-92: Added AWS 'RDS IAM DB Authentication Enabled' plugin and test cases
  exports.js
  plugins/aws/rds/iamDbAuthenticationEnabled.js
  plugins/aws/rds/iamDbAuthenticationEnabled.spec.js
Labels: readytogo

#575 feature/AKD-113: Added Azure 'SQL Server TLS Version' plugin and test cases
  exports.js
  plugins/azure/sqlserver/sqlServerTlsVersion.js
  plugins/azure/sqlserver/sqlServerTlsVersion.spec.js
Labels: readytogo, reviewed

#578 feature/AKD-115: Added Azure Cosmos DB 'Automatic Failover Enabled' plugin and test cases
  collectors/azure/collector.js
  exports.js
  helpers/azure/locations.js
  plugins/azure/cosmosdb/automaticFailoverEnabled.js
  plugins/azure/cosmosdb/automaticFailoverEnabled.spec.js
Labels: readytogo

#583 feature/AKD-116: Added Azure Cosmos DB 'Cosmos Public Access Disabled' plugin and test…
  exports.js
  plugins/azure/cosmosdb/cosmosPublicAccessDisabled.js
  plugins/azure/cosmosdb/cosmosPublicAccessDisabled.spec.js
Labels: readytogo

#592 feature/AKD-121: Added AWS Glue Data Catalog Encryption Enabled plugin and test cases
  exports.js
  plugins/aws/glue/dataCatalogEncryptionEnabled.js
  plugins/aws/glue/dataCatalogEncryptionEnabled.spec.js
Labels: readytogo

#543 feature/AKG-6: Added Google 'Kubernetes Alpha Disabled' plugin and test cases
  exports.js
  plugins/google/kubernetes/kubernetesAlphaDisabled.js
  plugins/google/kubernetes/kubernetesAlphaDisabled.spec.js
Labels: readytogo

#612 Spec/appservice
  plugins/azure/appservice/clientCertEnabled.spec.js
  plugins/azure/appservice/http20Enabled.spec.js
  plugins/azure/appservice/httpsOnlyEnabled.spec.js
  plugins/azure/appservice/identityEnabled.spec.js
  plugins/azure/appservice/javaVersion.spec.js
  plugins/azure/appservice/netFrameworkVersion.spec.js
  plugins/azure/appservice/phpVersion.spec.js
  plugins/azure/appservice/pythonVersion.spec.js
  plugins/azure/appservice/tlsVersionCheck.spec.js
Labels: reviewed

#611 Spec/securitycenter
  plugins/azure/securitycenter/adminSecurityAlertsEnabled.spec.js
  plugins/azure/securitycenter/autoProvisioningEnabled.spec.js
  plugins/azure/securitycenter/securityContactsEnabled.spec.js
Labels: reviewed

#610 Spec/storage accounts
  plugins/azure/storageaccounts/blobServiceEncryption.js
  plugins/azure/storageaccounts/blobServiceEncryption.spec.js
  plugins/azure/storageaccounts/fileServiceEncryption.spec.js
  plugins/azure/storageaccounts/storageAccountsEncryption.spec.js
  plugins/azure/storageaccounts/trustedMsAccessEnabled.spec.js
Labels: reviewed

#609 Spec/blobservice
  plugins/azure/blobservice/blobContainersPrivateAccess.spec.js
  plugins/azure/blobservice/blobServiceImmutable.spec.js
Labels: reviewed

#591 spec: Added test case file for Kubernetes RBAC Enabled plugin
  plugins/azure/kubernetesservice/rbacEnabled.spec.js
Labels: reviewed

#588 feature/AKD-118: Added Azure 'DDoS Standard Protection Enabled' plugin and test cases
  exports.js
  plugins/azure/virtualnetworks/ddosStandardProtectionEnabled.js
  plugins/azure/virtualnetworks/ddosStandardProtectionEnabled.spec.js
Labels: reviewed

#584 feature/AKD-96: Added Azure 'Storage Auto Growth Enabled' plugin and test cases
  exports.js
  plugins/azure/postgresqlserver/storageAutoGrowthEnabled.js
  plugins/azure/postgresqlserver/storageAutoGrowthEnabled.spec.js
Labels: readytogo, reviewed

#620 HOTFIX: Fixed issue for default TLS version setting
  plugins/azure/sqlserver/sqlServerTlsVersion.js
  plugins/azure/sqlserver/sqlServerTlsVersion.spec.js
Labels: readytogo

#621 Modification: Modified to generate PASS if no secrets
  plugins/aws/secretsmanager/secretRotationEnabled.js
  plugins/aws/secretsmanager/secretRotationEnabled.spec.js
Labels: readytogo

#511 HOTFIX: Fixed null results issue in Monitoring Metrics
  plugins/aws/cloudwatchlogs/monitoringMetrics.js
Labels: readytogo, reviewed

#518 feature-request: Modified CloudTrail S3 Bucket and Delivery Failed plugin to add settings for trail names to check
  plugins/aws/cloudtrail/cloudtrailDeliveryFailing.js
  plugins/aws/cloudtrail/cloudtrailDeliveryFailing.spec.js
  plugins/aws/cloudtrail/cloudtrailS3Bucket.js
  plugins/aws/cloudtrail/cloudtrailS3Bucket.spec.js
Labels: readytogo, reviewed

#538 modification: Modified RDS Transport Encryption to check postgres engine as well
  plugins/aws/rds/rdsTransportEncryption.js
Labels: readytogo

#540 modification: Modified to check dangling S3 bucket endpoints
  plugins/aws/route53/danglingDnsRecords.js
  plugins/aws/route53/danglingDnsRecords.spec.js
Labels: readytogo, reviewed

#553 modification-plugin-840: Modified AWS 'Open IP Address' to pass if not behind open security gr…
  plugins/aws/ec2/publicIpAddress.js
  plugins/aws/ec2/publicIpAddress.spec.js
Labels: readytogo

#565 spec: Added test case file for AWS CloudFront plugins
  plugins/aws/cloudfront/cloudfrontHttpsOnly.spec.js
  plugins/aws/cloudfront/cloudfrontLoggingEnabled.js
  plugins/aws/cloudfront/cloudfrontLoggingEnabled.spec.js
  plugins/aws/cloudfront/cloudfrontWafEnabled.js
  plugins/aws/cloudfront/cloudfrontWafEnabled.spec.js
  plugins/aws/cloudfront/insecureProtocols.spec.js
  plugins/aws/cloudfront/publicS3Origin.spec.js
  plugins/aws/cloudfront/secureOrigin.spec.js
Labels: readytogo

#577 feature/AKD-114: Added Azure Cosmos DB 'Advanced Threat Protection' plugin and test cases
  collectors/azure/collector.js
  exports.js
  plugins/azure/cosmosdb/advancedThreatProtection.js
  plugins/azure/cosmosdb/advancedThreatProtection.spec.js
Labels: readytogo

#514 Check Kubernetes Cluster scopes independently
  plugins/google/kubernetes/clusterLeastPrivilege.js
Labels: readytogo
