Repository aquasecurity/cloudsploit, pull requests merged in 2021-12, with the labels that each got.

#1012 SAAS-3251: Fixed False Negative and syntax issues in Oracle plugins
  plugins/oracle/compute/bootVolumeBackupEnabled.js
  plugins/oracle/compute/bootVolumeBackupEnabled.spec.js
  plugins/oracle/networking/statelessSecurityRules.js
Labels: hotfix

#1039 SAAS-3391: Added Lookout Metrics Anomaly Detectors Encrypted Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/lookout/anomalyDetectorEncrypted.js
  plugins/aws/lookout/anomalyDetectorEncrypted.spec.js
Labels: readytogo

#1046 SAAS-3405: Added Lex Audio Logs Encrypted Plugin
  collectors/aws/collector.js
  collectors/aws/lexmodelsv2/describeBotAlias.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/lex/lexAudioLogsEncrypted.js
  plugins/aws/lex/lexAudioLogsEncrypted.spec.js
Labels: reviewed

#1043 SAAS-3395: Added Lookout Vision Model Data Encrypted Plugin
  collectors/aws/collector.js
  collectors/aws/lookoutvision/describeModel.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/lookout/modelDataEncrypted.js
  plugins/aws/lookout/modelDataEncrypted.spec.js
Labels: reviewed

#1036 SAAS-3382: Added Location Geoference Collections Data Encrypted Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/location/geoCollectionDataEncrypted.js
  plugins/aws/location/geoCollectionDataEncrypted.spec.js
Labels: reviewed

#1034 SAAS-3371: Added IoT SiteWise Data Encrypted Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/iotsitewise/iotsitewiseDataEncrypted.js
  plugins/aws/iotsitewise/iotsitewiseDataEncrypted.spec.js
Labels: readytogo, reviewed

#1040 SAAS-3380: Added GuardDuty Export Findings Encrypted Plugin
  collectors/aws/collector.js
  collectors/aws/guardduty/describePublishingDestination.js
  collectors/aws/guardduty/listPublishingDestinations.js
  exports.js
  plugins/aws/guardduty/exportedFindingsEncrypted.js
  plugins/aws/guardduty/exportedFindingsEncrypted.spec.js
Labels: reviewed

#1035 SAAS-3381: Added Location Tracker Data Encrypted Plugin
  collectors/aws/collector.js
  exports.js
  plugins/aws/location/trackerDataEncrypted.js
  plugins/aws/location/trackerDataEncrypted.spec.js
Labels: readytogo, reviewed

#1033 SAAS-3369: Added Video Stream Data Encrypted Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/kinesisvideo/videostreamDataEncrypted.js
  plugins/aws/kinesisvideo/videostreamDataEncrypted.spec.js
Labels: reviewed

#1028 SAAS-3346: Added Idle AWS ElastCache Nodes Plugin
  collectors/aws/cloudwatch/getEcMetricStatistics.js
  collectors/aws/collector.js
  exports.js
  plugins/aws/elasticache/idleElastiCacheNode.js
  plugins/aws/elasticache/idleElastiCacheNode.spec.js
Labels: reviewed

#1037 SAAS-3383: Added Lookout Equipment Dataset Encrypted Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/lookout/equipmentdatasetEncrypted.js
  plugins/aws/lookout/equipmentdatasetEncrypted.spec.js
Labels: readytogo, reviewed

#1027 SAAS-3338: Added ElastiCache Reserved Cache Node Lease Expiration Plugin
  collectors/aws/collector.js
  exports.js
  plugins/aws/elasticache/reservedNodeLeaseExpiration.js
  plugins/aws/elasticache/reservedNodeLeaseExpiration.spec.js
Labels: reviewed

#1026 SAAS-3289: Added Reserved Node Payment Failed Plugin
  exports.js
  plugins/aws/elasticache/reservedNodePaymentFailed.js
  plugins/aws/elasticache/reservedNodePaymentFailed.spec.js
Labels: reviewed

#1024 SAAS-3287: Added Unused ElastiCache Reserved Cache Nodes Plugin
  collectors/aws/collector.js
  exports.js
  plugins/aws/elasticache/unusedElastiCacheReservedNode.js
  plugins/aws/elasticache/unusedElastiCacheReservedNode.spec.js
Labels: reviewed

#1021 SAAS-3276: Added EKS Latest Platform Version Plugin
  exports.js
  plugins/aws/eks/eksLatestPlatformVersion.js
  plugins/aws/eks/eksLatestPlatformVersion.spec.js
Labels: reviewed

#1025 SAAS-3288: Added Reserved Cache Node Payment Pending Plugin
  exports.js
  plugins/aws/elasticache/reservedNodePaymentPending.js
  plugins/aws/elasticache/reservedNodePaymentPending.spec.js
Labels: reviewed

#1023 SAAS-3282: Added ElastiCache Redis Multi-AZ Plugin
  exports.js
  plugins/aws/elasticache/elasticacheRedisMultiAZ.js
  plugins/aws/elasticache/elasticacheRedisMultiAZ.spec.js
Labels: reviewed

#1022 SAAS-3278: Added ElastiCache Nodes Count Plugin
  exports.js
  plugins/aws/elasticache/elasticacheNodesCount.js
  plugins/aws/elasticache/elasticacheNodesCount.spec.js
Labels: reviewed

#1020 SAAS-3139: Added ElastiCache Engine Version For Redis Plugin
  exports.js
  plugins/aws/elasticache/redisEngineVersions.js
  plugins/aws/elasticache/redisEngineVersions.spec.js
Labels: readytogo, reviewed

#1019 SAAS-3140: Added ElastiCache Instance Generation Plugin
  exports.js
  plugins/aws/elasticache/elasticacheInstanceGeneration.js
  plugins/aws/elasticache/elasticacheInstanceGeneration.spec.js
Labels: reviewed

#948 SAAS-2954: Added MQ Desired Broker Instance Type
  exports.js
  plugins/aws/mq/mqDesiredInstanceType.js
  plugins/aws/mq/mqDesiredInstanceType.spec.js
Labels: reviewed

#1014 SAAS-3136: Added EMR Instance Count Plugin
  collectors/aws/collector.js
  exports.js
  plugins/aws/emr/emrInstanceCount.js
  plugins/aws/emr/emrInstanceCount.spec.js
Labels: reviewed

#989 SAAS-3099: Added AWS WAF plugin and spec
  collectors/aws/collector.js
  collectors/aws/collector_multipart.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/waf/wafInUse.js
  plugins/aws/waf/wafInUse.spec.js
Labels: reviewed

#1002 Added WAFV2 plugin and spec
  exports.js
  plugins/aws/wafv2/wafv2InUse.js
  plugins/aws/wafv2/wafv2InUse.spec.js
Labels: reviewed

#1010 Added docdbClusterBackupRetention plugin and spec
  exports.js
  plugins/aws/documentDB/docdbClusterBackupRetention.js
  plugins/aws/documentDB/docdbClusterBackupRetention.spec.js
Labels: reviewed

#1015 Added environmentAccessLogs plugin and spec
  exports.js
  plugins/aws/elasticbeanstalk/environmentAccessLogs.js
  plugins/aws/elasticbeanstalk/environmentAccessLogs.spec.js
Labels: reviewed

#1018 Added enhancedHealthReporting plugin and spec
  exports.js
  plugins/aws/elasticbeanstalk/enhancedHealthReporting.js
  plugins/aws/elasticbeanstalk/enhancedHealthReporting.spec.js
Labels: reviewed

#1041 SAAS/3260: Added fsxFileSystemEncrypted plugin and spec
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/fsx/fsxFileSystemEncrypted.js
  plugins/aws/fsx/fsxFileSystemEncrypted.spec.js
Labels: reviewed

#1000 Added workspacesDesiredBundleType plugin and spec
  exports.js
  plugins/aws/workspaces/workspacesDesiredBundleType.js
  plugins/aws/workspaces/workspacesDesiredBundleType.spec.js
Labels: reviewed

#1017 Added environmentPersistentLogs plugin and spec
  exports.js
  plugins/aws/elasticbeanstalk/environmentPersistentLogs.js
  plugins/aws/elasticbeanstalk/environmentPersistentLogs.spec.js
Labels: reviewed

#1001 Added workspacesInstanceCount plugin and spec
  exports.js
  plugins/aws/workspaces/workspacesInstanceCount.js
  plugins/aws/workspaces/workspacesInstanceCount.spec.js
Labels: reviewed

#1031 SAAS/3256: Added voiceIdDomainEncrypted Plugin and spec
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/connect/voiceIdDomainEncrypted.js
  plugins/aws/connect/voiceIdDomainEncrypted.spec.js
Labels: reviewed

#1032 SAAS/3257: Added wisdomDomainEncrypted Plugin and spec
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/connect/wisdomDomainEncrypted.js
  plugins/aws/connect/wisdomDomainEncrypted.spec.js
Labels: reviewed

#1045 Added ssmManagedInstances plugin and spec
  exports.js
  plugins/aws/ssm/ssmManagedInstances.js
  plugins/aws/ssm/ssmManagedInstances.spec.js
Labels: reviewed

#1038 Added forecastDatasetEncrypted plugin and spec
  collectors/aws/collector.js
  exports.js
  plugins/aws/forecast/datasetExportEncrypted.js
  plugins/aws/forecast/datasetExportEncrypted.spec.js
Labels: reviewed
