Repository aquasecurity/cloudsploit, pull requests merged in 2021-04, with the labels that each got.

#544 remediation: ES Encrypted Domain remediated
  plugins/aws/es/esEncryptedDomain.js
Labels: readytogo

#545 remediation: ES Node To Node Encryption remediated
  plugins/aws/es/esNodeToNodeEncryption.js
Labels: readytogo

#623 Modification: Modified index and engine files to fix azure remediation invalid token issue
  config_example.js
  engine.js
  index.js
Labels: reviewed

#624 remediation: Azure Enforce MySQL SSL Connection remediated
  helpers/azure/auth.js
  plugins/azure/mysqlserver/enforceMySQLSSLConnection.js
Labels: readytogo

#629 remediation: Azure App Service Auth Enabled plugin remediated
  plugins/azure/appservice/authEnabled.js
Labels: readytogo, reviewed

#663 Added entry in exports for CodeStar Valid Repo Providers
  exports.js
Labels: readytogo

#617 feature/AKD-108: Added Azure 'SQL Server Private Endpoints Configured' plugin and test cases
  exports.js
  plugins/azure/sqlserver/serverPrivateEndpoints.js
  plugins/azure/sqlserver/serverPrivateEndpoints.spec.js
Labels: readytogo

#618 feature/AKD-117: Added Azure 'NSG Flow Logs Retention Period' plugin and test cases
  collectors/azure/collector.js
  exports.js
  plugins/azure/networkwatchers/nsgFlowLogsRetentionPeriod.js
  plugins/azure/networkwatchers/nsgFlowLogsRetentionPeriod.spec.js
Labels: readytogo

#633 Spec/storageaccounts
  plugins/azure/storageaccounts/logContainerPublicAccess.spec.js
  plugins/azure/storageaccounts/logStorageEncryption.spec.js
  plugins/azure/storageaccounts/networkAccessDefaultAction.spec.js
  plugins/azure/storageaccounts/storageAccountsHttps.spec.js
Labels: readytogo, reviewed

#634 feature/AKD-111: Added Azure 'SQL Server Automatic Tuning Enabled' plugin and test cases
  collectors/azure/collector.js
  exports.js
  plugins/azure/sqlserver/automaticTuningEnabled.js
  plugins/azure/sqlserver/automaticTuningEnabled.spec.js
Labels: reviewed

#635 feature/AKD-148: Added Azure 'No Unattached Disk Volumes' plugin and test cases
  exports.js
  plugins/azure/virtualmachines/noUnattachedDisks.js
  plugins/azure/virtualmachines/noUnattachedDisks.spec.js
Labels: readytogo, reviewed

#638 feature/136: Added Azure VM Automatic OS Upgrades Enabled plugin, test cases
  exports.js
  plugins/azure/virtualmachines/autoOsUpgradesEnabled.js
  plugins/azure/virtualmachines/autoOsUpgradesEnabled.spec.js
Labels: readytogo

#646 Spec files added for storage plugins
  plugins/google/storage/bucketLogging.spec.js
  plugins/google/storage/bucketVersioning.spec.js
Labels: readytogo, reviewed

#647 Spec files added for sql plugins
  plugins/google/sql/dbAutomatedBackups.spec.js
  plugins/google/sql/dbMultiAz.spec.js
  plugins/google/sql/dbPubliclyAccessible.spec.js
  plugins/google/sql/dbRestorable.spec.js
Labels: readytogo, reviewed

#649 feature/AKD-125: Added Azure 'Managed VM Machine Image' plugin and test cases
  exports.js
  plugins/azure/virtualmachines/approvedVmImage.js
  plugins/azure/virtualmachines/approvedVmImage.spec.js
Labels: readytogo, reviewed

#650 feature/AKD-128: Added Azure 'Password Authentication Disabled' plugin and test cases
  exports.js
  plugins/azure/virtualmachines/passwordAuthDisabled.js
  plugins/azure/virtualmachines/passwordAuthDisabled.spec.js
Labels: readytogo, reviewed

#652 Spec files added for VPC plugins
  plugins/google/vpcnetwork/defaultVpcInUse.js
  plugins/google/vpcnetwork/defaultVpcInUse.spec.js
  plugins/google/vpcnetwork/excessiveFirewallRules.spec.js
  plugins/google/vpcnetwork/multipleSubnets.js
  plugins/google/vpcnetwork/multipleSubnets.spec.js
Labels: readytogo, reviewed

#656 feature/AKD-133: Added Azure 'Accelerated Networking Enabled' plugin and test cases
  collectors/azure/collector.js
  exports.js
  helpers/azure/locations.js
  plugins/azure/virtualmachines/acceleratedNetworkingEnabled.js
  plugins/azure/virtualmachines/acceleratedNetworkingEnabled.spec.js
Labels: readytogo, reviewed

#616 feature/AKD-107: Added Azure 'Point in Time Restore (PITR) Backup Retention Period' plugin and test cases
  collectors/azure/collector.js
  exports.js
  plugins/azure/sqldatabases/pitrBackupEnabled.js
  plugins/azure/sqldatabases/pitrBackupEnabled.spec.js
Labels: readytogo

#657 feature/AKD-127: Added Azure 'No Empty Scale Sets' plugin and test cases
  collectors/azure/collector.js
  exports.js
  plugins/azure/virtualmachines/noEmptyScaleSets.js
  plugins/azure/virtualmachines/noEmptyScaleSets.spec.js
Labels: readytogo, reviewed

#658 feature/AKD-135: Added Azure 'Automatic Instance Repair Enabled' plugin and test cases
  exports.js
  plugins/azure/virtualmachines/autoInstanceRepairsEnabled.js
  plugins/azure/virtualmachines/autoInstanceRepairsEnabled.spec.js
Labels: readytogo, reviewed

#660 GCP SQL Plugin added for PostgreSQL db.
  exports.js
  plugins/google/sql/postgresqlLogLockWaits.js
  plugins/google/sql/postgresqlLogLockWaits.spec.js
Labels: readytogo, reviewed

#662 feature/AKD-150: Added Azure 'VM Managed Disks Enabled' plugin and test cases
  exports.js
  plugins/azure/virtualmachines/vmManagedDisks.js
  plugins/azure/virtualmachines/vmManagedDisks.spec.js
Labels: readytogo, reviewed
