Repository aquasecurity/cloudsploit, pull requests merged in 2022-06, with the labels that each got.

#1029 SAAS/3255: Added missing specs for RDS plugins
  plugins/aws/rds/rdsAutomatedBackups.spec.js
  plugins/aws/rds/rdsLoggingEnabled.spec.js
  plugins/aws/rds/rdsPubliclyAccessible.spec.js
  plugins/aws/rds/rdsRestorable.js
  plugins/aws/rds/rdsRestorable.spec.js
  plugins/aws/rds/rdsSnapshotEncryption.spec.js
Labels: enhancement, readytogo, reviewed, hotfix, Current Release

#1232 SAAS-4972: Added Modification for Remediation Trigger To Open Plugins
  plugins/aws/ec2/openCIFS.js
  plugins/aws/ec2/openDNS.js
  plugins/aws/ec2/openDocker.js
  plugins/aws/ec2/openElasticsearch.js
  plugins/aws/ec2/openFTP.js
  plugins/aws/ec2/openHadoopNameNode.js
  plugins/aws/ec2/openHadoopNameNodeWebUI.js
  plugins/aws/ec2/openKibana.js
  plugins/aws/ec2/openMySQL.js
  plugins/aws/ec2/openNetBIOS.js
  plugins/aws/ec2/openOracle.js
  plugins/aws/ec2/openPostgreSQL.js
  plugins/aws/ec2/openRDP.js
  plugins/aws/ec2/openRPC.js
  plugins/aws/ec2/openSMBoTCP.js
  plugins/aws/ec2/openSMTP.js
  plugins/aws/ec2/openSQLServer.js
  plugins/aws/ec2/openSSH.js
  plugins/aws/ec2/openSalt.js
  plugins/aws/ec2/openTelnet.js
  plugins/aws/ec2/openVNCClient.js
  plugins/aws/ec2/openVNCServer.js
Labels: enhancement, Current Release

#1283 SAAS-5610: Added a new boolean setting to whitelist AWS AppConfig S3 buckets.
  helpers/aws/api.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/s3/bucketEncryption.js
  plugins/aws/s3/bucketEncryption.spec.js
Labels: enhancement, readytogo, reviewed, Current Release

#1248 Added checkAllUsedServicesPlugin
  exports.js
  helpers/aws/api.js
  plugins/aws/iam/rolePolicyUnusedServices.js
  plugins/aws/iam/rolePolicyUnusedServices.spec.js
Labels: readytogo, reviewed, Current Release

#1293 GCP - Open All Ports Fix
  helpers/google/functions.js
  plugins/google/vpcnetwork/openAllPorts.js
  plugins/google/vpcnetwork/openCIFS.js
  plugins/google/vpcnetwork/openCassandra.js
  plugins/google/vpcnetwork/openCustomPorts.js
  plugins/google/vpcnetwork/openDNS.js
  plugins/google/vpcnetwork/openDocker.js
  plugins/google/vpcnetwork/openFTP.js
  plugins/google/vpcnetwork/openHadoopNameNode.js
  plugins/google/vpcnetwork/openHadoopNameNodeWebUI.js
  plugins/google/vpcnetwork/openKibana.js
  plugins/google/vpcnetwork/openMongo.js
  plugins/google/vpcnetwork/openMsSQL.js
  plugins/google/vpcnetwork/openMySQL.js
  plugins/google/vpcnetwork/openNetBIOS.js
  plugins/google/vpcnetwork/openOracle.js
  plugins/google/vpcnetwork/openOracleAutoDataWarehouse.js
  plugins/google/vpcnetwork/openPostgreSQL.js
  plugins/google/vpcnetwork/openRDP.js
  plugins/google/vpcnetwork/openRPC.js
  plugins/google/vpcnetwork/openRedis.js
  plugins/google/vpcnetwork/openSMBoTCP.js
  plugins/google/vpcnetwork/openSMTP.js
  plugins/google/vpcnetwork/openSQLServer.js
  plugins/google/vpcnetwork/openSSH.js
  plugins/google/vpcnetwork/openSalt.js
  plugins/google/vpcnetwork/openTelnet.js
  plugins/google/vpcnetwork/openVNCClient.js
  plugins/google/vpcnetwork/openVNCServer.js
Labels: readytogo, reviewed, hotfix

#1292 SAAS-5546: Added captureAppropriateCategories plugin and spec
  exports.js
  plugins/azure/monitor/diagnosticsCapturedCategories.js
  plugins/azure/monitor/diagnosticsCapturedCategories.spec.js
Labels: readytogo, reviewed

#1291 SAAS-5545: Added diagnosticsSettingsEnabled plugin and spec
  exports.js
  plugins/azure/monitor/diagnosticsSettingsEnabled.js
  plugins/azure/monitor/diagnosticsSettingsEnabled.spec.js
Labels: readytogo, reviewed

#1308 SAAS-6130: OCI - Notification topic with subscription plugin
  collectors/oracle/collector.js
  exports.js
  helpers/oracle/regions.js
  other_modules/oci/services.json
  plugins/oracle/identity/notificationTopicSubscription.js
  plugins/oracle/identity/notificationTopicSubscription.spec.js
Labels: readytogo, reviewed, Current Release

#1307 SAAS-6129: OCI - deafult Tags For Resources Plugin
  collectors/oracle/collector.js
  exports.js
  helpers/oracle/regions.js
  other_modules/oci/services.json
  plugins/oracle/identity/defaultTagsForResources.js
  plugins/oracle/identity/defaultTagsForResources.spec.js
Labels: readytogo, reviewed, Current Release

#1303 SAAS-5876: Oracle - VCN Inbound Security Lists
  exports.js
  plugins/oracle/networking/inboundSecurityLists.js
  plugins/oracle/networking/inboundSecurityLists.spec.js
Labels: readytogo, reviewed, Current Release

#1290 SAAS-5736: Oracle - Bucket Object Events
  exports.js
  plugins/oracle/objectstore/bucketObjectEvents.js
  plugins/oracle/objectstore/bucketObjectEvents.spec.js
Labels: readytogo, reviewed, Current Release

#1289 SAAS-5735: Oracle - Instance Legacy Metadata Endpoint Disabled
  exports.js
  plugins/oracle/compute/legacyEndpointDisabled.js
  plugins/oracle/compute/legacyEndpointDisabled.spec.js
Labels: readytogo, reviewed, Current Release

#1241 SAAS-3777: Oracle - OKE Secrets Encryption Plugin
  collectors/oracle/collector.js
  exports.js
  helpers/oracle/functions.js
  helpers/oracle/index.js
  helpers/oracle/regions.js
  other_modules/oci/index.js
  other_modules/oci/services.json
  plugins/oracle/oke/okePrivateEndpoint.js
  plugins/oracle/oke/okeSecretsEncrypted.js
  plugins/oracle/oke/okeSecretsEncrypted.spec.js
Labels: readytogo, reviewed, Current Release

#1279 SAAS-5581: OCI File System CMK Encryption Plugin
  collectors/oracle/collector.js
  exports.js
  helpers/oracle/regions.js
  other_modules/oci/services.json
  plugins/oracle/filestorage/fileSystemsCMKEncryption.js
  plugins/oracle/filestorage/fileSystemsCMKEncryption.spec.js
Labels: readytogo, reviewed, Current Release

#1278 SAAS-5567: OCI Boot Volume Encryption Plugin
  exports.js
  plugins/oracle/compute/bootVolumeCMKEncryption.js
  plugins/oracle/compute/bootVolumeCMKEncryption.spec.js
Labels: readytogo, reviewed, Current Release

#1277 SAAS-5566: OCI Block Volume CMK Encryption Plugin
  exports.js
  plugins/oracle/blockstorage/blockVolumeCMKEncryption.js
  plugins/oracle/blockstorage/blockVolumeCMKEncryption.spec.js
Labels: readytogo, reviewed, Current Release

#1276 SAAS-5565: OCI Bucket Versioning Plugin
  exports.js
  plugins/oracle/objectstore/bucketVersioning.js
  plugins/oracle/objectstore/bucketVersioning.spec.js
Labels: readytogo, reviewed, Current Release

#1240 SAAS-3774: Oracle - Bucket CMK Encryption Plugin
  collectors/oracle/collector.js
  exports.js
  helpers/oracle/regions.js
  plugins/oracle/objectstore/bucketCMKEncryption.js
  plugins/oracle/objectstore/bucketCMKEncryption.spec.js
Labels: readytogo, reviewed, Current Release

#1202 SAAS-4755: Added MSK Cluster Unauthenticated Access Plugin
  exports.js
  plugins/aws/msk/mskClusterUnauthAccess.js
  plugins/aws/msk/mskClusterUnauthAccess.spec.js
Labels: readytogo, reviewed, Current Release

#1228 SAAS-4960: Added EC2 Instances Optimized Plugin
  exports.js
  helpers/aws/api.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/computeoptimizer/ec2InstancesOptimized.js
  plugins/aws/computeoptimizer/ec2InstancesOptimized.spec.js
Labels: readytogo, reviewed, Current Release

#1203 SAAS-4764: Added MSK Cluster Public Access Plugin
  exports.js
  plugins/aws/msk/mskClusterPublicAccess.js
  plugins/aws/msk/mskClusterPublicAccess.spec.js
Labels: readytogo, reviewed, Current Release

#1204 SAAS-4768: Added MSK Cluster Client Broker Encryption Plugin
  exports.js
  plugins/aws/msk/mskClusterCBEncryption.js
  plugins/aws/msk/mskClusterCBEncryption.spec.js
Labels: readytogo, reviewed, Current Release

#1187 SAAS-4491: Added Enhanced Metadata Collection Enabled Plugin
  exports.js
  helpers/aws/api.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/imagebuilder/enhancedMetadataEnabled.js
  plugins/aws/imagebuilder/enhancedMetadataEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1234 SAAS-4977: Added EBS Volumes Optimized Plugins
  exports.js
  plugins/aws/computeoptimizer/ebsVolumesOptimized.js
  plugins/aws/computeoptimizer/ebsVolumesOptimized.spec.js
Labels: readytogo, reviewed, Current Release

#1233 SAAS-4973: Added Optimized Configuration Error Plugins
  exports.js
  plugins/aws/computeoptimizer/optimizerRecommendationsEnabled.js
  plugins/aws/computeoptimizer/optimizerRecommendationsEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1230 SAAs-4970: Added Auto Scaling Groups Optimized Plugin
  exports.js
  plugins/aws/computeoptimizer/asgOptimized.js
  plugins/aws/computeoptimizer/asgOptimized.spec.js
Labels: readytogo, reviewed, Current Release

#1231 SAAS-4971: Added Lambda Function Findings Optimized Plugin
  exports.js
  plugins/aws/computeoptimizer/lambdaFunctionsOptimized.js
  plugins/aws/computeoptimizer/lambdaFunctionsOptimized.spec.js
  plugins/aws/computeoptimizer/optimizerRecommendationsEnabled.js
  plugins/aws/computeoptimizer/optimizerRecommendationsEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1309 SAAS-3776: OCI - OKE Security Groups Plugin
  exports.js
  plugins/oracle/oke/okeSecurityGroups.js
  plugins/oracle/oke/okeSecurityGroups.spec.js
Labels: readytogo, reviewed, Current Release
