Repository aquasecurity/cloudsploit, pull requests merged in 2022-07, with the labels that each got.

#1306 SAAS-5942: GCP,Oracle - separate results in Open Port plugins
  helpers/google/functions.js
  helpers/oracle/functions.js
  plugins/google/vpcnetwork/openCustomPorts.spec.js
  plugins/oracle/networking/openAllPortsProtocols.spec.js
  plugins/oracle/networking/openCIFS.spec.js
  plugins/oracle/networking/openDNS.spec.js
  plugins/oracle/networking/openDocker.spec.js
  plugins/oracle/networking/openFTP.spec.js
  plugins/oracle/networking/openHadoopNameNode.spec.js
  plugins/oracle/networking/openHadoopNameNodeWebUI.spec.js
  plugins/oracle/networking/openKibana.spec.js
  plugins/oracle/networking/openMySQL.spec.js
  plugins/oracle/networking/openNetBIOS.spec.js
  plugins/oracle/networking/openOracle.spec.js
  plugins/oracle/networking/openOracleAutoDataWarehouse.spec.js
  plugins/oracle/networking/openPostgreSQL.spec.js
  plugins/oracle/networking/openRDP.spec.js
  plugins/oracle/networking/openRPC.spec.js
  plugins/oracle/networking/openSMBoTCP.spec.js
  plugins/oracle/networking/openSMTP.spec.js
  plugins/oracle/networking/openSQLServer.spec.js
  plugins/oracle/networking/openSSH.spec.js
  plugins/oracle/networking/openSalt.spec.js
  plugins/oracle/networking/openTelnet.spec.js
  plugins/oracle/networking/openVNCClient.spec.js
  plugins/oracle/networking/openVNCServer.spec.js
Labels: enhancement, question, Current Release

#1305 SAAS-UpdatedEKSPlatform: Added updated EKS latest platform versions
  plugins/aws/eks/eksLatestPlatformVersion.js
  plugins/aws/eks/eksLatestPlatformVersion.spec.js
Labels: enhancement, readytogo, reviewed, Current Release

#1302 SAAS-5785: SSM Agent Auto Update Enabled Plugin Failure
  plugins/aws/ssm/ssmAgentAutoUpdateEnabled.js
Labels: readytogo, reviewed, hotfix, Current Release

#1297 SAAS-5894: Added Modify affected AWS plugins.
  helpers/aws/regions.js
  plugins/aws/backup/backupNotificationEnabled.js
  plugins/aws/backup/backupNotificationEnabled.spec.js
  plugins/aws/cloudtrail/cloudtrailBucketAccessLogging.js
  plugins/aws/cloudtrail/cloudtrailBucketAccessLogging.spec.js
  plugins/aws/cloudtrail/cloudtrailBucketDelete.js
  plugins/aws/cloudtrail/cloudtrailBucketDelete.spec.js
  plugins/aws/cloudtrail/cloudtrailBucketPrivate.js
  plugins/aws/cloudtrail/cloudtrailBucketPrivate.spec.js
  plugins/aws/cloudtrail/cloudtrailNotificationsEnabled.js
  plugins/aws/cloudtrail/cloudtrailNotificationsEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1285 SAAS-Alibaba: Updated Alibaba RAM Inactive User Disabled date.
  plugins/alibaba/ram/inactiveUserDisabled.spec.js
Labels: enhancement, readytogo, reviewed, Current Release

#1281 SLK-51769: Insecure EC2 Metadata Options Fault Removed
  plugins/aws/ec2/ebsEncryptedSnapshots.js
  plugins/aws/ec2/ebsEncryptedSnapshots.spec.js
  plugins/aws/ec2/ec2MetadataOptions.js
Labels: enhancement, readytogo, reviewed, Current Release

#1275 Fix typo in GCP audit role
  docs/gcp.md
Labels: readytogo, reviewed, Current Release

#1274 SAAS-5526: Added Missing Specs For AWS Plugins
  plugins/aws/acm/acmValidation.spec.js
  plugins/aws/redshift/redshiftEncryptionEnabled.spec.js
  plugins/aws/redshift/redshiftPubliclyAccessible.spec.js
  plugins/aws/route53/domainAutoRenew.spec.js
  plugins/aws/route53/domainExpiry.spec.js
  plugins/aws/route53/domainTransferLock.spec.js
Labels: enhancement, readytogo, reviewed, Current Release

#1304 SAAS-5942: Added Results per resource for Open Port plugins
  helpers/aws/functions.js
Labels: duplicate

#1321 modified open port plugins to produce 1 result per plugin
  helpers/azure/functions.js
  plugins/azure/networksecuritygroups/openAllPorts.spec.js
  plugins/azure/networksecuritygroups/openCIFS.spec.js
  plugins/azure/networksecuritygroups/openDNS.spec.js
  plugins/azure/networksecuritygroups/openDocker.spec.js
  plugins/azure/networksecuritygroups/openFTP.spec.js
  plugins/azure/networksecuritygroups/openHadoopNameNode.spec.js
  plugins/azure/networksecuritygroups/openHadoopNameNodeWebUI.spec.js
  plugins/azure/networksecuritygroups/openKibana.spec.js
  plugins/azure/networksecuritygroups/openMySQL.spec.js
  plugins/azure/networksecuritygroups/openNetBIOS.spec.js
  plugins/azure/networksecuritygroups/openOracle.spec.js
  plugins/azure/networksecuritygroups/openOracleAutoDataWarehouse.spec.js
  plugins/azure/networksecuritygroups/openPostgreSQL.spec.js
  plugins/azure/networksecuritygroups/openRDP.spec.js
  plugins/azure/networksecuritygroups/openRPC.spec.js
  plugins/azure/networksecuritygroups/openSMBoTCP.spec.js
  plugins/azure/networksecuritygroups/openSMTP.spec.js
  plugins/azure/networksecuritygroups/openSQLServer.spec.js
  plugins/azure/networksecuritygroups/openSSH.spec.js
  plugins/azure/networksecuritygroups/openSalt.spec.js
  plugins/azure/networksecuritygroups/openTelnet.spec.js
  plugins/azure/networksecuritygroups/openVNCClient.spec.js
  plugins/azure/networksecuritygroups/openVNCServer.spec.js
Labels: enhancement, readytogo, reviewed, Current Release

#1322 added setting in s3 bucket website enabled to whitelist empty buckets
  helpers/aws/api.js
  helpers/aws/api_multipart.js
  plugins/aws/s3/bucketWebsiteEnabled.js
  plugins/aws/s3/bucketWebsiteEnabled.spec.js
Labels: enhancement, readytogo, reviewed, Current Release

#1143 SAAS-3871: Functions to handle GCP Remediations
  config_example.js
  helpers/google/functions.js
  helpers/google/index.js
  index.js
Labels: readytogo, reviewed, Current Release

#1152 SAAS-3869: GCP Remediation for Bucket Versioning Plugin
  helpers/google/index.js
  plugins/google/storage/bucketVersioning.js
Labels: readytogo, reviewed, remediation, Current Release

#1310 SAAS-6654: OCI - Event Rules Plugins
  collectors/oracle/collector.js
  exports.js
  helpers/oracle/functions.js
  helpers/oracle/regions.js
  other_modules/oci/services.json
  plugins/oracle/identity/iamGroupChanges.js
  plugins/oracle/identity/iamGroupChanges.spec.js
  plugins/oracle/identity/iamPolicyChanges.js
  plugins/oracle/identity/iamPolicyChanges.spec.js
  plugins/oracle/identity/identityProviderChanges.js
  plugins/oracle/identity/identityProviderChanges.spec.js
  plugins/oracle/identity/idpGroupMappingChanges.js
  plugins/oracle/identity/idpGroupMappingChanges.spec.js
  plugins/oracle/identity/userChanges.js
  plugins/oracle/identity/userChanges.spec.js
  plugins/oracle/networking/networkGatewayChanges.js
  plugins/oracle/networking/networkGatewayChanges.spec.js
  plugins/oracle/networking/routeTableChanges.js
  plugins/oracle/networking/routeTableChanges.spec.js
  plugins/oracle/networking/securityGroupChanges.js
  plugins/oracle/networking/securityGroupChanges.spec.js
  plugins/oracle/networking/securityListChanges.js
  plugins/oracle/networking/securityListChanges.spec.js
  plugins/oracle/networking/vcnChanges.js
  plugins/oracle/networking/vcnChanges.spec.js
Labels: readytogo, reviewed, Current Release

#1324 SAAS-7050: OCI - Flow Logs Enabled Plugin
  collectors/oracle/collector.js
  exports.js
  helpers/oracle/regions.js
  other_modules/oci/services.json
  plugins/oracle/networking/flowLogsEnabled.js
  plugins/oracle/networking/flowLogsEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1325 SAAS-7051: OCI - Key Rotation Plugin
  collectors/oracle/collector.js
  exports.js
  helpers/oracle/regions.js
  other_modules/oci/index.js
  other_modules/oci/services.json
  plugins/oracle/vaults/keyRotation.js
  plugins/oracle/vaults/keyRotation.spec.js
Labels: readytogo, reviewed, Current Release

#1339 Added 7061
  exports.js
  plugins/oracle/objectstore/bucketWriteLogsEnabled.js
  plugins/oracle/objectstore/bucketWriteLogsEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1327 SAAS-7116: OCI - Cloud Guard Enabled Plugin
  collectors/oracle/collector.js
  exports.js
  helpers/oracle/regions.js
  other_modules/oci/services.json
  plugins/oracle/cloudguard/cloudguardEnabled.js
  plugins/oracle/cloudguard/cloudguardEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1196 SAAS-4653: Added Image Builder Components Encrypted Plugin
  exports.js
  helpers/aws/api.js
  plugins/aws/imagebuilder/imgBuilderComponentsEncrypted.js
  plugins/aws/imagebuilder/imgBuilderComponentsEncrypted.spec.js
Labels: readytogo, reviewed, Current Release

#1195 SAAS-4534: Added Docker File Template Encrypted Plugin
  exports.js
  helpers/aws/api.js
  plugins/aws/imagebuilder/dockerfileTemplateEncrypted.js
  plugins/aws/imagebuilder/dockerfileTemplateEncrypted.spec.js
Labels: readytogo, reviewed, Current Release

#1192 SAAS-4562: Added Infrastructure Configuration Notification Enabled Plugin
  exports.js
  helpers/aws/api.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/imagebuilder/infraConfigNotificationEnabled.js
  plugins/aws/imagebuilder/infraConfigNotificationEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1191 SAAS-4494: Added Image Recipe storage volumes encrypted Plugin
  exports.js
  helpers/aws/api.js
  plugins/aws/imagebuilder/imageRecipeVolumeEncrypted.js
  plugins/aws/imagebuilder/imageRecipeVolumeEncrypted.spec.js
Labels: readytogo, reviewed, Current Release

#1334 SAAS-7199: Added spec for Azure File Service
  plugins/azure/fileservice/fileServiceAllAccessAcl.spec.js
Labels: Current Release

#1333 SAAS-7160: Added Modifications and spec for Azure Queue Service
  plugins/azure/queueservice/queueServiceAllAccessAcl.js
  plugins/azure/queueservice/queueServiceAllAccessAcl.spec.js
Labels: Current Release

#1331 SAAS-7192: Added missing specs for Azure sql server service
  plugins/azure/sqlserver/tdeProtectorEncrypted.spec.js
Labels: Current Release

#1330 SAAS-7179: Added missing specs for Azure security center service
  plugins/azure/securitycenter/appWhitelistingEnabled.spec.js
  plugins/azure/securitycenter/monitorBlobEncryption.spec.js
  plugins/azure/securitycenter/monitorDiskEncryption.spec.js
  plugins/azure/securitycenter/monitorEndpointProtection.spec.js
  plugins/azure/securitycenter/monitorJitNetworkAccess.spec.js
  plugins/azure/securitycenter/monitorNsgEnabled.spec.js
  plugins/azure/securitycenter/monitorSqlAuditing.spec.js
  plugins/azure/securitycenter/monitorSqlEncryption.spec.js
  plugins/azure/securitycenter/monitorSystemUpdates.spec.js
  plugins/azure/securitycenter/monitorVMVulnerability.spec.js
  plugins/azure/securitycenter/securityConfigMonitoring.spec.js
Labels: Current Release

#1315 SAAS-6759: Added Key Vaults Plugins Missing Specs
  plugins/azure/keyvaults/keyExpirationEnabled.spec.js
  plugins/azure/keyvaults/kvRecoveryEnabled.spec.js
Labels: Current Release

#1328 SAAS-7053: Added missing specs for Azure monitor service
  plugins/azure/monitor/lbLogAnalyticsEnabled.spec.js
  plugins/azure/monitor/logProfileArchiveData.spec.js
  plugins/azure/monitor/logProfileRetentionPolicy.spec.js
  plugins/azure/monitor/nsgLogAnalyticsEnabled.js
  plugins/azure/monitor/nsgLogAnalyticsEnabled.spec.js
Labels: Current Release

#1329 SAAS-7058: Added missing specs for Azure policy service
  plugins/azure/policyservice/resourceAllowedLocations.spec.js
  plugins/azure/policyservice/resourceLocationMatch.js
  plugins/azure/policyservice/resourceLocationMatch.spec.js
Labels: Current Release

#1312 SAAS-6699: Added Specs for Azure CDN Profiles Plugin
  plugins/azure/cdnprofiles/detectInsecureCustomOrigin.spec.js
  plugins/azure/cdnprofiles/endpointLoggingEnabled.spec.js
Labels: Current Release
