Repository aquasecurity/cloudsploit, pull requests merged in 2022-09, with the labels that each got.

#1365 SAAS-8575: GCP - Open Cassandra Monitoring Port Plugin
  exports.js
  plugins/google/vpcnetwork/openCassandraMonitoring.js
  plugins/google/vpcnetwork/openCassandraMonitoring.spec.js
Labels: readytogo, reviewed, Current Release

#1363 SAAS-8573: GCP - Open Cassnadra Client Port Plugin
  exports.js
  plugins/google/vpcnetwork/openCassandraClient.js
  plugins/google/vpcnetwork/openCassandraClient.spec.js
Labels: readytogo, reviewed, Current Release

#1361 SAAS-8386: GCP - Open Elasticsearch Port Plugin
  exports.js
  plugins/google/vpcnetwork/openElasticsearch.js
  plugins/google/vpcnetwork/openElasticsearch.spec.js
Labels: readytogo, reviewed, Current Release

#1360 SAAS-8385: GCP - Open LDAP Port Plugin
  exports.js
  plugins/google/vpcnetwork/openLDAP.js
  plugins/google/vpcnetwork/openLDAP.spec.js
Labels: readytogo, reviewed, Current Release

#1359 SAAS-8384: GCP - Open SNMP Port Plugin
  exports.js
  plugins/google/vpcnetwork/openSNMP.js
  plugins/google/vpcnetwork/openSNMP.spec.js
Labels: readytogo, reviewed, Current Release

#1358 SAAS-8383: GCP - Open Memcached Port Plugin
  exports.js
  plugins/google/vpcnetwork/openMemcached.js
  plugins/google/vpcnetwork/openMemcached.spec.js
Labels: readytogo, reviewed, Current Release

#1357 SAAS-8382: GCP - Open LDAP SSL Port Plugin
  exports.js
  plugins/google/vpcnetwork/openLDAPS.js
  plugins/google/vpcnetwork/openLDAPS.spec.js
Labels: readytogo, reviewed, Current Release

#1356 SAAS-8379: Added RDS Snapshot Publicly Accessible Plugin
  exports.js
  helpers/aws/api.js
  helpers/aws/api_multipart.js
  plugins/aws/rds/rdsSnapshotPubliclyAccessible.js
  plugins/aws/rds/rdsSnapshotPubliclyAccessible.spec.js
Labels: readytogo, reviewed, Current Release

#1371 SAAS-8376: Added Internet Gateway In VPC plugin
  exports.js
  plugins/aws/ec2/internetGatewayInVpc.js
  plugins/aws/ec2/internetGatewayInVpc.spec.js
Labels: readytogo, reviewed, Current Release

#1364 SAAS-8574: GCP - Open Cassnadra Internode Port Plugin
  exports.js
  plugins/google/vpcnetwork/openCassandraInternode.js
  plugins/google/vpcnetwork/openCassandraInternode.spec.js
Labels: readytogo, reviewed, Current Release

#1347 SAAS:7943: Added some new and open ports plugin
  exports.js
  package-lock.json
  plugins/aws/ec2/openCassandraClient.js
  plugins/aws/ec2/openCassandraClient.spec.js
  plugins/aws/ec2/openCassandraInternode.js
  plugins/aws/ec2/openCassandraInternode.spec.js
  plugins/aws/ec2/openCassandraMonitoring.js
  plugins/aws/ec2/openCassandraMonitoring.spec.js
  plugins/aws/ec2/openCassandraThrift.js
  plugins/aws/ec2/openCassandraThrift.spec.js
  plugins/aws/ec2/openInternalWeb.js
  plugins/aws/ec2/openInternalWeb.spec.js
  plugins/aws/ec2/openLDAP.js
  plugins/aws/ec2/openLDAP.spec.js
  plugins/aws/ec2/openLDAPS.js
  plugins/aws/ec2/openLDAPS.spec.js
  plugins/aws/ec2/openMemcached.js
  plugins/aws/ec2/openMemcached.spec.js
  plugins/aws/ec2/openMongoDB.js
  plugins/aws/ec2/openMongoDB.spec.js
  plugins/aws/ec2/openRedis.js
  plugins/aws/ec2/openRedis.spec.js
  plugins/aws/ec2/openSNMP.js
  plugins/aws/ec2/openSNMP.spec.js
  plugins/aws/iam/policyAllowsToChangePassword.js
  plugins/aws/iam/policyAllowsToChangePassword.spec.js
Labels: readytogo, reviewed, Current Release

#1342 SAAS-7688: Added Azure Enable Trusted Microsoft Services for Key Vault Access pl…
  exports.js
  plugins/azure/keyvaults/trustedServicesEnabled.js
  plugins/azure/keyvaults/trustedServicesEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1341 SAAS-7582: Added Azure Restrict Default Network Access For Key Vaults
  exports.js
  plugins/azure/keyvaults/restrictDefaultNetworkAccess.js
  plugins/azure/keyvaults/restrictDefaultNetworkAccess.spec.js
Labels: readytogo, reviewed, Current Release

#1368 SAAS-8548: Added AWS Config Services In Use Plugin
  exports.js
  plugins/aws/configservice/servicesInUse.js
  plugins/aws/configservice/servicesInUse.spec.js
Labels: readytogo, reviewed, Current Release

#1374 SAAS-8748: Azure Collector changes for missing permissions
  collectors/azure/collector.js
Labels: enhancement, readytogo, reviewed, Current Release

#1369 SAAS-8579: GCP - Modified some open ports plugins
  plugins/google/vpcnetwork/openMongo.js
  plugins/google/vpcnetwork/openNetBIOS.js
Labels: enhancement, readytogo, reviewed, Current Release

#1362 SAAS-8550: GCP - Added a warn setting to API Key Rotation Plugin
  plugins/google/api/apiKeyRotation.js
  plugins/google/api/apiKeyRotation.spec.js
Labels: enhancement, readytogo, reviewed, Current Release

#1344 SAAS-7942: Modified EC2 open ports plugin
  plugins/aws/ec2/openElasticsearch.js
  plugins/aws/ec2/openNetBIOS.js
Labels: enhancement, readytogo, reviewed, Current Release

#1406 Feature/saas 9308 aws ensure eks cluster have tags
  exports.js
  helpers/aws/api.js
  helpers/aws/api_multipart.js
  helpers/aws/functions.js
  plugins/aws/eks/eksClusterHasTags.js
  plugins/aws/eks/eksClusterHasTags.spec.js
Labels: readytogo, reviewed, Current Release

#1388 SAAS-9139: GCP - DNS Zone Labels Added Plugin
  exports.js
  plugins/google/dns/dnsZoneLabelsAdded.js
  plugins/google/dns/dnsZoneLabelsAdded.spec.js
Labels: readytogo, reviewed, Current Release

#1387 SAAS-9138: GCP - SQL Instance Labels Added Plugin
  exports.js
  plugins/google/sql/sqlInstanceLabelsAdded.js
  plugins/google/sql/sqlInstanceLabelsAdded.spec.js
Labels: readytogo, reviewed, Current Release

#1407 HotFix - IAM: Role policy unused services
  plugins/aws/iam/rolePolicyUnusedServices.js
Labels: readytogo, reviewed, hotfix

#1379 SAAS-9123: GCP - Dataset Lables Added Plugin
  exports.js
  plugins/google/bigquery/datasetLabelsAdded.js
  plugins/google/bigquery/datasetLabelsAdded.spec.js
Labels: readytogo, reviewed, Current Release

#1380 SAAS-9124: GCP - Topic Labels Added Plugin
  exports.js
  plugins/google/pubsub/topicLabelsAdded.js
  plugins/google/pubsub/topicLabelsAdded.spec.js
Labels: readytogo, reviewed, Current Release

#1381 SAAS-9125: GCP - Bucket Labels Added Plugin
  exports.js
  plugins/google/storage/bucketLabelsAdded.js
  plugins/google/storage/bucketLabelsAdded.spec.js
Labels: readytogo, reviewed, Current Release

#1382 SAAS-9131: GCP - Instance Labels Added Plugin
  exports.js
  plugins/google/compute/instanceLabelsAdded.js
  plugins/google/compute/instanceLabelsAdded.spec.js
Labels: readytogo, reviewed, Current Release

#1384 SAAS-9135: GCP - Cloud Function Labels Added Plugin
  exports.js
  plugins/google/cloudfunctions/cloudFunctionLabelsAdded.js
  plugins/google/cloudfunctions/cloudFunctionLabelsAdded.spec.js
Labels: readytogo, reviewed, Current Release

#1383 SAAS-9134: GCP - Image Labels Added Plugin
  exports.js
  plugins/google/compute/imageLabelsAdded.js
  plugins/google/compute/imageLabelsAdded.spec.js
Labels: readytogo, reviewed, Current Release

#1385 SAAS-9136: GCP - Compute Disk Labels Added Plugin
  exports.js
  plugins/google/compute/diskLabelsAdded.js
  plugins/google/compute/diskLabelsAdded.spec.js
Labels: readytogo, reviewed, Current Release

#1386 SAAS-9137: GCP - Compute Disk Snapshot Labels Added Plugin
  exports.js
  plugins/google/compute/snapshotLabelsAdded.js
  plugins/google/compute/snapshotLabelsAdded.spec.js
Labels: readytogo, reviewed, Current Release
