Repository aquasecurity/cloudsploit, pull requests merged in 2022-05, with the labels that each got.

#1243 SLK-50956: Fixed logical error in versionedBucketsLC plugin
  plugins/aws/s3/versionedBucketsLC.js
Labels: hotfix

#1244 SAAS-5274: Added ARN To The Plugins
  plugins/aws/autoscaling/asgMultiAz.js
  plugins/aws/ec2/flowLogsEnabled.js
  plugins/aws/ec2/multipleSubnets.js
  plugins/aws/elb/insecureCiphers.js
  plugins/aws/redshift/redshiftEncryptionEnabled.js
  plugins/aws/redshift/redshiftPubliclyAccessible.js
  plugins/aws/redshift/redshiftUnusedReservedNodes.js
  plugins/aws/ses/dkimEnabled.js
Labels: enhancement, hotfix

#1246 SLK-51015: Resolved Unknown Issue to Plugins
  plugins/aws/cloudtrail/cloudtrailNotificationsEnabled.js
  plugins/aws/cloudtrail/cloudtrailNotificationsEnabled.spec.js
  plugins/aws/configservice/configServiceMissingBucket.js
  plugins/aws/s3/bucketPolicyCloudFrontOai.js
Labels: hotfix

#1267 Saas 5434 Added azure sqlServerRecurringScans plugin
  collectors/azure/collector.js
  exports.js
  plugins/azure/sqlserver/sqlServerRecurringScans.js
  plugins/azure/sqlserver/sqlServerRecurringScans.spec.js
Labels: readytogo, reviewed, Current Release

#1266 Saas 5439 Added Azure serverSendEmailToAdmins plugin
  exports.js
  plugins/azure/sqlserver/serverSendEmailToAdmins.js
  plugins/azure/sqlserver/serverSendEmailToAdmins.spec.js
Labels: readytogo, reviewed, Current Release

#1265 Saas 5416 Added Azure enableDefenderForContainer plugin
  exports.js
  plugins/azure/defender/enableDefenderForContainers.js
  plugins/azure/defender/enableDefenderForContainers.spec.js
Labels: readytogo, reviewed, Current Release

#1264 Saas 5415 Added azure enableDefenderForStorage plugin
  exports.js
  plugins/azure/defender/enableDefenderForStorage.js
  plugins/azure/defender/enableDefenderForStorage.spec.js
Labels: readytogo, reviewed, Current Release

#1263 Saas 5497 Added Azure keyVaultInUse plugin
  exports.js
  plugins/azure/keyvaults/keyVaultInUse.js
  plugins/azure/keyvaults/keyVaultInUse.spec.js
Labels: readytogo, reviewed, Current Release

#1259 Fix typo in README Azure link
  README.md
Labels: readytogo, reviewed

#1270 SAAS 5414 Added plugin enableDefenderForSqlServers
  exports.js
  plugins/azure/defender/enableDefenderForSqlServers.js
  plugins/azure/defender/enableDefenderForSqlServers.spec.js
Labels: readytogo, reviewed, Current Release

#1236 SAAS-3775: Oracle - OKE Private Endpoint Plugin
  collectors/oracle/collector.js
  exports.js
  helpers/oracle/regions.js
  other_modules/oci/services.json
  plugins/oracle/oke/okePrivateEndpoint.js
  plugins/oracle/oke/okePrivateEndpoint.spec.js
Labels: readytogo, reviewed, Current Release

#1227 SAAS-4942: Oracle Identity Users Password Last Used Plugin
  exports.js
  plugins/oracle/identity/usersPasswordLastUsed.js
  plugins/oracle/identity/usersPasswordLastUsed.spec.js
Labels: question, Current Release

#1226 SAAS-4777: GCP - API Key Application Restriction Plugin
  collectors/google/collector.js
  exports.js
  helpers/google/index.js
  helpers/google/regions.js
  plugins/google/api/apiKeyApplicationRestriction.js
  plugins/google/api/apiKeyApplicationRestriction.spec.js
Labels: readytogo, reviewed, Current Release

#1225 SAAS-4936: Oracle - Specs fro Open Ports Plugins
  plugins/oracle/networking/openAllPortsProtocols.spec.js
  plugins/oracle/networking/openCIFS.spec.js
  plugins/oracle/networking/openDNS.spec.js
  plugins/oracle/networking/openDocker.spec.js
  plugins/oracle/networking/openFTP.spec.js
  plugins/oracle/networking/openHadoopNameNode.spec.js
  plugins/oracle/networking/openHadoopNameNodeWebUI.spec.js
  plugins/oracle/networking/openKibana.spec.js
  plugins/oracle/networking/openMySQL.spec.js
  plugins/oracle/networking/openNetBIOS.spec.js
  plugins/oracle/networking/openOracle.spec.js
  plugins/oracle/networking/openOracleAutoDataWarehouse.spec.js
  plugins/oracle/networking/openPostgreSQL.spec.js
  plugins/oracle/networking/openRDP.spec.js
  plugins/oracle/networking/openRPC.spec.js
  plugins/oracle/networking/openSMBoTCP.spec.js
  plugins/oracle/networking/openSMTP.spec.js
  plugins/oracle/networking/openSQLServer.spec.js
  plugins/oracle/networking/openSSH.spec.js
  plugins/oracle/networking/openSalt.spec.js
  plugins/oracle/networking/openTelnet.spec.js
  plugins/oracle/networking/openVNCClient.spec.js
  plugins/oracle/networking/openVNCServer.spec.js
Labels: readytogo, reviewed, Current Release

#1214 SAAS-4785: GCP PostgreSQL Latest Version
  exports.js
  plugins/google/sql/postgresqlLatestVersion.js
  plugins/google/sql/postgresqlLatestVersion.spec.js
Labels: readytogo, reviewed, Current Release

#1213 SAAS-4783: GCP MYSQL Latest Version Plugin
  exports.js
  plugins/google/sql/mysqlLatestVersion.js
  plugins/google/sql/mysqlLatestVersion.spec.js
Labels: readytogo, reviewed, Current Release

#1207 SAAS-4776: GCP API Key Rotation Plugin
  exports.js
  plugins/google/api/apiKeyRotation.js
  plugins/google/api/apiKeyRotation.spec.js
Labels: readytogo, reviewed, Current Release

#1185 SAAS-4456: GCP Disable Service Account Creation Plugin
  exports.js
  plugins/google/cloudresourcemanager/disableServiceAccountCreation.js
  plugins/google/cloudresourcemanager/disableServiceAccountCreation.spec.js
Labels: readytogo, reviewed, Current Release

#1184 SAAS-2243: GCP KMS Public Access Plugin
  collectors/google/collector.js
  exports.js
  plugins/google/cryptographickeys/keyProtectionLevel.js
  plugins/google/cryptographickeys/keyRotation.js
  plugins/google/cryptographickeys/kmsPublicAccess.js
  plugins/google/cryptographickeys/kmsPublicAccess.spec.js
Labels: readytogo, reviewed, Current Release

#1173 SAAS-2467: GCP Public Disk Images Plugin
  collectors/google/collector.js
  exports.js
  plugins/google/compute/publicDiskImages.js
  plugins/google/compute/publicDiskImages.spec.js
Labels: readytogo, reviewed, Current Release

#1167 SAAS-4207: GCP Instance Groups Auto Healing
  collectors/google/collector.js
  exports.js
  helpers/google/regions.js
  plugins/google/compute/instanceGroupAutoHealing.js
  plugins/google/compute/instanceGroupAutoHealing.spec.js
Labels: readytogo, reviewed, Current Release

#1175 SAAS-4171: Added backupRetentionPeriod plugin for app service
  collectors/azure/collector.js
  exports.js
  plugins/azure/appservice/backupRetentionPeriod.js
  plugins/azure/appservice/backupRetentionPeriod.spec.js
Labels: readytogo, reviewed, Current Release

#1176 Added checkAdvisorRecommendations plugin and spec
  collectors/azure/collector.js
  exports.js
  helpers/azure/locations.js
  plugins/azure/advisor/checkAdvisorRecommendations.js
  plugins/azure/advisor/checkAdvisorRecommendations.spec.js
Labels: readytogo, reviewed, Current Release

#1178 Added automatedBackupsEnabled plugin and spec
  exports.js
  plugins/azure/appservice/automatedBackupsEnabled.js
  plugins/azure/appservice/automatedBackupsEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1177 Added appInsightsEnabled plugin and spec
  collectors/azure/collector.js
  exports.js
  plugins/azure/appservice/appInsightsEnabled.js
  plugins/azure/appservice/appInsightsEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1201 SAAS-4234: Added appTierCmkInUse plugin and spec
  exports.js
  plugins/azure/keyvaults/appTierCmkInUse.js
  plugins/azure/keyvaults/appTierCmkInUse.spec.js
  plugins/azure/keyvaults/keyExpirationEnabled.js
  plugins/azure/keyvaults/kvRecoveryEnabled.js
  plugins/azure/keyvaults/secretExpirationEnabled.js
Labels: readytogo, reviewed, Current Release

#1210 SAAS-4235: Added allowedCertificateKeyTypes plugin and spec
  collectors/azure/collector.js
  exports.js
  plugins/azure/keyvaults/allowedCertificateKeyTypes.js
  plugins/azure/keyvaults/allowedCertificateKeyTypes.spec.js
Labels: readytogo, reviewed, Current Release

#1211 SAAS-4236: Added checkEncryptionKeysExpiry plugin and spec
  exports.js
  plugins/azure/keyvaults/keyVaultKeyExpiry.js
  plugins/azure/keyvaults/keyVaultKeyExpiry.spec.js
Labels: readytogo, reviewed, Current Release

#1212 SAAS-4237: Added checkSecretsExpiry plugin and spec
  exports.js
  plugins/azure/keyvaults/keyVaultSecretExpiry.js
  plugins/azure/keyvaults/keyVaultSecretExpiry.spec.js
Labels: reviewed, initial review, Current Release

#1221 SAAS-4238: Added rsaCertificateKeySize plugin and spec
  exports.js
  plugins/azure/keyvaults/rsaCertificateKeySize.js
  plugins/azure/keyvaults/rsaCertificateKeySize.spec.js
Labels: reviewed, initial review, Current Release

#1222 SAAS-4239: Added accessAndManagePermissions plugin and spec
  exports.js
  plugins/azure/keyvaults/manageKeyAccessAndPermissions.js
  plugins/azure/keyvaults/manageKeyAccessAndPermissions.spec.js
Labels: readytogo, reviewed, Current Release

#1223 SAAS-4240: Added sslCertificatesAutoRenewalPeriod plugin and spec
  exports.js
  plugins/azure/keyvaults/sslCertificateAutoRenewal.js
  plugins/azure/keyvaults/sslCertificateAutoRenewal.spec.js
Labels: readytogo, reviewed, Current Release

#1224 SAAS-4241: Added databaseTierCmkInUse plugin and spec
  exports.js
  plugins/azure/keyvaults/databaseTierCmkInUse.js
  plugins/azure/keyvaults/databaseTierCmkInUse.spec.js
Labels: readytogo, reviewed, Current Release

#1220 SAAS-4924: Added EC2 Remediations To Open Ports
  plugins/aws/ec2/openOracleAutoDataWarehouse.js
Labels: readytogo, reviewed, remediation, Current Release

#1253 SAAS-5432: Added enableATP plugin and spec
  collectors/azure/collector.js
  exports.js
  plugins/azure/sqlserver/enableATP.js
  plugins/azure/sqlserver/enableATP.spec.js
Labels: question, Current Release

#1271 Saas 5438 added azure sqlServerSendScanReports plugin
  exports.js
  plugins/azure/sqlserver/sqlServerSendScanReports.js
  plugins/azure/sqlserver/sqlServerSendScanReports.spec.js
Labels: readytogo, reviewed, Current Release

#1252 SAAS-5417: Added enableWDATPIntegration plugin and spec
  collectors/azure/collector.js
  exports.js
  helpers/azure/locations.js
  plugins/azure/defender/enableEndpointIntegration.js
  plugins/azure/defender/enableEndpointIntegration.spec.js
Labels: readytogo, reviewed, Current Release

#1258 SAAS-5411: Added Remediation for StackTerminationProtection Plugin
  plugins/aws/cloudformation/stackTerminationProtection.js
Labels: remediation, Current Release

#1268 SAAS-5530: Added openUDP plugin and spec
  exports.js
  plugins/azure/networksecuritygroups/openUDP.js
  plugins/azure/networksecuritygroups/openUDP.spec.js
Labels: readytogo, reviewed, Current Release
