Repository aquasecurity/cloudsploit, pull requests merged in 2022-04, with the labels that each got.

#1217 Added new setting in Google IAM Service Account Key Rotation plugin
  plugins/google/iam/serviceAccountKeyRotation.js
  plugins/google/iam/serviceAccountKeyRotation.spec.js
Labels: enhancement, Current Release

#1205 SAAS-847: Modified setting input regex to accept comma separated list for open …
  helpers/aws/functions.js
  plugins/aws/ec2/openCIFS.js
  plugins/aws/ec2/openDNS.js
  plugins/aws/ec2/openDocker.js
  plugins/aws/ec2/openElasticsearch.js
  plugins/aws/ec2/openFTP.js
  plugins/aws/ec2/openHadoopNameNode.js
  plugins/aws/ec2/openHadoopNameNodeWebUI.js
  plugins/aws/ec2/openKibana.js
  plugins/aws/ec2/openMySQL.js
  plugins/aws/ec2/openNetBIOS.js
  plugins/aws/ec2/openOracle.js
  plugins/aws/ec2/openPostgreSQL.js
  plugins/aws/ec2/openRDP.js
  plugins/aws/ec2/openRPC.js
  plugins/aws/ec2/openSMBoTCP.js
  plugins/aws/ec2/openSMTP.js
  plugins/aws/ec2/openSQLServer.js
  plugins/aws/ec2/openSSH.js
  plugins/aws/ec2/openSalt.js
  plugins/aws/ec2/openTelnet.js
  plugins/aws/ec2/openVNCClient.js
  plugins/aws/ec2/openVNCServer.js
Labels: enhancement, Current Release

#1200 hotfix: Added logic to check on server before databases for azure db auditing enabled plugin
  plugins/azure/sqldatabases/dbAuditingEnabled.js
  plugins/azure/sqldatabases/dbAuditingEnabled.spec.js
Labels: enhancement, hotfix, Current Release

#1130 Domain: Added domain to the Plugin
  plugins/aws/connect/customerProfilesDomainEncrypted.js
  plugins/google/dataflow/dataflowHangedJobs.js
  plugins/google/dataflow/dataflowJobsEncryption.js
Labels: enhancement, Current Release

#1133 SAAS-4011: Added new regions for AWS
  helpers/aws/regions.js
  plugins/aws/ec2/instanceMaxCount.js
Labels: enhancement, Current Release

#1142 Updated Lambda Old Runtimes Plugin
  plugins/aws/lambda/lambdaOldRuntimes.js
Labels: enhancement, reviewed, Current Release

#1197 Fixed false results bug
  plugins/aws/eventbridge/eventBusCrossAccountAccess.js
Labels: hotfix, Current Release

#1112 SAAS-3876: Added new regions for Alibaba
  helpers/alibaba/regions.js
Labels: enhancement, Current Release

#1111 SAAS-3875: Added new Azure regions
  helpers/azure/locations.js
Labels: enhancement, Current Release

#1110 SAAS-3868: Added new regions for oracle cloud
  helpers/oracle/regions.js
  helpers/oracle/regions_gov.js
  plugins/oracle/compute/instanceMaxCount.js
Labels: enhancement, Current Release

#1057 SAAS-3534: Added Firehose Encrypted Spec File
  plugins/aws/firehose/firehoseEncrypted.js
  plugins/aws/firehose/firehoseEncrypted.spec.js
Labels: enhancement, reviewed, hotfix, Current Release

#1055 SAAS-3536: Added Kinesis Streams Encrypted Spec File
  plugins/aws/kendra/kendraIndexEncrypted.spec.js
  plugins/aws/kinesis/kinesisEncrypted.js
  plugins/aws/kinesis/kinesisEncrypted.spec.js
Labels: enhancement, reviewed, hotfix, Current Release

#1136 Implemented rate limit for azure storage accounts api's
  collectors/azure/collector.js
Labels: enhancement

#1094 SAAS-2994: GCP collector refactoring
  collectors/google/collector.js
  helpers/google/index.js
Labels: enhancement

#1237 Added disableFTPDeployments plugin and spec
  exports.js
  plugins/azure/appservice/disableFTPDeployments.js
  plugins/azure/appservice/disableFTPDeployments.spec.js
Labels: reviewed, Current Release
