Repository aquasecurity/cloudsploit, pull requests merged in 2022-03, with the labels that each got.

#1097 SAAS-3830: Added Auto Scaling Unused Launch Configurations Plugin
  exports.js
  plugins/aws/autoscaling/asgUnusedLaunchConfiguration.js
  plugins/aws/autoscaling/asgUnusedLaunchConfiguration.spec.js
Labels: reviewed, Current Release

#1092 SAAS-3804: Added Access Analyzer Active Findings Plugin
  collectors/aws/accessanalyzer/listFindings.js
  collectors/aws/collector.js
  exports.js
  plugins/aws/accessanalyzer/accessAnalyzerActiveFindings.js
  plugins/aws/accessanalyzer/accessAnalyzerActiveFindings.spec.js
Labels: reviewed, Current Release

#1148 Added virtualMachinesDeallocate plugin and spec
  exports.js
  plugins/azure/logalerts/virtualMachinesDeallocateAlert.js
  plugins/azure/logalerts/virtualMachinesDeallocateAlert.spec.js
Labels: reviewed, Current Release

#1149 Added virtualMachinesPowerOffAlert plugin and spec
  exports.js
  plugins/azure/logalerts/virtualMachinesPowerOffAlert.js
  plugins/azure/logalerts/virtualMachinesPowerOffAlert.spec.js
Labels: reviewed, Current Release

#1150 Added sqlServerDatabaseRenameAlert plugin and spec
  exports.js
  plugins/azure/logalerts/sqlServerDatabaseRenameAlert.js
  plugins/azure/logalerts/sqlServerDatabaseRenameAlert.spec.js
Labels: reviewed, Current Release

#1159 SAAS-4125: Added App Mesh TLS Required Plugin
  collectors/aws/appmesh/describeVirtualGateway.js
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/appmesh/appmeshTLSRequired.js
  plugins/aws/appmesh/appmeshTLSRequired.spec.js
Labels: reviewed, Current Release

#1151 Added postgreSqlDBLoggingEnabled plugin and spec
  exports.js
  plugins/azure/logalerts/postgreSqlDBLoggingEnabled.js
  plugins/azure/logalerts/postgreSqlDBLoggingEnabled.spec.js
Labels: reviewed, Current Release

#1137 Added virtualMachineLogging plugin and spec
  exports.js
  plugins/azure/logalerts/virtualMachineLogging.js
  plugins/azure/logalerts/virtualMachineLogging.spec.js
Labels: question, Current Release

#1105 Added loadBalancerLoggingEnabled plugin and spec
  exports.js
  plugins/azure/logalerts/loadBalancerLoggingEnabled.js
  plugins/azure/logalerts/loadBalancerLoggingEnabled.spec.js
Labels: reviewed, Current Release

#1106 Added sqlServerDatabaseLoggingEnabled plugin and spec
  exports.js
  plugins/azure/logalerts/sqlServerDatabaseLoggingEnabled.js
  plugins/azure/logalerts/sqlServerDatabaseLoggingEnabled.spec.js
Labels: reviewed, Current Release

#1107 Added storageAccountLogginEnabled plugin and spec
  exports.js
  plugins/azure/logalerts/storageAccountLoggingEnabled.js
  plugins/azure/logalerts/storageAccountLoggingEnabled.spec.js
Labels: reviewed, Current Release

#1108 Added keyVaults LogginEnabled plugin and spec
  exports.js
  plugins/azure/logalerts/keyVaultsLoggingEnabled.js
  plugins/azure/logalerts/keyVaultsLoggingEnabled.spec.js
Labels: reviewed, Current Release

#1172 SAAS-4259: Added DynamoDB Table Backup Exists Plugin
  collectors/aws/collector.js
  collectors/aws/dynamodb/listBackups.js
  exports.js
  plugins/aws/dynamodb/dynamoTableBackupExists.js
  plugins/aws/dynamodb/dynamoTableBackupExists.spec.js
Labels: reviewed, Current Release

#1103 SAAS-3834: Added AWS Config Referencing Missing S3 Bucket Plugin
  collectors/aws/collector.js
  exports.js
  plugins/aws/configservice/configServiceMissingBucket.js
  plugins/aws/configservice/configServiceMissingBucket.spec.js
Labels: reviewed, Current Release

#1090 SAAS-3780: Added Enable Access Logging For App Mesh Virtual Gateways Plugin
  exports.js
  helpers/aws/regions.js
  plugins/aws/appmesh/appmeshVGAccessLogging.js
  plugins/aws/appmesh/appmeshVGAccessLogging.spec.js
Labels: reviewed, Current Release

#1091 SAAS-3794: Added App Mesh Restrict External Traffic Plugin
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/appmesh/restrictExternalTraffic.js
  plugins/aws/appmesh/restrictExternalTraffic.spec.js
Labels: reviewed, initial review, Current Release

#867 SAAS-2420: Plugin to check that elastiCache not using default ports
  exports.js
  plugins/aws/elasticache/elasticacheDefaultPorts.js
  plugins/aws/elasticache/elasticacheDefaultPorts.spec.js
Labels: reviewed, Current Release

#1171 SAAS-4257: Added ACM Single Domain Name Certificates Plugin
  exports.js
  plugins/aws/acm/acmSingleDomainNameCertificate.js
  plugins/aws/acm/acmSingleDomainNameCertificate.spec.js
Labels: Current Release

#1169 SAAS-4255: Added API Stage-Level Cache Encryption Plugin
  exports.js
  plugins/aws/apigateway/apiStageLevelCacheEncryption.js
  plugins/aws/apigateway/apiStageLevelCacheEncryption.spec.js
Labels: reviewed, Current Release

#1170 SAAS-4256: Added API Gateway Response Caching Plugin
  exports.js
  plugins/aws/apigateway/apigatewayResponseCaching.js
  plugins/aws/apigateway/apigatewayResponseCaching.spec.js
Labels: reviewed, Current Release

#1089 SAAS-3765: Added SNS Appropriate Subscribers Plugin
  collectors/aws/collector.js
  exports.js
  plugins/aws/sns/snsValidSubscribers.js
  plugins/aws/sns/snsValidSubscribers.spec.js
Labels: reviewed, Current Release

#1104 SAAS-3837: Added AWS Config Delivery Failing Plugin
  exports.js
  plugins/aws/configservice/configDeliveryFailing.js
  plugins/aws/configservice/configDeliveryFailing.spec.js
Labels: reviewed, initial review, Current Release

#1109 SAAS-3847: Added AWS Backup Compliant Lifecycle Configured Plugin
  collectors/aws/collector.js
  exports.js
  plugins/aws/backup/compliantLifecyleConfigured.js
  plugins/aws/backup/compliantLifecyleConfigured.spec.js
Labels: question, Current Release

#1174 SAAS-4274: Added Config Complaint Rules Plugin
  collectors/aws/collector.js
  exports.js
  plugins/aws/configservice/configComplaintRules.js
  plugins/aws/configservice/configComplaintRules.spec.js
Labels: reviewed, Current Release

#1113 SAAS-3862: Added AWS Backup Deletion Protection Enabled Plugin
  collectors/aws/collector.js
  exports.js
  plugins/aws/backup/backupDeletionProtection.js
  plugins/aws/backup/backupDeletionProtection.spec.js
Labels: reviewed, Current Release

#1114 SAAS-3877: Added AWS Backup Notification Enabled Plugin
  collectors/aws/collector.js
  exports.js
  plugins/aws/backup/backupNotificationEnabled.js
  plugins/aws/backup/backupNotificationEnabled.spec.js
Labels: reviewed, Current Release

#1117 SAAS-3890: Added AWS CloudFront In Use Plugin
  exports.js
  plugins/aws/cloudfront/cloudfrontInUse.js
  plugins/aws/cloudfront/cloudfrontInUse.spec.js
Labels: reviewed, Current Release

#1115 SAAS-3878: Added AWS Backup In Use For RDS Snapshots Plugin
  exports.js
  plugins/aws/backup/backupInUseForRDSSnapshots.js
  plugins/aws/backup/backupInUseForRDSSnapshots.spec.js
Labels: reviewed, Current Release

#1120 SAAS-3898: Added AWS CloudFront Distribution Field-Level Encryption Plugin
  exports.js
  plugins/aws/cloudfront/cloudfrontFieldLevelEncryption.js
  plugins/aws/cloudfront/cloudfrontFieldLevelEncryption.spec.js
Labels: reviewed, Current Release

#1135 SAAS-4050: Added AWS EventBridge Events In Use Plugin
  collectors/aws/collector.js
  exports.js
  plugins/aws/eventbridge/eventsInUse.js
  plugins/aws/eventbridge/eventsInUse.spec.js
Labels: reviewed, initial review, Current Release

#1131 SAAS-3922: Added CloudTrail Notifications Enabled Plugin
  exports.js
  plugins/aws/cloudtrail/cloudtrailNotificationsEnabled.js
  plugins/aws/cloudtrail/cloudtrailNotificationsEnabled.spec.js
Labels: reviewed, initial review, Current Release

#1134 SAAS-4035: Added Event Bus Public Access Plugin
  exports.js
  plugins/aws/eventbridge/eventBusPublicAccess.js
  plugins/aws/eventbridge/eventBusPublicAccess.spec.js
Labels: reviewed, initial review, Current Release

#1138 SAAS-4064: Added CloudFormation Admin Priviliges Plugin
  exports.js
  plugins/aws/cloudformation/cloudformationAdminPriviliges.js
  plugins/aws/cloudformation/cloudformationAdminPriviliges.spec.js
Labels: reviewed, Current Release

#1162 SAAS-4146: Added VPC Flow Logs Metric Alarm Plugin
  collectors/aws/collector.js
  exports.js
  plugins/aws/cloudwatch/vpcFlowLogsMetricAlarm.js
  plugins/aws/cloudwatch/vpcFlowLogsMetricAlarm.spec.js
Labels: reviewed, Current Release

#1006 SAAS-3133: Added MSK Encryption In Transit Plugin
  exports.js
  plugins/aws/msk/mskClusterEncryptionInTransit.js
  plugins/aws/msk/mskClusterEncryptionInTransit.spec.js
Labels: reviewed, Current Release
