Repository aquasecurity/cloudsploit, pull requests merged in 2022-11, with the labels that each got.

#1421 plugin dev for snapshot have tags
  exports.js
  plugins/aws/ec2/ebsSnapshotHasTags.js
  plugins/aws/ec2/ebsSnapshotHasTags.spec.js
Labels: readytogo, reviewed, Current Release

#1438 SAAS-10111: GCP - Dataproc Cluster Labels Added Plugin
  collectors/google/collector.js
  exports.js
  helpers/google/regions.js
  plugins/google/compute/autoscaleEnabled.js
  plugins/google/compute/autoscaleEnabled.spec.js
  plugins/google/compute/autoscaleMinCpuUtilization.js
  plugins/google/dataproc/dataprocClusterLabelsAdded.js
  plugins/google/dataproc/dataprocClusterLabelsAdded.spec.js
  plugins/google/kubernetes/aliasIpRangesEnabled.js
  plugins/google/kubernetes/aliasIpRangesEnabled.spec.js
  plugins/google/kubernetes/autoNodeRepairEnabled.js
  plugins/google/kubernetes/autoNodeRepairEnabled.spec.js
  plugins/google/kubernetes/autoNodeUpgradesEnabled.js
  plugins/google/kubernetes/autoNodeUpgradesEnabled.spec.js
  plugins/google/kubernetes/basicAuthenticationDisabled.js
  plugins/google/kubernetes/basicAuthenticationDisabled.spec.js
  plugins/google/kubernetes/clusterEncryption.js
  plugins/google/kubernetes/clusterEncryption.spec.js
  plugins/google/kubernetes/clusterLabelsAdded.js
  plugins/google/kubernetes/clusterLabelsAdded.spec.js
  plugins/google/kubernetes/clusterLeastPrivilege.js
  plugins/google/kubernetes/clusterLeastPrivilege.spec.js
  plugins/google/kubernetes/cosImageEnabled.js
  plugins/google/kubernetes/cosImageEnabled.spec.js
  plugins/google/kubernetes/defaultServiceAccount.js
  plugins/google/kubernetes/defaultServiceAccount.spec.js
  plugins/google/kubernetes/integrityMonitoringEnabled.js
  plugins/google/kubernetes/integrityMonitoringEnabled.spec.js
  plugins/google/kubernetes/kubernetesAlphaDisabled.js
  plugins/google/kubernetes/kubernetesAlphaDisabled.spec.js
  plugins/google/kubernetes/legacyAuthorizationDisabled.js
  plugins/google/kubernetes/legacyAuthorizationDisabled.spec.js
  plugins/google/kubernetes/loggingEnabled.js
  plugins/google/kubernetes/loggingEnabled.spec.js
  plugins/google/kubernetes/masterAuthorizedNetwork.js
  plugins/google/kubernetes/masterAuthorizedNetwork.spec.js
  plugins/google/kubernetes/monitoringEnabled.js
  plugins/google/kubernetes/monitoringEnabled.spec.js
  plugins/google/kubernetes/networkPolicyEnabled.js
  plugins/google/kubernetes/networkPolicyEnabled.spec.js
  plugins/google/kubernetes/nodeEncryption.js
  plugins/google/kubernetes/nodeEncryption.spec.js
  plugins/google/kubernetes/podSecurityPolicyEnabled.js
  plugins/google/kubernetes/podSecurityPolicyEnabled.spec.js
  plugins/google/kubernetes/privateClusterEnabled.js
  plugins/google/kubernetes/privateClusterEnabled.spec.js
  plugins/google/kubernetes/privateEndpoint.js
  plugins/google/kubernetes/privateEndpoint.spec.js
  plugins/google/kubernetes/secureBootEnabled.js
  plugins/google/kubernetes/secureBootEnabled.spec.js
  plugins/google/kubernetes/shieldedNodes.js
  plugins/google/kubernetes/shieldedNodes.spec.js
  plugins/google/kubernetes/webDashboardDisabled.js
  plugins/google/kubernetes/webDashboardDisabled.spec.js
Labels: readytogo, reviewed, Current Release

#1439 SAAS-10147: GCP Dataproc Cluster Encryption Plugin
  exports.js
  plugins/google/dataproc/dataprocClusterEncryption.js
  plugins/google/dataproc/dataprocClusterEncryption.spec.js
Labels: readytogo, reviewed, Current Release

#1441 SAAS-10148: GCP - Hadoop Secure Mode Enabled Plugin
  exports.js
  plugins/google/dataproc/hadoopSecureModeEnabled.js
  plugins/google/dataproc/hadoopSecureModeEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1429 Feature/saas 9815 aws ensure that cognito have m
  exports.js
  helpers/aws/api.js
  helpers/aws/api_multipart.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/cognito/cognitoMFAEnabled.js
  plugins/aws/cognito/cognitoMFAEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1430 Feature/saas 9853 aws cognito user pool have waf
  collectors/aws/wafv2/getWebACLForCognitoUserPool.js
  exports.js
  helpers/aws/api.js
  helpers/aws/api_multipart.js
  plugins/aws/cognito/cognitoHasWafEnabled.js
  plugins/aws/cognito/cognitoHasWafEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1431 Updated api for docdb
  helpers/aws/api.js
  helpers/aws/api_multipart.js
Labels: enhancement, readytogo, Current Release

#1442 SAAS-9740: fixed-iam-sshKeysRotated
  plugins/aws/iam/sshKeysRotated.js
  plugins/aws/iam/sshKeysRotated.spec.js
Labels: enhancement, readytogo, Current Release

#1437 Added New GCP regions
  helpers/google/regions.js
  plugins/google/compute/instanceMaxCount.js
Labels: enhancement, readytogo, Current Release

#1428 SAAS - 9799: added new settings to ignore iam roles on tag basis
  plugins/aws/iam/iamMasterManagerRoles.js
  plugins/aws/iam/iamMasterManagerRoles.spec.js
  plugins/aws/iam/iamRoleLastUsed.js
  plugins/aws/iam/iamRoleLastUsed.spec.js
  plugins/aws/iam/iamRolePolicies.js
  plugins/aws/iam/iamRolePolicies.spec.js
  plugins/aws/iam/rolePolicyUnusedServices.js
  plugins/aws/iam/rolePolicyUnusedServices.spec.js
Labels: enhancement, readytogo, Current Release

#1433 refactoring
  plugins/aws/eks/eksKubernetesVersion.js
  plugins/aws/eks/eksLatestPlatformVersion.js
  plugins/aws/eks/eksLatestPlatformVersion.spec.js
  plugins/aws/lambda/lambdaOldRuntimes.js
Labels: enhancement, readytogo, Current Release

#1435 Feature/aws periodic region updates
  helpers/aws/regions.js
  plugins/aws/ec2/instanceMaxCount.js
Labels: enhancement, readytogo, Current Release

#1454 modified logic
  plugins/azure/keyvaults/keyVaultInUse.js
Labels: enhancement, readytogo, Current Release

#1457 api-gateway-plugins
  exports.js
  helpers/aws/api.js
  helpers/aws/api_multipart.js
  plugins/aws/apigateway/apigatewayDefaultEndpointDisabled.js
  plugins/aws/apigateway/apigatewayDefaultEndpointDisabled.spec.js
  plugins/aws/apigateway/customDomainTlsVersion.js
  plugins/aws/apigateway/customDomainTlsVersion.spec.js
Labels: readytogo, reviewed

#1461 Elbv2-Insecure Ciphers
  exports.js
  plugins/aws/elbv2/elbv2InsecureCiphers.js
  plugins/aws/elbv2/elbv2InsecureCiphers.spec.js
Labels: readytogo, reviewed

#1460 Elbv2-Deprecated SSL policies
  exports.js
  plugins/aws/elbv2/elbv2DeprecatedSslPolicies.js
  plugins/aws/elbv2/elbv2DeprecatedSslPolicies.spec.js
Labels: readytogo, reviewed

#1463 Feature/saas 10408 aws cloudfront tls deprecated
  exports.js
  plugins/aws/cloudfront/cloudfrontTlsDeprecatedProtocols.js
  plugins/aws/cloudfront/cloudfrontTlsDeprecatedProtocols.spec.js
Labels: readytogo, reviewed
