Repository aquasecurity/cloudsploit, pull requests merged in 2022-02, with the labels that each got.

#1072 SAAS-3704: Added CloudFront Compress Objects Automatically Plugin
  exports.js
  plugins/aws/cloudfront/compressObjectsAutomatically.js
  plugins/aws/cloudfront/compressObjectsAutomatically.spec.js
Labels: reviewed

#1073 SAAS-3706: Added CloudFront Geo Restriction Enabled Plugin
  exports.js
  plugins/aws/cloudfront/cloudfrontGeoRestriction.js
  plugins/aws/cloudfront/cloudfrontGeoRestriction.spec.js
Labels: reviewed

#1086 SAAS-3713: Added DMS Auto Minor Version Upgrade Plugin
  exports.js
  plugins/aws/dms/autoMinorVersionUpgrade.js
  plugins/aws/dms/autoMinorVersionUpgrade.spec.js
Labels: reviewed

#1074 SAAS-3707: Added CloudFront Origin Failover Enabled Plugin
  exports.js
  plugins/aws/cloudfront/enableOriginFailOver.js
  plugins/aws/cloudfront/enableOriginFailOver.spec.js
Labels: reviewed

#1087 SAAS-3760: Added DMS Multi-AZ Feature Enabled Plugin
  exports.js
  plugins/aws/dms/dmsMultiAZFeatureEnabled.js
  plugins/aws/dms/dmsMultiAZFeatureEnabled.spec.js
Labels: reviewed

#1070 SAAS-3397: Added SageMaker Notebook Instances in VPC plugin
  exports.js
  plugins/aws/sagemaker/notebookInstanceInVpc.js
  plugins/aws/sagemaker/notebookInstanceInVpc.spec.js
Labels: readytogo, reviewed

#1088 SAAS-3762: Added DMS Publicly Accessible Instances Plugin
  exports.js
  plugins/aws/dms/dmsPubliclyAccessibleInstances.js
  plugins/aws/dms/dmsPubliclyAccessibleInstances.spec.js
Labels: reviewed

#1100 SAAS/3801: Added specs for Azure logAlerts plugins
  plugins/azure/logalerts/nsgLoggingEnabled.spec.js
  plugins/azure/logalerts/securityPolicyAlertsEnabled.spec.js
  plugins/azure/logalerts/securitySolutionLogging.spec.js
  plugins/azure/logalerts/sqlServerFirewallRuleEnabled.spec.js
  plugins/azure/logalerts/virtualNetworkRuleEnabled.spec.js
Labels: reviewed

#1065 SAAS/3377: Added secretsManagerInUse plugin and spec
  exports.js
  plugins/aws/secretsmanager/secretsManagerInUse.js
  plugins/aws/secretsmanager/secretsManagerInUse.spec.js
Labels: reviewed

#1050 SAAS-3259: Added fraudDetectorDataEncrypted plugin and spec
  collectors/aws/collector.js
  exports.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  plugins/aws/frauddetector/fraudDetectorDataEncrypted.js
  plugins/aws/frauddetector/fraudDetectorDataEncrypted.spec.js
Labels: reviewed

#1124 SLK-45885: Added EC2 Unused Security Groups Plugin
  exports.js
  plugins/aws/ec2/unusedSecurityGroups.js
  plugins/aws/ec2/unusedSecurityGroups.spec.js
Labels: question

#1125 Changed plugin title
  plugins/aws/firehose/deliveryStreamEncrypted.js
Labels: hotfix

#1132 SAAS-4009: Added Modify Open Ports Plugin
  helpers/aws/functions.js
  plugins/aws/ec2/openAllPortsProtocols.js
  plugins/aws/ec2/openAllPortsProtocols.spec.js
  plugins/aws/ec2/openCustomPorts.spec.js
  plugins/aws/ec2/openDNS.spec.js
  plugins/aws/ec2/openDocker.spec.js
  plugins/aws/ec2/openElasticsearch.spec.js
  plugins/aws/ec2/openFTP.spec.js
  plugins/aws/ec2/openHadoopNameNode.spec.js
  plugins/aws/ec2/openHadoopNameNodeWebUI.spec.js
  plugins/aws/ec2/openKibana.spec.js
  plugins/aws/ec2/openMySQL.spec.js
  plugins/aws/ec2/openNetBIOS.spec.js
  plugins/aws/ec2/openOracle.spec.js
  plugins/aws/ec2/openOracleAutoDataWarehouse.spec.js
  plugins/aws/ec2/openPostgreSQL.spec.js
  plugins/aws/ec2/openRDP.spec.js
  plugins/aws/ec2/openRPC.spec.js
  plugins/aws/ec2/openSMBoTCP.spec.js
  plugins/aws/ec2/openSMTP.spec.js
  plugins/aws/ec2/openSQLServer.spec.js
  plugins/aws/ec2/openSSH.spec.js
  plugins/aws/ec2/openSalt.spec.js
  plugins/aws/ec2/openTelnet.spec.js
  plugins/aws/ec2/openVNCClient.spec.js
  plugins/aws/ec2/openVNCServer.spec.js
Labels: enhancement, reviewed
