Repository aquasecurity/cloudsploit, pull requests merged in 2022-01, with the labels that each got.

#1071 SAAS/3701: App Service Access Restriction remediated
  plugins/azure/appservice/appServiceAccessRestriction.js
Labels: remediation

#1069 SAAS-3699: Network Access Default Action remediated
  plugins/azure/storageaccounts/networkAccessDefaultAction.js
Labels: remediation

#1068 SAAS-3578: Blob Containers Private Access remediated
  plugins/azure/blobservice/blobContainersPrivateAccess.js
Labels: remediation

#1064 SAAS-3564: TLS Version Check remediated
  plugins/azure/appservice/tlsVersionCheck.js
Labels: readytogo, remediation

#1063 SAAS-3563: Storage Account TLS Version remediated
  plugins/azure/storageaccounts/storageAccountsTlsVersion.js
Labels: readytogo, remediation

#860 SAAS-1120: S3 Bucket All Users Policy, S3 Bucket All Users ACL remediated
  plugins/aws/s3/bucketAllUsersAcl.js
  plugins/aws/s3/bucketAllUsersPolicy.js
Labels: readytogo, remediation

#1048 SLK-43687: Added setting to only WARN federated users
  plugins/oracle/identity/usersMfaEnabled.js
  plugins/oracle/identity/usersMfaEnabled.spec.js
Labels: enhancement, readytogo

#1080 Added jitter code in new custom collectrs
  collectors/aws/cloudwatch/getEcMetricStatistics.js
  collectors/aws/guardduty/describePublishingDestination.js
  collectors/aws/guardduty/getFindings.js
  collectors/aws/guardduty/listFindings.js
  collectors/aws/guardduty/listPublishingDestinations.js
  collectors/aws/kms/listGrants.js
  collectors/aws/lexmodelsv2/describeBotAlias.js
  collectors/aws/lookoutvision/describeModel.js
Labels: enhancement

#1049 SLK-43946: Fixed issues in logging plugins
  plugins/google/logging/projectOwnershipLogging.js
  plugins/google/logging/projectOwnershipLogging.spec.js
  plugins/google/logging/sqlConfigurationLogging.js
  plugins/google/logging/sqlConfigurationLogging.spec.js
  plugins/google/logging/storagePermissionsLogging.js
  plugins/google/logging/storagePermissionsLogging.spec.js
  plugins/google/logging/vpcFirewallRuleLogging.js
  plugins/google/logging/vpcFirewallRuleLogging.spec.js
  plugins/google/logging/vpcNetworkLogging.js
  plugins/google/logging/vpcNetworkLogging.spec.js
  plugins/google/logging/vpcNetworkRouteLogging.js
  plugins/google/logging/vpcNetworkRouteLogging.spec.js
Labels: enhancement, hotfix

#1004 SAAS-3137: Added ElastiCache Cluster In VPC Plugin
  exports.js
  plugins/aws/elasticache/elasticacheClusterInVpc.js
  plugins/aws/elasticache/elasticacheClusterInVpc.spec.js
Labels: reviewed

#1005 SAAS-3138: Added ElastiCache Desired Node Type Plugin
  exports.js
  plugins/aws/elasticache/elasticaheDesiredNodeType.js
  plugins/aws/elasticache/elasticaheDesiredNodeType.spec.js
Labels: reviewed

#951 SAAS-2968: Added EMR Cluster In VPC
  exports.js
  plugins/aws/emr/emrClusterInVPC.js
  plugins/aws/emr/emrClusterInVPC.spec.js
Labels: reviewed

#1011 SAAS-2975: Added EMR Desired Instance Type Plugin
  exports.js
  package.json
  plugins/aws/emr/emrDesiredInstanceType.js
  plugins/aws/emr/emrDesiredInstanceType.spec.js
Labels: reviewed

#1058 SAAS-3533: Added Spec File For ELBV2 WAF Enabled Plugin
  plugins/aws/elbv2/elbv2WafEnabled.spec.js
Labels: reviewed

#1053 SAAS-3531: Added ELBV2 HTTPS-only Spec File
  plugins/aws/elbv2/elbv2HttpsOnly.spec.js
Labels: enhancement, reviewed

#1054 SAAS-3532: Added ELBV2 Logging Enabled Spec File
  plugins/aws/elbv2/elbv2LoggingEnabled.spec.js
Labels: enhancement, reviewed

#1056 SAAS-3537: Added KMS Scheduled Deletion Spec File
  plugins/aws/kms/kmsScheduledDeletion.spec.js
Labels: enhancement, reviewed

#1059 SAAS-3542: Added SQS Encryption Enabled Plugin
  exports.js
  plugins/aws/sqs/sqsEncryptionEnabled.js
  plugins/aws/sqs/sqsEncryptionEnabled.spec.js
Labels: reviewed

#1060 SAAS-3547: Added Kinesis Data Stream Encryption Enabled Plugin
  exports.js
  plugins/aws/kinesis/kinesisDataStreamsEncrypted.js
  plugins/aws/kinesis/kinesisDataStreamsEncrypted.spec.js
Labels: reviewed

#1123 Saas/3758
  collectors/oracle/collector.js
  plugins/oracle/identity/userAPIKeysRotated.js
Labels: hotfix

#1061 SAAS-3549: Added Firehose Delivery Stream Encryption Enabled Plugin
  exports.js
  plugins/aws/firehose/deliveryStreamEncrypted.js
  plugins/aws/firehose/deliveryStreamEncrypted.spec.js
Labels: reviewed
