Repository aquasecurity/cloudsploit, pull requests merged in 2023-03, with the labels that each got.

#1570 SAAS-14235: GCP - Trigger Has Tags
  exports.js
  helpers/google/api.js
  helpers/google/index.js
  helpers/google/regions.js
  plugins/google/cloudbuild/commentControlEnabled.js
  plugins/google/cloudbuild/commentControlEnabled.spec.js
  plugins/google/cloudbuild/triggerHasTags.js
  plugins/google/cloudbuild/triggerHasTags.spec.js
Labels: readytogo, reviewed, Current Release

#1567 SAAS-14229: GCP - Comment Control Enabled
  exports.js
  helpers/google/api.js
  helpers/google/index.js
  helpers/google/regions.js
  plugins/google/cloudbuild/commentControlEnabled.js
  plugins/google/cloudbuild/commentControlEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1569 SAAS-14232: GCP - Specific Source Branch
  exports.js
  plugins/google/cloudbuild/specificSourceBranch.js
  plugins/google/cloudbuild/specificSourceBranch.spec.js
Labels: readytogo, reviewed, Current Release

#1565 SAAS-14203: GCP - Function All Users Policy
  exports.js
  helpers/google/api.js
  plugins/google/cloudfunctions/functionAllUsersPolicy.js
  plugins/google/cloudfunctions/functionAllUsersPolicy.spec.js
Labels: readytogo, reviewed, Current Release

#1564 SAAS-14202: GCP - Topic All Users Policy
  exports.js
  helpers/google/api.js
  plugins/google/pubsub/topicAllUsersPolicy.js
  plugins/google/pubsub/topicAllUsersPolicy.spec.js
Labels: readytogo, reviewed, Current Release

#1559 SAAS-14197: GCP - Images CMK Encrypted
  exports.js
  plugins/google/compute/imagesCMKEncrypted.js
  plugins/google/compute/imagesCMKEncrypted.spec.js
Labels: readytogo, reviewed, Current Release

#1560 SAAS-14198: GCP - Binary Authorization Enabled
  exports.js
  plugins/google/kubernetes/binaryAuthorizationEnabled.js
  plugins/google/kubernetes/binaryAuthorizationEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1549 open https aws
  exports.js
  plugins/aws/ec2/openHTTPS.js
  plugins/aws/ec2/openHTTPS.spec.js
Labels: readytogo, reviewed, Current Release

#1554 unique execution role
  exports.js
  plugins/aws/lambda/lambdaUniqueExecutionRole.js
  plugins/aws/lambda/lambdaUniqueExecutionRole.spec.js
Labels: readytogo, reviewed, Current Release

#1557 plugin iam user without permission
  exports.js
  plugins/aws/iam/iamUserWithoutPermissions.js
  plugins/aws/iam/iamUserWithoutPermissions.spec.js
Labels: readytogo, reviewed, Current Release

#1573 Feature/saas 14060 aws ecs cluster should have active services
  exports.js
  plugins/aws/ecs/ecsClusterActiveService.js
  plugins/aws/ecs/ecsClusterActiveService.spec.js
Labels: readytogo, reviewed, Current Release

#1551 deafult security group ec2
  exports.js
  plugins/aws/ec2/defaultSecurityGroupInUse.js
  plugins/aws/ec2/defaultSecurityGroupInUse.spec.js
Labels: readytogo, reviewed, Current Release

#1572 plugin service with running task
  exports.js
  plugins/aws/ecs/ecsClusterWithActiveTask.js
  plugins/aws/ecs/ecsClusterWithActiveTask.spec.js
Labels: readytogo, reviewed, Current Release

#1550 Feature/saas 13820 aws ensure no security groups allow egress to 0 0 0 0 0
  exports.js
  plugins/aws/ec2/openAllPortsProtocolsEgress.js
  plugins/aws/ec2/openAllPortsProtocolsEgress.spec.js
Labels: readytogo, reviewed, Current Release

#1556 oracle new port
  plugins/aws/ec2/openOracle.js
Labels: enhancement, readytogo, reviewed, Current Release

#1561 SAAS-14201: Added port 2483 to Open Oracle Plugins
  plugins/alibaba/ecs/openOracle.js
  plugins/aws/ec2/openOracle.js
  plugins/azure/networksecuritygroups/openOracle.js
  plugins/google/vpcnetwork/openOracle.js
  plugins/oracle/networking/openOracle.js
  plugins/oracle/networking/openOracle.spec.js
Labels: enhancement, readytogo, reviewed

#1548 AWS new regions
  helpers/aws/regions.js
  plugins/aws/ec2/instanceMaxCount.js
Labels: enhancement, readytogo, reviewed, Current Release

#1563 Java latest version plugin app service updated
  plugins/azure/appservice/javaVersion.js
  plugins/azure/appservice/javaVersion.spec.js
Labels: enhancement, readytogo, reviewed, Current Release

#1562 Feature/saas 14199 aws ensures the latest version of php is installed for all app services
  plugins/azure/appservice/phpVersion.js
  plugins/azure/appservice/phpVersion.spec.js
Labels: enhancement, readytogo, reviewed, Current Release

#1580 updated the logic
  plugins/aws/iam/iamRolePolicies.js
  plugins/aws/iam/iamRolePolicies.spec.js
Labels: enhancement, readytogo, reviewed, Current Release
