Repository aquasecurity/cloudsploit, pull requests merged in 2023-06, with the labels that each got.

#1612 SAAS-15384: GCP - Pub/Sub Admin Plugin
  exports.js
  helpers/google/functions.js
  plugins/google/iam/bigtableAdmin.js
  plugins/google/iam/bigtableAdmin.spec.js
  plugins/google/iam/pubsubAdmin.js
  plugins/google/iam/pubsubAdmin.spec.js
Labels: readytogo, reviewed, currentrelease

#1610 SAAS-15379: GCP - Bigtable Admin Plugin
  exports.js
  helpers/google/functions.js
  plugins/google/iam/bigtableAdmin.js
  plugins/google/iam/bigtableAdmin.spec.js
Labels: readytogo, reviewed, currentrelease

#1611 SAAS-15383: GCP - BigQuery Admin Plugin
  exports.js
  plugins/google/iam/bigqueryAdmin.js
  plugins/google/iam/bigqueryAdmin.spec.js
Labels: readytogo, reviewed, currentrelease

#1632 system identity enabled
  exports.js
  plugins/azure/virtualmachines/systemAssignedIdentityEnabled.js
  plugins/azure/virtualmachines/systemAssignedIdentityEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1651 guardduty S3 protection enabled
  exports.js
  plugins/aws/guardduty/s3ProtectionEnabled.js
  plugins/aws/guardduty/s3ProtectionEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1643 plugin to check if the scan on push is enable for the ecr repository
  exports.js
  plugins/aws/ecr/ecrImageVulnerability.js
  plugins/aws/ecr/ecrImageVulnerability.spec.js
Labels: readytogo, reviewed, currentrelease

#1642 EMR cluster has tags
  exports.js
  plugins/aws/emr/emrClusterHasTags.js
  plugins/aws/emr/emrClusterHasTags.spec.js
Labels: readytogo, reviewed, currentrelease

#1641 plugin/elbv2 has unhealthy instance
  exports.js
  plugins/aws/elbv2/elbv2UnhealthyInstance.js
  plugins/aws/elbv2/elbv2UnhealthyInstance.spec.js
Labels: readytogo, reviewed, currentrelease

#1640 plugin/EBS volume recent snapshot
  exports.js
  plugins/aws/ec2/ebsRecentSnapshots.js
  plugins/aws/ec2/ebsRecentSnapshots.spec.js
Labels: readytogo, reviewed, currentrelease

#1639 RDS instance generation of ec2
  exports.js
  plugins/aws/rds/rdsInstanceGeneration.js
  plugins/aws/rds/rdsInstanceGeneration.spec.js
Labels: readytogo, reviewed, currentrelease

#1635 plugin/sns Subcription HTTPS only
  exports.js
  plugins/aws/sns/snsSubscriptionHTTPSonly.js
  plugins/aws/sns/snsSubscriptionHTTPSonly.spec.js
Labels: readytogo, reviewed, currentrelease

#1624 plugin/opensearchVersionCheck
  exports.js
  plugins/aws/opensearch/opensearchVersion.js
  plugins/aws/opensearch/opensearchVersion.spec.js
Labels: readytogo, reviewed, currentrelease

#1652 fixed the spec file of ebsRecentSnapshots
  plugins/aws/ec2/ebsRecentSnapshots.spec.js
Labels: readytogo, reviewed, hotfix

#1630 subscription has tags
  collectors/azure/collector.js
  exports.js
  helpers/azure/api.js
  plugins/azure/subscription/subscriptionHasTags.js
  plugins/azure/subscription/subscriptionHasTags.spec.js
Labels: readytogo, reviewed, currentrelease

#1636 Feature/saas 16593 azure azure recovery services vaults should use customer managed keys for encrypting backup data
  exports.js
  helpers/azure/api.js
  plugins/azure/recoveryService/recoveryVaultByokEncrypted.js
  plugins/azure/recoveryService/recoveryVaultByokEncrypted.spec.js
Labels: question, reviewed, currentrelease

#1650 A SNS topic is not configured to restrict the HTTP protocol
  exports.js
  plugins/aws/sns/snsTopicNoHttpPolicy.js
  plugins/aws/sns/snsTopicNoHttpPolicy.spec.js
Labels: readytogo, reviewed, currentrelease

#1613 Feature/saas 15348 azure ensure that enable infrastructure encryption for each storage account in azure storage is set to enabled
  exports.js
  plugins/azure/storageaccounts/infrastructureEncryption.js
  plugins/azure/storageaccounts/infrastructureEncryption.spec.js
Labels: readytogo, reviewed, currentrelease

#1633 acr cmk enabled
  exports.js
  helpers/azure/api.js
  plugins/azure/containerregistry/acrCMKEncryption.js
  plugins/azure/containerregistry/acrCMKEncryption.spec.js
Labels: readytogo, reviewed, currentrelease

#1634 elb Unhealthy Instances
  collectors/aws/elb/describeInstanceHealth.js
  exports.js
  helpers/aws/api.js
  plugins/aws/elb/elbUnhealthyInstances.js
  plugins/aws/elb/elbUnhealthyInstances.spec.js
Labels: readytogo, reviewed, currentrelease

#1627 Apigateway authorization
  exports.js
  helpers/aws/api.js
  plugins/aws/apigateway/apigatewayAuthorization.js
  plugins/aws/apigateway/apigatewayAuthorization.spec.js
Labels: question, reviewed, currentrelease

#1653 fixed the typo mistakes in the plugins
  plugins/alibaba/securitycenter/securityAgentInstalled.js
  plugins/aws/apprunner/serviceEncrypted.js
  plugins/aws/cloudfront/cloudfrontCustomOriginHttpsOnly.spec.js
  plugins/aws/cloudfront/cloudfrontOriginTlsVersion.spec.js
  plugins/aws/cloudfront/cloudfrontTlsDeprecatedProtocols.spec.js
  plugins/aws/cloudfront/cloudfrontTlsInsecureCipher.spec.js
  plugins/aws/cloudfront/cloudfrontWafEnabled.js
  plugins/aws/cloudfront/cloudfrontWafEnabled.spec.js
  plugins/aws/cloudfront/compressObjectsAutomatically.js
  plugins/aws/cloudfront/compressObjectsAutomatically.spec.js
  plugins/aws/connect/instanceCallRecordingEncrypted.js
  plugins/aws/location/geoCollectionDataEncrypted.js
  plugins/aws/managedblockchain/networkMemberDataEncrypted.js
  plugins/aws/mq/mqBrokerEncrypted.js
  plugins/aws/s3/versionedBucketsLC.js
  plugins/azure/activedirectory/appOrgnaizationalDirectoryAccess.js
  plugins/azure/applicationGateway/agWafEnabled.js
  plugins/azure/applicationGateway/agWafEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1629 Feature/saas 16469 azure advanced threat protection enabled for key vault
  exports.js
  plugins/azure/defender/enableDefenderForKeyVaults.js
  plugins/azure/defender/enableDefenderForKeyVaults.spec.js
Labels: readytogo, reviewed, currentrelease

#1618 storage account private endpoint
  exports.js
  plugins/azure/storageaccounts/storageAccountPrivateEndpoint.js
  plugins/azure/storageaccounts/storageAccountPrivateEndpoint.spec.js
Labels: readytogo, reviewed, currentrelease

#1646 plugin to check if ec2 instance have exceeded the alarm threshold for…
  collectors/aws/cloudwatch/getEc2MetricStatistics.js
  exports.js
  helpers/aws/api.js
  helpers/aws/api_multipart.js
  plugins/aws/ec2/overutilizedEC2Instance.js
  plugins/aws/ec2/overutilizedEC2Instance.spec.js
Labels: readytogo, reviewed, currentrelease

#1615 Feature/saas 15381 ensure that SKU basic consumption is not used on artifacts that need to be monitored
  exports.js
  helpers/azure/api.js
  plugins/azure/monitor/monitorResourceSku.js
  plugins/azure/monitor/monitorResourceSku.spec.js
Labels: readytogo, reviewed, currentrelease

#1648 Underutilized redshiftcluster
  collectors/aws/cloudwatch/getredshiftMetricStatistics.js
  exports.js
  helpers/aws/api.js
  helpers/aws/api_multipart.js
  plugins/aws/redshift/underutilizedRedshiftCluster.js
  plugins/aws/redshift/underutilizedRedshiftCluster.spec.js
Labels: question, reviewed, currentrelease

#1614 Feature/ saas 15343 azure ensure an azure bastion host exists
  exports.js
  helpers/azure/api.js
  helpers/azure/locations.js
  plugins/azure/bastion/bastionHostExists.js
  plugins/azure/bastion/bastionHostExists.spec.js
Labels: readytogo, reviewed, currentrelease

#1616 Feature/saas 15344 azure ensure allow access to azure services for postgre sql database server is disabled
  exports.js
  plugins/azure/postgresqlserver/azureServicesAccessDisabled.js
  plugins/azure/postgresqlserver/azureServicesAccessDisabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1617 regions and versions update
  helpers/aws/regions.js
  helpers/azure/locations.js
  plugins/aws/elasticache/redisEngineVersions.js
  plugins/azure/monitor/logProfileArchiveData.spec.js
Labels: enhancement, readytogo, currentrelease

#1622 high severity email
  plugins/azure/securitycenter/highSeverityAlertsEnabled.js
  plugins/azure/securitycenter/highSeverityAlertsEnabled.spec.js
Labels: enhancement, readytogo, currentrelease

#1452 updated-name-compliantLifecycleConfigured
  exports.js
  plugins/aws/backup/compliantLifecycleConfigured.js
  plugins/aws/backup/compliantLifecycleConfigured.spec.js
Labels: enhancement, readytogo, reviewed
