Repository aquasecurity/cloudsploit, pull requests merged in 2023-04, with the labels that each got.

#1589 SAAS-14819: GCP - Service Account Role Plugin
  exports.js
  plugins/google/iam/serviceAccountRole.js
  plugins/google/iam/serviceAccountRole.spec.js
Labels: readytogo, reviewed, currentrelease

#1588 SAAS-14787: GCP - Cloud Function Serverless VPC Access Plugin
  exports.js
  plugins/google/cloudfunctions/serverlessVPCAccess.js
  plugins/google/cloudfunctions/serverlessVPCAccess.spec.js
Labels: readytogo, reviewed, currentrelease

#1586 SAAS-14782: GCP - Instance Default Network Plugin
  exports.js
  plugins/google/vpcnetwork/instanceDefaultNetwork.js
  plugins/google/vpcnetwork/instanceDefaultNetwork.spec.js
Labels: readytogo, reviewed, currentrelease

#1585 SAAS-14748: GCP - Airflow Web Server Public Access Plugin
  exports.js
  helpers/google/api.js
  helpers/google/regions.js
  plugins/google/composer/environmentLabelsAdded.js
  plugins/google/composer/environmentLabelsAdded.spec.js
  plugins/google/composer/webserverPublicAccess.js
  plugins/google/composer/webserverPublicAccess.spec.js
Labels: readytogo, reviewed, currentrelease

#1584 SAAS-14734: GCP - Environment Default Service Account Plugin
  exports.js
  plugins/google/composer/envDefaultServiceAccount.js
  plugins/google/composer/envDefaultServiceAccount.spec.js
Labels: readytogo, reviewed, currentrelease

#1583 SAAS-14733: GCP - Environment Encryption Plugin
  exports.js
  plugins/google/composer/environmentEncryption.js
  plugins/google/composer/environmentEncryption.spec.js
Labels: readytogo, reviewed, currentrelease

#1590 elbv2 cross zone enabled
  exports.js
  plugins/aws/elbv2/elbv2crosszoneLoadBalancing.js
  plugins/aws/elbv2/elbv2crosszoneLoadBalancing.spec.js
Labels: readytogo, reviewed, currentrelease

#1591 dynamo unused tables
  exports.js
  plugins/aws/dynamodb/dynamoUnusedTable.js
  plugins/aws/dynamodb/dynamoUnusedTable.spec.js
Labels: readytogo, reviewed, currentrelease

#1595 plugin default action block wafv2
  collectors/aws/wafv2/getWebACL.js
  exports.js
  helpers/aws/api.js
  helpers/aws/api_multipart.js
  plugins/aws/wafv2/aclRulesDefaultAction.js
  plugins/aws/wafv2/aclRulesDefaultAction.spec.js
Labels: readytogo, reviewed, currentrelease

#1594 backup vault all principle
  exports.js
  plugins/aws/backup/backupVaultPolicies.js
  plugins/aws/backup/backupVaultPolicies.spec.js
Labels: readytogo, reviewed, currentrelease

#1598 Feature/saas 14651 aws ensure that open search encryption at rest using cmk
  collectors/aws/opensearchserverless/getEncryptionSecurityPolicy.js
  collectors/aws/opensearchserverless/listEncryptionSecurityPolicies.js
  exports.js
  helpers/aws/api.js
  helpers/aws/api_multipart.js
  plugins/aws/openSearchServerless/opensearchCollectionCmkEncrypted.js
  plugins/aws/openSearchServerless/opensearchCollectionCmkEncrypted.spec.js
Labels: question, reviewed, currentrelease

#1602 single tenant access
  exports.js
  helpers/azure/api.js
  helpers/azure/auth.js
  helpers/azure/locations.js
  plugins/azure/activedirectory/appOrgnaizationalDirectoryAccess.js
  plugins/azure/activedirectory/appOrgnaizationalDirectoryAccess.spec.js
Labels: readytogo, reviewed
