Repository aquasecurity/cloudsploit, pull requests merged in 2023-12, with the labels that each got.

#1737 SAAS-20313/AFD-Bot-Protection
  exports.js
  helpers/azure/api.js
  helpers/azure/locations.js
  plugins/azure/frontdoor/botProtectionEnabled.js
  plugins/azure/frontdoor/botProtectionEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1745 Azure - Redis Cache Private Endpoint Enabled Plugin
  exports.js
  plugins/azure/redisCache/redisCachePrivateEndpoint.js
  plugins/azure/redisCache/redisCachePrivateEndpoint.spec.js
Labels: readytogo, reviewed, currentrelease

#1749 Azure - Postgres Flexible Server SCRAM Enabled Plugin
  exports.js
  helpers/azure/api.js
  plugins/azure/postgresqlserver/flexibleServerSCRAMEnabled.js
  plugins/azure/postgresqlserver/flexibleServerSCRAMEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1738 SAAS-20313/Front-Door-https-only
  exports.js
  helpers/azure/api.js
  helpers/azure/locations.js
  plugins/azure/frontdoor/frontDoorHttpsOnly.js
  plugins/azure/frontdoor/frontDoorHttpsOnly.spec.js
Labels: readytogo, reviewed, currentrelease

#1760 Azure - Service Bus Namespace Encryption Plugin
  exports.js
  helpers/azure/api.js
  helpers/azure/locations.js
  plugins/azure/servicebus/namespaceEncryptionAtRest.js
  plugins/azure/servicebus/namespaceEncryptionAtRest.spec.js
Labels: readytogo, reviewed, currentrelease

#1739 SAAS-20313/Front-Door-Waf-Enabled
  exports.js
  helpers/azure/api.js
  plugins/azure/frontdoor/frontDoorWafEnabled.js
  plugins/azure/frontdoor/frontDoorWafEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1761 Azure - Service Bus Namespace TLS Version Plugin
  exports.js
  plugins/azure/servicebus/namespaceTlsVersion.js
  plugins/azure/servicebus/namespaceTlsVersion.spec.js
Labels: readytogo, reviewed, currentrelease

#1762 Azure - Service Bus Namespace Local Authentication Plugin
  exports.js
  plugins/azure/servicebus/namespaceLocalAuth.js
  plugins/azure/servicebus/namespaceLocalAuth.spec.js
Labels: readytogo, reviewed, currentrelease

#1763 Azure - Service Bus Namespace Logging Enabled Plugin
  exports.js
  plugins/azure/servicebus/namespaceLoggingEnabled.js
  plugins/azure/servicebus/namespaceLoggingEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1740 SAAS-20313/Front-Door-Request-Body-Inspection
  exports.js
  helpers/azure/api.js
  helpers/azure/locations.js
  plugins/azure/frontdoor/frontDoorRequestBodyInspection.js
  plugins/azure/frontdoor/frontDoorRequestBodyInspection.spec.js
Labels: question, reviewed, currentrelease

#1764 Azure - PostgreSQL Diagnostic Logging Enabled Plugin
  exports.js
  helpers/azure/api.js
  plugins/azure/postgresqlserver/diagnosticLoggingEnabled.js
  plugins/azure/postgresqlserver/diagnosticLoggingEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1791 Azure - PostgreSQL Flexible Server Logging Plugin
  exports.js
  helpers/azure/api.js
  plugins/azure/postgresqlserver/flexibleServerDiagnosticLogs.js
  plugins/azure/postgresqlserver/flexibleServerDiagnosticLogs.spec.js
Labels: readytogo, reviewed, currentrelease

#1742 SAAS-20313/afd-detection-mode
  exports.js
  plugins/azure/frontdoor/frontDoorWafDetectionMode.js
  plugins/azure/frontdoor/frontDoorWafDetectionMode.spec.js
Labels: readytogo, reviewed, currentrelease

#1766 SAAS-20297/ag-Request-body-inspection
  exports.js
  plugins/azure/applicationGateway/agRequestBodyInspection.js
  plugins/azure/applicationGateway/agRequestBodyInspection.spec.js
Labels: readytogo, reviewed, currentrelease

#1785 Bedrock encryption enabled
  exports.js
  helpers/aws/api.js
  helpers/aws/api_multipart.js
  helpers/aws/regions.js
  helpers/aws/regions_china.js
  helpers/aws/regions_gov.js
  helpers/aws/regions_gov_fedramp_east_1.js
  helpers/aws/regions_gov_fedramp_west_1.js
  package.json
  plugins/aws/bedrock/customModelEncryptionEnabled.js
  plugins/aws/bedrock/customModelEncryptionEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1746 SAAS-20313/Front-Door-Waf-Default-Rate-limit
  exports.js
  plugins/azure/frontdoor/frontDoorWafDefaultRateLimit.js
  plugins/azure/frontdoor/frontDoorWafDefaultRateLimit.spec.js
Labels: readytogo, reviewed, currentrelease

#1770 SAAS-20297/ag-ssl-policy
  exports.js
  plugins/azure/applicationGateway/agSslPolicy.js
  plugins/azure/applicationGateway/agSslPolicy.spec.js
Labels: readytogo, reviewed, currentrelease

#1789 SAAS-20297/ag-security-logging
  exports.js
  helpers/azure/api.js
  plugins/azure/applicationGateway/agSecurityLoggingEnabled.js
  plugins/azure/applicationGateway/agSecurityLoggingEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1741 postgresqlServerCMKencrypted
  exports.js
  plugins/azure/postgresqlserver/postgresqlCMKEncrypted.js
  plugins/azure/postgresqlserver/postgresqlCMKEncrypted.spec.js
Labels: readytogo, reviewed, currentrelease

#1736 privateAccessEnabled
  exports.js
  plugins/azure/postgresqlserver/postgresqlPrivateEndpoints.js
  plugins/azure/postgresqlserver/postgresqlPrivateEndpoints.spec.js
Labels: readytogo, reviewed, currentrelease

#1783 Azure/postgresFlexibleServerPrivateAccess
  exports.js
  helpers/azure/api.js
  plugins/azure/postgresqlserver/flexibleServerPrivateAccess.js
  plugins/azure/postgresqlserver/flexibleServerPrivateAccess.spec.js
Labels: readytogo, reviewed, currentrelease

#1786 Bedrock private custom model
  exports.js
  plugins/aws/bedrock/privateCustomModel.js
  plugins/aws/bedrock/privateCustomModel.spec.js
Labels: readytogo, reviewed, currentrelease

#1787 Bedrock model in vpc
  exports.js
  plugins/aws/bedrock/customModelInVpc.js
  plugins/aws/bedrock/customModelInVpc.spec.js
Labels: readytogo, reviewed, currentrelease

#1735 TlsVersionCheck
  exports.js
  plugins/azure/postgresqlserver/postgresqlTlsVersion.js
  plugins/azure/postgresqlserver/postgresqlTlsVersion.spec.js
Labels: readytogo, reviewed, currentrelease

#1782 ams public access disabled
  exports.js
  helpers/azure/api.js
  helpers/azure/locations.js
  plugins/azure/mediaServices/amsPublicAccessDisabled.js
  plugins/azure/mediaServices/amsPublicAccessDisabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1772 added azure vm plugin diskDeleteConfig
  exports.js
  helpers/azure/api.js
  plugins/azure/virtualmachines/vmDiskDeleteConfig.js
  plugins/azure/virtualmachines/vmDiskDeleteConfig.spec.js
Labels: readytogo, reviewed, currentrelease

#1769 added azure vm plugin vmVTPMEnabled
  exports.js
  plugins/azure/virtualmachines/vmVTPMEnabled.js
  plugins/azure/virtualmachines/vmVTPMEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1768 added plugin for azure vm security type check
  exports.js
  plugins/azure/virtualmachines/vmSecurityType.js
  plugins/azure/virtualmachines/vmSecurityType.spec.js
Labels: readytogo, reviewed, currentrelease

#1765 added sql server plugin audit microsoft support operations
  exports.js
  helpers/azure/api.js
  helpers/azure/resources.js
  plugins/azure/sqlserver/auditOperationsEnabled.js
  plugins/azure/sqlserver/auditOperationsEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1758 added sql server plugin restrict outbound networking
  exports.js
  plugins/azure/sqlserver/restrictOutboundNetworking.js
  plugins/azure/sqlserver/restrictOutboundNetworking.spec.js
Labels: readytogo, reviewed, currentrelease

#1751 added sql db data maksing enabled
  exports.js
  helpers/azure/api.js
  helpers/azure/resources.js
  plugins/azure/sqldatabases/dbDataMaskingEnabled.js
  plugins/azure/sqldatabases/dbDataMaskingEnabled.spec.js
Labels: question, reviewed, currentrelease

#1756 added sql db enableSecureEnclaves
  exports.js
  helpers/azure/api.js
  plugins/azure/sqldatabases/dbEnableSecureEnclaves.js
  plugins/azure/sqldatabases/dbEnableSecureEnclaves.spec.js
Labels: readytogo, reviewed, currentrelease

#1779 storage account managed identity enabled
  exports.js
  plugins/azure/mediaServices/amsStorageAccountIdentity.js
  plugins/azure/mediaServices/amsStorageAccountIdentity.spec.js
Labels: readytogo, reviewed, currentrelease

#1757 Feature/saas 20307/sql db ledger enabled
  exports.js
  plugins/azure/sqldatabases/dbLedgerEnabled.js
  plugins/azure/sqldatabases/dbLedgerEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1755 added sql db transparent data encryption enabled
  exports.js
  helpers/azure/api.js
  helpers/azure/resources.js
  plugins/azure/sqldatabases/dbTDEEnabled.js
  plugins/azure/sqldatabases/dbTDEEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1754 added sql db syncGroupPrivateLink
  exports.js
  helpers/azure/api.js
  helpers/azure/resources.js
  plugins/azure/sqldatabases/dbSyncGroupPrivateLink.js
  plugins/azure/sqldatabases/dbSyncGroupPrivateLink.spec.js
Labels: readytogo, reviewed, currentrelease

#1720 added tiggers for p,q,r,w
  plugins/aws/proton/environmentTemplateEncrypted.js
  plugins/aws/qldb/ledgerEncrypted.js
  plugins/aws/rds/iamDbAuthenticationEnabled.js
  plugins/aws/rds/idleRDSInstance.js
  plugins/aws/rds/mysqlVulnerabilityCheck.js
  plugins/aws/rds/overutilizedRDSInstance.js
  plugins/aws/rds/rdsAutomatedBackups.js
  plugins/aws/rds/rdsCmkEncryptionEnabled.js
  plugins/aws/rds/rdsDefaultPort.js
  plugins/aws/rds/rdsDefaultUsername.js
  plugins/aws/rds/rdsDeletionProtectionEnabled.js
  plugins/aws/rds/rdsEncryptionEnabled.js
  plugins/aws/rds/rdsInstanceGeneration.js
  plugins/aws/rds/rdsInstanceHasTags.js
  plugins/aws/rds/rdsLoggingEnabled.js
  plugins/aws/rds/rdsMinorVersionUpgrade.js
  plugins/aws/rds/rdsMultiAz.js
  plugins/aws/rds/rdsPublicSubnet.js
  plugins/aws/rds/rdsPubliclyAccessible.js
  plugins/aws/rds/rdsRestorable.js
  plugins/aws/rds/rdsSnapshotEncryption.js
  plugins/aws/rds/rdsSnapshotPubliclyAccessible.js
  plugins/aws/rds/rdsTransportEncryption.js
  plugins/aws/rds/sqlServerTLSVersion.js
  plugins/aws/redshift/auditLoggingEnabled.js
  plugins/aws/redshift/redshiftAllowVersionUpgrade.js
  plugins/aws/redshift/redshiftClusterCmkEncrypted.js
  plugins/aws/redshift/redshiftClusterDefaultPort.js
  plugins/aws/redshift/redshiftClusterInVpc.js
  plugins/aws/redshift/redshiftClusterMasterUsername.js
  plugins/aws/redshift/redshiftDesiredNodeType.js
  plugins/aws/redshift/redshiftEncryptionEnabled.js
  plugins/aws/redshift/redshiftNodesCount.js
  plugins/aws/redshift/redshiftPubliclyAccessible.js
  plugins/aws/redshift/redshiftSSLEnabled.js
  plugins/aws/redshift/redshiftUnusedReservedNodes.js
  plugins/aws/redshift/snapshotRetentionPeriod.js
  plugins/aws/redshift/underutilizedRedshiftCluster.js
  plugins/aws/redshift/userActivityLoggingEnabled.js
  plugins/aws/route53/danglingDnsRecords.js
  plugins/aws/route53/domainAutoRenew.js
  plugins/aws/route53/domainExpiry.js
  plugins/aws/route53/domainTransferLock.js
  plugins/aws/route53/privacyProtection.js
  plugins/aws/route53/senderPolicyFwInUse.js
  plugins/aws/route53/senderPolicyFwRecordPresent.js
  plugins/aws/waf/wafInUse.js
  plugins/aws/wafv2/aclRulesDefaultAction.js
  plugins/aws/wafv2/wafv2CloudwatchMetricsEnabled.js
  plugins/aws/wafv2/wafv2InUse.js
  plugins/aws/workspaces/unusedWorkspaces.js
  plugins/aws/workspaces/workspacesDesiredBundleType.js
  plugins/aws/workspaces/workspacesInstanceCount.js
  plugins/aws/workspaces/workspacesIpAccessControl.js
  plugins/aws/workspaces/workspacesVolumeEncryption.js
Labels: readytogo, reviewed

#1718 added tiggers for f,g,h and connect
  plugins/aws/connect/customerProfilesDomainEncrypted.js
  plugins/aws/connect/instanceAttachmentsEncrypted.js
  plugins/aws/connect/instanceCallRecordingEncrypted.js
  plugins/aws/connect/instanceMediaStreamsEncrypted.js
  plugins/aws/connect/instanceReportsEncrypted.js
  plugins/aws/connect/instanceTranscriptsEncrypted.js
  plugins/aws/connect/voiceIdDomainEncrypted.js
  plugins/aws/connect/wisdomDomainEncrypted.js
  plugins/aws/finspace/finspaceEnvironmentEncrypted.js
  plugins/aws/firehose/deliveryStreamEncrypted.js
  plugins/aws/firehose/firehoseEncrypted.js
  plugins/aws/forecast/datasetExportEncrypted.js
  plugins/aws/forecast/forecastDatasetEncrypted.js
  plugins/aws/frauddetector/fraudDetectorDataEncrypted.js
  plugins/aws/fsx/fsxFileSystemEncrypted.js
  plugins/aws/glue/bookmarkEncryptionEnabled.js
  plugins/aws/glue/dataCatalogCmkEncrypted.js
  plugins/aws/glue/glueCloudwatchLogsEncrypted.js
  plugins/aws/glue/glueS3EncryptionEnabled.js
  plugins/aws/gluedatabrew/databrewJobOutputEncrypted.js
  plugins/aws/guardduty/exportedFindingsEncrypted.js
  plugins/aws/guardduty/guarddutyEnabled.js
  plugins/aws/guardduty/guarddutyMaster.js
  plugins/aws/guardduty/noActiveFindings.js
  plugins/aws/guardduty/s3ProtectionEnabled.js
  plugins/aws/healthlake/dataStoreEncrypted.js
Labels: readytogo, reviewed

#1719 L m n o tiggers
  plugins/aws/kms/kmsDefaultKeyUsage.js
  plugins/aws/lambda/envVarsClientSideEncryption.js
  plugins/aws/lambda/lambdaAdminPrivileges.js
  plugins/aws/lambda/lambdaHasTags.js
  plugins/aws/lambda/lambdaLogGroups.js
  plugins/aws/lambda/lambdaOldRuntimes.js
  plugins/aws/lambda/lambdaPublicAccess.js
  plugins/aws/lambda/lambdaTracingEnabled.js
  plugins/aws/lambda/lambdaUniqueExecutionRole.js
  plugins/aws/lambda/lambdaVpcConfig.js
  plugins/aws/lex/lexAudioLogsEncrypted.js
  plugins/aws/location/geoCollectionDataEncrypted.js
  plugins/aws/location/trackerDataEncrypted.js
  plugins/aws/lookout/anomalyDetectorEncrypted.js
  plugins/aws/lookout/equipmentdatasetEncrypted.js
  plugins/aws/lookout/modelDataEncrypted.js
  plugins/aws/managedblockchain/networkMemberDataEncrypted.js
  plugins/aws/memorydb/memorydbClusterEncrypted.js
  plugins/aws/mq/mqAutoMinorVersionUpgrade.js
  plugins/aws/mq/mqBrokerEncrypted.js
  plugins/aws/mq/mqBrokerPublicAccess.js
  plugins/aws/mq/mqDeploymentMode.js
  plugins/aws/mq/mqDesiredInstanceType.js
  plugins/aws/mq/mqLatestEngineVersion.js
  plugins/aws/mq/mqLogExports.js
  plugins/aws/msk/mskClusterCBEncryption.js
  plugins/aws/msk/mskClusterEncryptionAtRest.js
  plugins/aws/msk/mskClusterEncryptionInTransit.js
  plugins/aws/msk/mskClusterPublicAccess.js
  plugins/aws/msk/mskClusterUnauthAccess.js
  plugins/aws/mwaa/environmentAdminPrivileges.js
  plugins/aws/mwaa/environmentDataEncrypted.js
  plugins/aws/mwaa/webServerPublicAccess.js
  plugins/aws/neptune/neptuneDBInstanceEncrypted.js
  plugins/aws/openSearchServerless/opensearchCollectionCmkEncrypted.js
  plugins/aws/openSearchServerless/opensearchCollectionPublicAccess.js
  plugins/aws/opensearch/opensearchAccessFromIps.js
  plugins/aws/opensearch/opensearchClusterStatus.js
  plugins/aws/opensearch/opensearchCrossAccountAccess.js
  plugins/aws/opensearch/opensearchDedicatedMasterEnabled.js
  plugins/aws/opensearch/opensearchDesiredInstanceTypes.js
  plugins/aws/opensearch/opensearchDomainEncryptionEnabled.js
  plugins/aws/opensearch/opensearchEncryptedDomain.js
  plugins/aws/opensearch/opensearchExposedDomain.js
  plugins/aws/opensearch/opensearchHttpsOnly.js
  plugins/aws/opensearch/opensearchLoggingEnabled.js
  plugins/aws/opensearch/opensearchNodeToNodeEncryption.js
  plugins/aws/opensearch/opensearchPublicEndpoint.js
  plugins/aws/opensearch/opensearchRequireIAMAuth.js
  plugins/aws/opensearch/opensearchTlsVersion.js
  plugins/aws/opensearch/opensearchUpgradeAvailable.js
  plugins/aws/opensearch/opensearchVersion.js
  plugins/aws/opensearch/opensearchZoneAwarenessEnabled.js
  plugins/aws/organizations/enableAllFeatures.js
  plugins/aws/organizations/organizationInvite.js
Labels: readytogo, reviewed, currentrelease
