Repository aquasecurity/cloudsploit, pull requests merged in 2023-02, with the labels that each got.

#1517 plugin waf policy has tags
  exports.js
  helpers/azure/api.js
  helpers/azure/locations.js
  plugins/azure/waf/wafPolicyHasTags.js
  plugins/azure/waf/wafPolicyHasTags.spec.js
Labels: readytogo, reviewed, Current Release

#1538 plugin snapshot has byok enabled
  exports.js
  plugins/azure/virtualmachines/snapshotByokEncryptionEnabled.js
  plugins/azure/virtualmachines/snapshotByokEncryptionEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1539 Feature/saas 12636 azure ensure waf policy for application gateway is set to prevention mode
  exports.js
  helpers/azure/api.js
  helpers/azure/locations.js
  plugins/azure/applicationGateway/agPreventionModeEnabled.js
  plugins/azure/applicationGateway/agPreventionModeEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1519 acr has tags plugin
  exports.js
  plugins/azure/containerregistry/acrHasTags.js
  plugins/azure/containerregistry/acrHasTags.spec.js
Labels: readytogo, reviewed, Current Release

#1513 plugin RT has tags
  exports.js
  helpers/azure/api.js
  helpers/azure/locations.js
  plugins/azure/virtualnetworks/routeTableHasTags.js
  plugins/azure/virtualnetworks/routeTableHasTags.spec.js
Labels: readytogo, reviewed, Current Release

#1485 plugin dev in progress
  exports.js
  helpers/azure/api.js
  helpers/azure/locations.js
  plugins/azure/virtualmachines/vmImageHasTags.js
  plugins/azure/virtualmachines/vmImageHasTags.spec.js
Labels: readytogo, reviewed, Current Release

#1534 open port plugins
  exports.js
  plugins/aws/ec2/openHTTP.js
  plugins/aws/ec2/openHTTP.spec.js
  plugins/google/vpcnetwork/openHTTP.js
  plugins/google/vpcnetwork/openHTTP.spec.js
  plugins/oracle/networking/openHTTP.js
  plugins/oracle/networking/openHTTP.spec.js
Labels: readytogo, reviewed, Current Release

#1526 SAAS-13295: GCP - CLB Logging Enabled
  exports.js
  plugins/google/clb/clbLoggingEnabled.js
  plugins/google/clb/clbLoggingEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1525 SAAS-13294: GCP - API Key Active Services Plugin
  exports.js
  plugins/google/api/apiKeyActiveServices.js
  plugins/google/api/apiKeyActiveServices.spec.js
Labels: readytogo, reviewed, Current Release

#1531 Azure/infrastructure double encryption
  exports.js
  plugins/azure/postgresqlserver/postgresqlInfraDoubleEncryption.js
  plugins/azure/postgresqlserver/postgresqlInfraDoubleEncryption.spec.js
Labels: readytogo, reviewed, Current Release

#1523 SAAS-13292: GCP - Project API Keys Plugin
  exports.js
  plugins/google/api/projectAPIKeys.js
  plugins/google/api/projectAPIKeys.spec.js
Labels: readytogo, reviewed, Current Release

#1535 unattached disk
  exports.js
  plugins/azure/virtualmachines/unattachedDiskWithDefaultEncryption.js
  plugins/azure/virtualmachines/unattachedDiskWithDefaultEncryption.spec.js
Labels: readytogo, reviewed, Current Release

#1524 SAAS-13293: GCP - API Key API Restriction Plugin
  exports.js
  plugins/google/api/apiKeyAPIRestriction.js
  plugins/google/api/apiKeyAPIRestriction.spec.js
Labels: Current Release

#1482 mysql server has tags
  exports.js
  plugins/azure/mysqlserver/mysqlServerHasTags.js
  plugins/azure/mysqlserver/mysqlServerHasTags.spec.js
Labels: readytogo, reviewed, Current Release

#1518 plugin application gateway has tags
  exports.js
  plugins/azure/loadbalancer/applicationGatewayHasTags.js
  plugins/azure/loadbalancer/applicationGatewayHasTags.spec.js
Labels: readytogo, reviewed, Current Release

#1528 security contact role set to owner
  collectors/azure/collector.js
  exports.js
  helpers/azure/api.js
  helpers/azure/locations.js
  plugins/azure/securitycenter/securityContactRoleSetToOwner.js
  plugins/azure/securitycenter/securityContactRoleSetToOwner.spec.js
Labels: readytogo, reviewed, Current Release

#1530 azure cis benchmark plugins
  exports.js
  helpers/azure/api.js
  plugins/azure/logalerts/publicIpAddressLoggingEnabled.js
  plugins/azure/logalerts/publicIpAddressLoggingEnabled.spec.js
  plugins/azure/mysqlserver/mysqlFlexibleServersMinTls.js
  plugins/azure/mysqlserver/mysqlFlexibleServersMinTls.spec.js
  plugins/azure/networksecuritygroups/openHTTP.js
  plugins/azure/networksecuritygroups/openHTTP.spec.js
Labels: readytogo, reviewed, Current Release

#1527 security contact additional email plugin dev comp
  exports.js
  plugins/azure/securitycenter/securityContactAdditionalEmail.js
  plugins/azure/securitycenter/securityContactAdditionalEmail.spec.js
Labels: readytogo, reviewed, Current Release

#1529 AWS Plugins for New CIS-Benchmarks
  exports.js
  plugins/aws/cloudwatchlogs/monitoringMetrics.js
  plugins/aws/ec2/networkAclInboundTraffic.js
  plugins/aws/ec2/networkAclInboundTraffic.spec.js
  plugins/aws/s3/bucketMFADeleteEnabled.js
  plugins/aws/s3/bucketMFADeleteEnabled.spec.js
Labels: readytogo, reviewed, Current Release

#1498 s3BucketPolicyCloudFrontOAC
  exports.js
  plugins/aws/s3/bucketPolicyCloudFrontOac.js
  plugins/aws/s3/bucketPolicyCloudFrontOac.spec.js
Labels: readytogo, reviewed, Current Release

#1465 updated resource arn
  plugins/aws/fsx/fsxFileSystemEncrypted.js
Labels: readytogo, reviewed, hotfix, Current Release

#1541 updated api call for image builder
  helpers/aws/api.js
Labels: readytogo, reviewed, hotfix, Current Release

#1521 SAAS-12945/iam-policies-plugins
  helpers/aws/regions.js
  plugins/aws/iam/iamRolePolicies.js
  plugins/aws/iam/iamRolePolicies.spec.js
  plugins/aws/iam/rolePolicyUnusedServices.js
  plugins/aws/iam/rolePolicyUnusedServices.spec.js
  plugins/aws/lambda/lambdaOldRuntimes.js
Labels: enhancement, readytogo, reviewed, Current Release

#1574 Feature/saas 13752 azure https plugin
  exports.js
  plugins/azure/networksecuritygroups/openHTTPS.js
  plugins/azure/networksecuritygroups/openHTTPS.spec.js
Labels: readytogo, reviewed, Current Release
