Repository aquasecurity/cloudsploit, pull requests merged in 2024-04, with the labels that each got.

#1960 Bedrock model tags
  exports.js
  plugins/aws/bedrock/customModelHasTags.js
  plugins/aws/bedrock/customModelHasTags.spec.js
Labels: readytogo, reviewed, currentrelease

#1966 dynamodb deletion protection enabled
  exports.js
  plugins/aws/dynamodb/dynamoDeletionProtection.js
  plugins/aws/dynamodb/dynamoDeletionProtection.spec.js
Labels: readytogo, reviewed, currentrelease

#1979 containerAppManagedIdentity
  exports.js
  helpers/azure/api.js
  helpers/azure/locations.js
  helpers/azure/resources.js
  plugins/azure/containerapps/containerAppManagedIdentity.js
  plugins/azure/containerapps/containerAppManagedIdentity.spec.js
Labels: readytogo, reviewed, currentrelease

#1984 cosmosDbManagedIdentity
  exports.js
  plugins/azure/cosmosdb/cosmosdbManagedIdentity.js
  plugins/azure/cosmosdb/cosmosdbManagedIdentity.spec.js
Labels: readytogo, reviewed, currentrelease

#1985 cosmosdbLoggingEnabled
  exports.js
  helpers/azure/api.js
  plugins/azure/cosmosdb/cosmosdbDiagnosticLogs.js
  plugins/azure/cosmosdb/cosmosdbDiagnosticLogs.spec.js
Labels: readytogo, reviewed, currentrelease

#1980 Container app http only
  exports.js
  plugins/azure/containerapps/containerAppHttpsOnly.js
  plugins/azure/containerapps/containerAppHttpsOnly.spec.js
Labels: readytogo, reviewed, currentrelease

#1981 Container app external access
  exports.js
  plugins/azure/containerapps/externalNetworkAccess.js
  plugins/azure/containerapps/externalNetworkAccess.spec.js
Labels: readytogo, reviewed, currentrelease

#1990 syncing open source with saas
  helpers/aws/regions.js
  helpers/aws/regions_gov.js
  plugins/aws/bedrock/customModelEncryptionEnabled.js
  plugins/aws/bedrock/customModelHasTags.js
  plugins/aws/bedrock/customModelInVpc.js
  plugins/aws/bedrock/privateCustomModel.js
  plugins/aws/ec2/instanceLimit.js
  plugins/aws/ec2/instanceLimit.spec.js
  plugins/azure/sqldatabases/dbDataMaskingEnabled.js
  plugins/azure/storageaccounts/blobServiceLoggingEnabled.js
  plugins/azure/storageaccounts/queueServiceLoggingEnabled.js
  plugins/google/iam/serviceAccountKeyRotation.js
  plugins/google/iam/serviceAccountKeyRotation.spec.js
Labels: readytogo, currentrelease

#1887 Azure-Automation-Approved-Certificates?
  exports.js
  helpers/azure/api.js
  plugins/azure/automationAccounts/automationAcctApprovedCerts.js
  plugins/azure/automationAccounts/automationAcctApprovedCerts.spec.js
Labels: readytogo, reviewed, currentrelease

#1956 Azure/databricks workspace managed services cmk encrypted
  exports.js
  plugins/azure/databricks/workspaceManagedServicesCmk.js
  plugins/azure/databricks/workspaceManagedServicesCmk.spec.js
Labels: readytogo, reviewed, currentrelease

#1957 Azure databricks workspace diagnostic logs
  exports.js
  helpers/azure/api.js
  plugins/azure/databricks/workspaceDiagnosticLogs.js
  plugins/azure/databricks/workspaceDiagnosticLogs.spec.js
Labels: readytogo, reviewed, currentrelease

#1958 Azure databricks workspace no public ip
  exports.js
  plugins/azure/databricks/workspaceSecureCluster.js
  plugins/azure/databricks/workspaceSecureCluster.spec.js
Labels: readytogo, reviewed, currentrelease

#1959 Flywheel in vpc
  exports.js
  helpers/aws/api.js
  plugins/aws/comprehend/flywheelInVpc.js
  plugins/aws/comprehend/flywheelInVpc.spec.js
Labels: readytogo, reviewed, currentrelease

#1963 flexibleserverConnectionThrottle
  exports.js
  plugins/azure/postgresqlserver/flexibleServerConnectionThrottle.js
  plugins/azure/postgresqlserver/flexibleServerConnectionThrottle.spec.js
Labels: readytogo, reviewed, currentrelease

#1964 flexibleserverlogDisconnections
  exports.js
  plugins/azure/postgresqlserver/flexibleServerLogDisconnections.js
  plugins/azure/postgresqlserver/flexibleServerLogDisconnections.spec.js
Labels: readytogo, reviewed, currentrelease

#1965 aws cloudformation deletion policy
  exports.js
  helpers/aws/api.js
  helpers/aws/api_multipart.js
  plugins/aws/cloudformation/cloudformationDeletionPolicy.js
  plugins/aws/cloudformation/cloudformationDeletionPolicy.spec.js
Labels: readytogo, reviewed, currentrelease

#1969 aws lambda enhanced monitoring
  exports.js
  helpers/aws/api.js
  helpers/aws/api_multipart.js
  plugins/aws/lambda/lambdaEnhancedMonitoring.js
  plugins/aws/lambda/lambdaEnhancedMonitoring.spec.js
Labels: readytogo, reviewed, currentrelease

#1986 aws opensearch audit logs
  exports.js
  plugins/aws/opensearch/opensearchEnableAuditLogs.js
  plugins/aws/opensearch/opensearchEnableAuditLogs.spec.js
Labels: readytogo, reviewed, currentrelease

#1983 Authentication container app
  exports.js
  helpers/azure/api.js
  plugins/azure/containerapps/containerAppAuthEnabled.js
  plugins/azure/containerapps/containerAppAuthEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1978 Azure/Event-Grid-Domain-Diagnostic-Logs
  exports.js
  helpers/azure/api.js
  plugins/azure/eventGrid/domainDiagnosticLogs.js
  plugins/azure/eventGrid/domainDiagnosticLogs.spec.js
Labels: readytogo, reviewed, currentrelease

#1977 Azure/Event-Grid-Domain-Minimum-Tls-Version
  exports.js
  plugins/azure/eventGrid/domainMinimumTlsVersion.js
  plugins/azure/eventGrid/domainMinimumTlsVersion.spec.js
Labels: readytogo, reviewed, currentrelease

#1967 lambda code signing config enabled
  exports.js
  helpers/aws/api.js
  helpers/aws/api_multipart.js
  plugins/aws/lambda/lambdaCodeSigningEnabled.js
  plugins/aws/lambda/lambdaCodeSigningEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1962 guarddutyRDSprotection
  exports.js
  plugins/aws/guardduty/rdsProtectionEnabled.js
  plugins/aws/guardduty/rdsProtectionEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1968 aws lambda dead letter queue
  exports.js
  helpers/aws/api.js
  helpers/aws/api_multipart.js
  plugins/aws/lambda/lambdaDeadLetterQueue.js
  plugins/aws/lambda/lambdaDeadLetterQueue.spec.js
Labels: readytogo, reviewed, currentrelease

#1972 aws route53 in use
  exports.js
  plugins/aws/route53/route53InUse.js
  plugins/aws/route53/route53InUse.spec.js
Labels: readytogo, reviewed, currentrelease

#1973 aws workspace operational state
  exports.js
  plugins/aws/workspaces/workSpacesHealthyInstances.js
  plugins/aws/workspaces/workSpacesHealthyInstances.spec.js
Labels: question, readytogo, currentrelease
