Repository aquasecurity/cloudsploit, pull requests merged in 2024-01, with the labels that each got.

#1833 hotfix/updatedEKSVersions
  plugins/aws/eks/eksKubernetesVersion.js
  plugins/aws/eks/eksKubernetesVersion.spec.js
Labels: hotfix

#1811 Azure - VM Encryption At Host Plugin
  exports.js
  plugins/azure/virtualmachines/vmEncryptionAtHost.js
  plugins/azure/virtualmachines/vmEncryptionAtHost.spec.js
Labels: readytogo, reviewed, currentrelease

#1808 Azure - Namespace Infrastructure Encryption Enabled Plugin
  exports.js
  plugins/azure/servicebus/namespaceInfraEncryption.js
  plugins/azure/servicebus/namespaceInfraEncryption.spec.js
Labels: readytogo, reviewed, currentrelease

#1807 Azure - Namespace Public Access Plugin
  exports.js
  plugins/azure/servicebus/namespacePublicAccess.js
  plugins/azure/servicebus/namespacePublicAccess.spec.js
Labels: readytogo, reviewed, currentrelease

#1658 diagnostic logs enabled in recovery vault
  exports.js
  helpers/azure/api.js
  plugins/azure/recoveryService/recoveryVaultLoggingEnabled.js
  plugins/azure/recoveryService/recoveryVaultLoggingEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1777 content key policy exists
  exports.js
  helpers/azure/api.js
  plugins/azure/mediaServices/amsContentKeyPolicy.js
  plugins/azure/mediaServices/amsContentKeyPolicy.spec.js
Labels: readytogo, reviewed, currentrelease

#1798 vmss ad authentication
  exports.js
  plugins/azure/virtualmachinescaleset/scaleSetAdAuthEnabled.js
  plugins/azure/virtualmachinescaleset/scaleSetAdAuthEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1799 trusted launch enabled
  exports.js
  helpers/azure/api.js
  plugins/azure/virtualmachinescaleset/vmssTrustedLaunchEnabled.js
  plugins/azure/virtualmachinescaleset/vmssTrustedLaunchEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1819 vmss managed identity
  exports.js
  helpers/azure/api.js
  plugins/azure/virtualmachinescaleset/vmssManagedIdentityEnabled.js
  plugins/azure/virtualmachinescaleset/vmssManagedIdentityEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1800 vmss vtpm enabled
  exports.js
  plugins/azure/virtualmachinescaleset/scalesetVTPMEnabled.js
  plugins/azure/virtualmachinescaleset/scalesetVTPMEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1801 vmss secure boot enabled
  exports.js
  plugins/azure/virtualmachinescaleset/scalesetSecureBootEnabled.js
  plugins/azure/virtualmachinescaleset/scalesetSecureBootEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1817 check vmss approved extension
  exports.js
  plugins/azure/virtualmachinescaleset/vmssApprovedExtensions.js
  plugins/azure/virtualmachinescaleset/vmssApprovedExtensions.spec.js
Labels: readytogo, reviewed, currentrelease

#1803 Azure/Redis-Cache-Version
  exports.js
  plugins/azure/redisCache/redisVersion.js
  plugins/azure/redisCache/redisVersion.spec.js
Labels: readytogo, reviewed, currentrelease

#1815 Azure/acr content trust
  exports.js
  plugins/azure/containerregistry/acrContentTrustEnabled.js
  plugins/azure/containerregistry/acrContentTrustEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1804 Azure/Redis-cache-diagnostic-logs
  exports.js
  helpers/azure/api.js
  plugins/azure/redisCache/redisCacheDiagnosticLogs.js
  plugins/azure/redisCache/redisCacheDiagnosticLogs.spec.js
Labels: readytogo, reviewed, currentrelease

#1805 Azure/redis cache schedule updates
  exports.js
  helpers/azure/api.js
  plugins/azure/redisCache/redisCacheScheduledUpdates.js
  plugins/azure/redisCache/redisCacheScheduledUpdates.spec.js
Labels: readytogo, reviewed, currentrelease

#1829 Azure/Redis-cache-managed-identity
  exports.js
  plugins/azure/redisCache/redisCacheManagedIdentity.js
  plugins/azure/redisCache/redisCacheManagedIdentity.spec.js
Labels: readytogo, reviewed, currentrelease

#1818 Azure/Acr-Managed-Identity
  exports.js
  plugins/azure/containerregistry/acrManagedIdentityEnabled.js
  plugins/azure/containerregistry/acrManagedIdentityEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1821 Azure/Automation-Accounts
  exports.js
  helpers/azure/api.js
  helpers/azure/locations.js
  helpers/azure/resources.js
  plugins/azure/automationAccounts/automationAcctDiagnosticLogs.js
  plugins/azure/automationAccounts/automationAcctDiagnosticLogs.spec.js
  plugins/azure/containerregistry/acrManagedIdentityEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1823 Azure/automation account managed identity
  exports.js
  plugins/azure/automationAccounts/automationAcctDiagnosticLogs.js
  plugins/azure/automationAccounts/automationAcctManagedIdentity.js
  plugins/azure/automationAccounts/automationAcctManagedIdentity.spec.js
Labels: readytogo, reviewed, currentrelease

#1825 Azure/App-Configuration-Managed-identity
  exports.js
  helpers/azure/api.js
  helpers/azure/locations.js
  helpers/azure/resources.js
  plugins/azure/appConfigurations/appConfigManagedIdentity.js
  plugins/azure/appConfigurations/appConfigManagedIdentity.spec.js
Labels: readytogo, reviewed, currentrelease

#1827 Azure/app configuration diagnostic logs
  exports.js
  helpers/azure/api.js
  plugins/azure/appConfigurations/appConfigurationDiagnosticLogs.js
  plugins/azure/appConfigurations/appConfigurationDiagnosticLogs.spec.js
Labels: readytogo, reviewed, currentrelease

#1828 Azure/app configuration public access
  exports.js
  plugins/azure/appConfigurations/appConfigurationPublicAccess.js
  plugins/azure/appConfigurations/appConfigurationPublicAccess.spec.js
Labels: readytogo, reviewed, currentrelease

#1814 flexibleServerVersion
  exports.js
  plugins/azure/postgresqlserver/flexibleServerVersion.js
  plugins/azure/postgresqlserver/flexibleServerVersion.spec.js
Labels: readytogo, reviewed, currentrelease

#1822 enableDefenderForPostgresql
  exports.js
  plugins/azure/defender/enableDefenderForOSRD.js
  plugins/azure/defender/enableDefenderForOSRD.spec.js
Labels: readytogo, reviewed, currentrelease

#1824 flexibleServerVNetIntegrated
  exports.js
  plugins/azure/postgresqlserver/flexibleServerVNetIntegrated.js
  plugins/azure/postgresqlserver/flexibleServerVNetIntegrated.spec.js
Labels: readytogo, reviewed, currentrelease

#1826 flexibleServerPrivateDnsZone
  exports.js
  plugins/azure/postgresqlserver/flexibleServerPrivateDns.js
  plugins/azure/postgresqlserver/flexibleServerPrivateDns.spec.js
Labels: readytogo, reviewed, currentrelease

#1830 hotfix/SqlPublicAccess
  plugins/azure/sqlserver/noPublicAccess.js
  plugins/azure/sqlserver/noPublicAccess.spec.js
Labels: enhancement, reviewed, currentrelease

#1816 Azure/Aks-Diagnostic-Logs
  exports.js
  helpers/azure/api.js
  plugins/azure/kubernetesservice/aksDiagnosticLogsEnabled.js
  plugins/azure/kubernetesservice/aksDiagnosticLogsEnabled.spec.js
Labels: readytogo, reviewed, currentrelease

#1831 category changed
  exports.js
  plugins/azure/virtualmachinescaleset/autoInstanceRepairsEnabled.js
  plugins/azure/virtualmachinescaleset/autoInstanceRepairsEnabled.spec.js
  plugins/azure/virtualmachinescaleset/autoOsUpgradesEnabled.js
  plugins/azure/virtualmachinescaleset/autoOsUpgradesEnabled.spec.js
  plugins/azure/virtualmachinescaleset/autoscaleNotificationsEnabled.js
  plugins/azure/virtualmachinescaleset/autoscaleNotificationsEnabled.spec.js
  plugins/azure/virtualmachinescaleset/noEmptyScaleSets.js
  plugins/azure/virtualmachinescaleset/noEmptyScaleSets.spec.js
  plugins/azure/virtualmachinescaleset/scaleSetAutoscaleEnabled.js
  plugins/azure/virtualmachinescaleset/scaleSetAutoscaleEnabled.spec.js
  plugins/azure/virtualmachinescaleset/scaleSetHealthMonitoring.js
  plugins/azure/virtualmachinescaleset/scaleSetHealthMonitoring.spec.js
  plugins/azure/virtualmachinescaleset/scaleSetMultiAz.js
  plugins/azure/virtualmachinescaleset/scaleSetMultiAz.spec.js
  plugins/azure/virtualmachinescaleset/vmScaleSetHasTags.js
  plugins/azure/virtualmachinescaleset/vmScaleSetHasTags.spec.js
Labels: enhancement, reviewed, currentrelease

#1836 Saas 21769/az realtime triggers a b c d
  package.json
  plugins/azure/appConfigurations/appConfigManagedIdentity.js
  plugins/azure/appConfigurations/appConfigurationDiagnosticLogs.js
  plugins/azure/appConfigurations/appConfigurationPublicAccess.js
  plugins/azure/applicationGateway/agPreventionModeEnabled.js
  plugins/azure/applicationGateway/agRequestBodyInspection.js
  plugins/azure/applicationGateway/agSecurityLoggingEnabled.js
  plugins/azure/applicationGateway/agSslPolicy.js
  plugins/azure/applicationGateway/agWafEnabled.js
  plugins/azure/applicationGateway/applicationGatewayHasTags.js
  plugins/azure/appservice/alwaysOnEnabled.js
  plugins/azure/appservice/appInsightsEnabled.js
  plugins/azure/appservice/appServiceAccessRestriction.js
  plugins/azure/appservice/authEnabled.js
  plugins/azure/appservice/automatedBackupsEnabled.js
  plugins/azure/appservice/backupRetentionPeriod.js
  plugins/azure/appservice/clientCertEnabled.js
  plugins/azure/appservice/disableFTPDeployments.js
  plugins/azure/appservice/ftpsOnlyAccessEnabled.js
  plugins/azure/appservice/http20Enabled.js
  plugins/azure/appservice/httpsOnlyEnabled.js
  plugins/azure/appservice/identityEnabled.js
  plugins/azure/appservice/javaVersion.js
  plugins/azure/appservice/netFrameworkVersion.js
  plugins/azure/appservice/phpVersion.js
  plugins/azure/appservice/pythonVersion.js
  plugins/azure/appservice/remoteDebuggingDisabled.js
  plugins/azure/appservice/scmSiteAccessRestriction.js
  plugins/azure/appservice/tlsVersionCheck.js
  plugins/azure/appservice/webAppsADEnabled.js
  plugins/azure/automationAccounts/automationAcctDiagnosticLogs.js
  plugins/azure/automationAccounts/automationAcctManagedIdentity.js
  plugins/azure/bastion/bastionHostExists.js
  plugins/azure/blobservice/blobContainersPrivateAccess.js
  plugins/azure/blobservice/blobServiceImmutable.js
  plugins/azure/cdnprofiles/detectInsecureCustomOrigin.js
  plugins/azure/cdnprofiles/endpointLoggingEnabled.js
  plugins/azure/containerregistry/acrAdminUser.js
  plugins/azure/containerregistry/acrAnonymousPullAccessEnabled.js
  plugins/azure/containerregistry/acrCMKEncryption.js
  plugins/azure/containerregistry/acrContentTrustEnabled.js
  plugins/azure/containerregistry/acrHasTags.js
  plugins/azure/containerregistry/acrLogAnalyticsEnabled.js
  plugins/azure/containerregistry/acrPublicAccess.js
  plugins/azure/cosmosdb/automaticFailoverEnabled.js
  plugins/azure/cosmosdb/cosmosPublicAccessDisabled.js
  plugins/azure/cosmosdb/cosmosdbHasTags.js
  plugins/azure/defender/enableDefenderForAppService.js
  plugins/azure/defender/enableDefenderForContainers.js
  plugins/azure/defender/enableDefenderForDNS.js
  plugins/azure/defender/enableDefenderForKeyVaults.js
  plugins/azure/defender/enableDefenderForOSRD.js
  plugins/azure/defender/enableDefenderForSqlServers.js
  plugins/azure/defender/enableDefenderForStorage.js
  plugins/azure/defender/enableDefenderForVMs.js
  plugins/azure/defender/enableEndpointIntegration.js
Labels: readytogo, reviewed, currentrelease
